package main

var arcadeVideos = map[string]string{
	"1941":            "rkG0L6jhxQI",
	"1942":            "Em7UwOOBvlA",
	"1943j":           "kntCwchJWfw",
	"1943kai":         "YRjNWVU64kk",
	"1943mii":         "eTq5CnekJ3g",
	"1943u":           "kntCwchJWfw",
	"1944":            "ijA-uXBqGFw",
	"19xx":            "9NcTNoGjFvE",
	"280zzzap":        "GYReNE2X06Y",
	"3wonders":        "uxClDHEPjGI",
	"4dwarrio":        "5WVusaaXggc",
	"afighter":        "bh0u34wZoGo",
	"alexkidd":        "DXXD2v7PeN4",
	"alibaba":         "Gab0qHXdbr0",
	"alienaru":        "mjo3SX5G0iM",
	"amidars":         "6zTJR0nZa6g",
	"anteater":        "Lz_i7ZUH218",
	"arkanoid":        "Th-Z6QQ5AOQ",
	"arkanoidj":       "Th-Z6QQ5AOQ",
	"arkanoiduo":      "Th-Z6QQ5AOQ",
	"armorcar":        "C8gOJVwjtIs",
	"armwar":          "v0RwBJPtEGw",
	"asteroid":        "_TKiRvGfw3Q",
	"asteroidsdeluxe": "MoPGVxZRNy8",
	"atetris":         "gTeaC1GpsOk",
	"atetrisc":        "gTeaC1GpsOk",
	"atlantis2":       "2JuB_OD4G1c",
	"attackfc":        "_TmQODia2QM",
	"avsp":            "l5oFATk5gh0",
	"azurian":         "zuO1VI1W3jo",
	"bagman":          "LigsGhuo2Zg",
	"ballbomb":        "uMD-UJvlp-0",
	"batcir":          "zSjtMzhcRWM",
	"battroad":        "Cmh8ElenmJk",
	"beastfp":         "7R9RNjvKfUA",
	"berzerk":         "DFSQ0Pl4KDk",
	"bigkong":         "6oU4NVBoxBY",
	"bilyard":         "iMPb6qspR-c",
	"bionicc":         "xkTasNER4vI",
	"birdiy":          "u5AHBNAqPdI",
	"blkhole":         "JpsQsGBe6Qw",
	"blktiger":        "ZzKStmMAiHM",
	"blockgal":        "6-u1Zkn21nc",
	"blueshrk":        "PVaNo0Zv9t0",
	"bodyslam":        "DIWl7YE29M0",
	"bombjack":        "XvHk6LTh-Ks",
	"boothill":        "HXFkVN0fq5Q",
	"botanic":         "pEeWH2OUJn0",
	"breakout":        "hW7Sg5pXAok",
	"brubber":         "t62w3tD6HsU",
	"btime":           "QlPp7WEnaCI",
	"bubbles":         "0t5BfbIeJjI",
	"bublbobl":        "BuXOSBb4hQw",
	"bullfgt":         "mWd9UPEGEM8",
	"bwidow":          "0uXjYpiPgyQ",
	"calipso":         "SpwC_nVTRpE",
	"canyon":          "05Ni8E526Qs",
	"captcomm":        "eu9QOpj3r-Q",
	"catacomb":        "MZ5HWITBXl8",
	"cavenger":        "zH6wFG6loPA",
	"cawing":          "ev1rgJm6uWw",
	"cclimber":        "onqBxoDRB_I",
	"centiped":        "oQhUKhgWUac",
	"centiped3":       "oQhUKhgWUac",
	"choko":           "MmqwdrW_e4",
	"ckong":           "lC3LGEV13V8",
	"ckongdks":        "UBHJhla8TO4",
	"ckongo":          "50PiBHs3Y4I",
	"ckongpt2":        "Z4xXEX2zvyY",
	"clowns":          "Q5_wpVKH_a0",
	"clubpacm":        "i27lK3yZ5SE",
	"colony7":         "ULv1yrOOFnU",
	"combatsc":        "",
	"commando":        "-LY3OHf8hUs",
	"computerspace":   "",
	"contrae":         "rD9G7OCmsfk",
	"cosmo":           "JtSQmjvRmKA",
	"crater":          "",
	"crbaloon":        "",
	"crush2":          "",
	"csclub":          "",
	"cworld2j":        "Kqi8H-bn6GI",
	"cybots":          "bQ9iCjncR8I",
	"daimakai":        "",
	"daimakair":       "",
	"darkplnt":        "",
	"ddonpach":        "iJwhq2pkhhc",
	"ddragon":         "jo6R6LqpNNY",
	"ddragon2":        "jjLJbucpCak",
	"ddsom":           "8alVk4Zi5A0",
	"ddtod":           "axBRSw0gDWk",
	"defender":        "0FXDLtwz86E",
	"demoderm":        "",
	"devilfsg":        "",
	"digdug":          "zOuLiKwHciw",
	"digdug2":         "xK7WbWGbYzg",
	"dimahoo":         "l4o10EXaqnY",
	"dino":            "uif1ONYv660",
	"dkong":           "UBHJhla8TO4",
	"dkong3":          "n3kjQzcp7Lk",
	"dkongjr":         "",
	"domino":          "o9cbxTFGxVQ",
	"dominos":         "",
	"dorodon":         "Ik2R4_dpuvg",
	"dotrikun":        "",
	"dotron":          "9ZGW8QvysdU",
	"dremshpr":        "",
	"dstlk":           "dgxkP6ZiEGQ",
	"dynwar":          "cWCOZ76_3jA",
	"ebases":          "",
	"ecofghtr":        "94UTtzYdJw0",
	"eeekkp":          "f66sSvsHwmU",
	"eggor":           "4J2E2yWX0u0",
	"eyes":            "UtJkcJ6ObwI",
	"f1dream":         "q4YKHfaUmfI",
	"fantzone":        "As3rKii7pZA",
	"ffight":          "xm3OqLXBt2I",
	"flicky":          "Gth96brPsxM",
	"foodf":           "XN1KkuD3Guw",
	"forgottn":        "PYJfoesXYC8",
	"frenzy":          "wijgReO3Zqs",
	"frogger":         "1rUPuz2Z9NY",
	"futurespy":       "",
	"galaga3":         "1MQl56etots",
	"galagamw":        "29VVkfuXkVI",
	"galaxian":        "",
	"galxwars":        "",
	"ganbare":         "",
	"gaplus":          "2SWqdUfv7J4",
	"gaunt2":          "",
	"gauntlet":        "",
	"gberet":          "",
	"gemini":          "5Pk6e7lIzVE",
	"ghouls":          "odPJN_lZJgY",
	"gigawing":        "j56eUNx4sZk",
	"gng":             "uIhyjrXVhzg",
	"gorf":            "zyarBNUisj8",
	"gorkans":         "Eh3hKLD-MRs",
	"gorodki":         "",
	"gravitar":        "iOi9-jqNtXc",
	"grobda":          "c4B0iUN1GpA",
	"gulunpa":         "UnPBvKviCoM",
	"gunfight":        "",
	"gunsmoke":        "gZ4LUuk1kAc",
	"higemaru":        "R5mg6XPqtBs",
	"horizon":         "YG1GlnQ7os0",
	"hsf2":            "UbKrhj-dEgk",
	"imsorry":         "",
	"invaders":        "",
	"invadpt2":        "",
	"jin":             "5cYkhI2Y5qw",
	"journey":         "tBVKE-1sBKY",
	"joust":           "kfytuoG-Xzo",
	"jumpshot":        "Iidq8O0JRxo",
	"jyangoku":        "",
	"kick":            "p6F_DSqiUtI",
	"kickman":         "",
	"kidniki":         "BQFsBfOawtM",
	"kingball":        "",
	"kingballj":       "",
	"knights":         "jwv_I7dy0z4",
	"kod":             "IsM3_h1xav0",
	"konek":           "",
	"koroleva":        "",
	"kot":             "",
	"kroozr":          "",
	"kungfum":         "sx9ive1tFPM",
	"ladybug":         "BOBYMZ14tQQ",
	"lagunar":         "",
	"ldrun":           "",
	"ldrun2":          "",
	"ldrun3":          "",
	"ldrun4":          "",
	"lizwiz":          "",
	"llander":         "",
	"losttomb":        "",
	"lrescue":         "",
	"luctoday":        "",
	"lunarbat":        "",
	"lupin3a":         "",
	"lwings":          "0f4jWQyf-fs",
	"mappy":           "X08oIPJPFX8",
	"mario":           "JHlUEJXaxfY",
	"mars":            "XANY_hBaFY4",
	"maxrpm":          "",
	"mayday":          "wol3cGp6KP0",
	"maze":            "",
	"mbombrd":         "_IrHPOcVFNU",
	"megaman":         "PbIjksXp6RI",
	"megaman2":        "Hxsoq3Fqu6U",
	"mercs":           "1p4CZHwFWYo",
	"mimonscr":        "f2LziS7XYgA",
	"minefld":         "",
	"mmatrix":         "",
	"mooncrgx":        "Dl5stQgPGYQ",
	"moonwar":         "",
	"motos":           "FFvFGV_HjL4",
	"mpang":           "goXjMzjcBU4",
	"mpatrol":         "QoH2zNAIcXI",
	"mrdo":            "5_BBQWed8Vk",
	"mrdofix":         "",
	"mrgoemon":        "uy3if2RKwK8",
	"mrtnt":           "A6R7K8VH_Ck",
	"mrviking":        "",
	"msh":             "zaRBbaKT8oY",
	"mshvsf":          "Y70AlMBPoIY",
	"mspacman":        "",
	"msword":          "63oFgwnruxQ",
	"mtwins":          "c42MRUnciZk",
	"mvsc":            "",
	"myhero":          "MxFlq-CfVZ8",
	"nemo":            "ZOF0C9jyeWY",
	"ninjakun":        "",
	"nrallyx":         "",
	"nwarr":           "z441EuNeYnc",
	"omegab":          "7n7q9dlSKCQ",
	"orbitron":        "",
	"pacman":          "yvHPE20pPPo",
	"pacnchmp":        "",
	"pacnpal":         "",
	"pacplus":         "",
	"pang3":           "",
	"pengo":           "csNPwcWWGFo",
	"pestplce":        "POlWy2WTdQw",
	"phoenix":         "OEyOJt-ZjNU",
	"pickin":          "",
	"pisces":          "uL2ZhTS4D1M",
	"pitfall2":        "",
	"playball":        "hQu3-NF4avM",
	"pleiadce":        "",
	"pleiads":         "mudL0K5Txlg",
	"pnickj":          "",
	"pokonyan":        "",
	"polyplay":        "",
	"polyplay2":       "",
	"pong":            "X1-8ofKGsvY",
	"ponpoko":         "",
	"pooyan":          "1RDFTeOQrvU",
	"popeye":          "MSSKpeeB23s",
	"powerdrv":        "",
	"progear":         "LOUxSbUg0Mo",
	"puckman":         "2PHC1gzLrGE",
	"punisher":        "BMmI1Ez9ajo",
	"pzloop2":         "",
	"qad":             "eBHIiV2xmaw",
	"qbert":           "HKIbhaQfs-A",
	"qndream":         "EWuKBBEj3t4",
	"qtono2j":         "",
	"radarscp":        "",
	"raflesia":        "nywVINJBaHk",
	"rallyx":          "",
	"rampage":         "he-_v3NZz_A",
	"regulus":         "",
	"rescue":          "66-ywnJTXmc",
	"ringdest":        "",
	"robby":           "",
	"robotron":        "",
	"rpatroln":        "",
	"rushatck":        "",
	"rygar":           "FK_OQIgIPqw",
	"sarge":           "1SsnbqOcE68",
	"sbagman":         "Z-Pab-a8pbs",
	"sbrkout":         "",
	"schaser":         "",
	"scobra":          "Y6FK9jNBURY",
	"scramble":        "zRlRcIsIKkY",
	"seawolf":         "",
	"seawolf2":        "",
	"sectionz":        "",
	"seganinj":        "",
	"sf":              "",
	"sf2":             "xI284D4y1q4",
	"sf2ce":           "KJne-82X4L0",
	"sf2hf":           "",
	"sfa":             "",
	"sfa2":            "cFZLsfhw4m0",
	"sfa3":            "xJwwVeQuZ6I",
	"sfz2al":          "",
	"sfzch":           "",
	"sgemf":           "",
	"shinobi":         "IiVhLpQtQcI",
	"shollow":         "",
	"shtrider":        "",
	"shuffle":         "",
	"shuttlei":        "",
	"sidearms":        "",
	"silkworm":        "y-Eq361-xWE",
	"silvland":        "",
	"sinistar":        "U8S5VSwcNag",
	"skyskipr":        "",
	"slammast":        "",
	"snapjack":        "hifWexvJmOo",
	"solarfox":        "",
	"solomon":         "",
	"solomonj":        "",
	"sosterm":         "n9xj0n4c0os",
	"spacerace":       "",
	"spacezap":        "O9LWxEIzp6Y",
	"spatter":         "",
	"spcenctr":        "",
	"spdcoin":         "Ji2nP7YGVp8",
	"spelunk2":        "",
	"spelunkr":        "",
	"spf2t":           "zVIY0vbdHQ0",
	"splat":           "V1yjoBzVnF0",
	"sprglbpg":        "tZMfgJ_1ul0",
	"sprint1":         "",
	"sprint2":         "",
	"spyhunt":         "PT_X-YELPjY",
	"squaitsa":        "akpMhxCWNHA",
	"srumbler":        "",
	"ssf2":            "",
	"ssf2t":           "",
	"stargate":        "0LfGye0e5VY",
	"stargrds":        "",
	"starjack":        "",
	"starjacks":       "",
	"stratgyx":        "",
	"strider":         "FZwzRRHn53k",
	"superpac":        "KYpuKc86gT8",
	"swat":            "ggeOjClMig0",
	"szaxxon":         "",
	"tapper":          "z5ozpJm0iDs",
	"tazmania":        "",
	"teddybb":         "",
	"theend":          "gydQFicUafs",
	"theglobp":        "oTYTlrWF1ko",
	"tigeroad":        "eN0e3G41620",
	"timber":          "VV4kauEVeys",
	"timeplt":         "v_OzRECVOk8",
	"todruaga":        "LdNGOARBDJ0",
	"tokiob":          "",
	"tp84":            "",
	"tp84a":           "",
	"tp84b":           "",
	"travrusa":        "",
	"tricktrp":        "",
	"trojanr":         "L1FVWdlQNG8",
	"tron":            "GmPbeHCkAmc",
	"turbotag":        "",
	"turtles":         "QMfw_ZMPHfQ",
	"twotigerc":       "",
	"ultratnk":        "",
	"uniwars":         "",
	"unsquad":         "4TB62ZPYGLU",
	"upndown":         "",
	"vanvan":          "",
	"varth":           "",
	"vball":           "",
	"vballb":          "",
	"vhunt2":          "bevWXe8oG5M",
	"victorycb":       "",
	"vindctr2":        "",
	"vortex":          "ANagqRpGmzI",
	"vsav":            "H7Y4quP8ii0",
	"vsav2":           "yRfFtIAtfHU",
	"vulgus":          "",
	"wacko":           "Ko6g2NtZ0go",
	"warofbug":        "",
	"wboy":            "Bvim7O9RvK0",
	"willow":          "LumZP0rpoDM",
	"wmatch":          "",
	"wof":             "iNo7UhzwZs4",
	"woodpeck":        "",
	"wow":             "",
	"xevious":         "VpyFHvPizYM",
	"xmcota":          "6rmyvfXayME",
	"xmvsf":           "XrFB2N1aBbs",
	"youjyudn":        "-hGNlvt8zZU",
	"zaxxon":          "ul2vX8-dmTA",
	"zigzagb":         "9y2Z5KqWHqM",
}

var arcadeLongplays = []string{
	"005|https://youtu.be/Z4EorUfbRDI",
	"1000 Miglia: Great 1000 Miles Rally|https://www.youtube.com/watch?v=12-luPvjjVs",
	"1941: Counter Attack|https://www.youtube.com/watch?v=rkG0L6jhxQI",
	"1942|https://www.youtube.com/watch?v=Em7UwOOBvlA",
	"1943: The Battle of Midway|https://www.youtube.com/watch?v=kntCwchJWfw",
	"1944: The Loop Master|http://www.youtube.com/watch?v=ijA-uXBqGFw",
	"1945k III|https://www.youtube.com/watch?v=3-R5lkN3PGY",
	"19XX: The War Against Destiny|http://www.youtube.com/watch?v=9NcTNoGjFvE",
	"3 Count Bout|http://www.youtube.com/watch?v=4K39cEB8TuE",
	"3 On 3 Dunk Madness (Prototype)|https://youtu.be/QFLJRmNWvOQ",
	"4-D Warriors|https://youtu.be/5WVusaaXggc",
	"64th. Street: A Detective Story|http://youtu.be/1VdgTb3pX6c",
	"88 Games|http://www.youtube.com/watch?v=aUmrGdTFmBA",
	"A Jax|https://youtu.be/HRaW57eaBoI",
	"A.B. Cop|http://www.youtube.com/watch?v=6njLXs-K2Ww",
	"Acrobat Mission|https://youtu.be/SVlYLm-lKJQ",
	"Act-Fancer: Cybernetick Hyper Weapon|https://youtu.be/Gs7QCQtHWMk",
	"Action Fighter|https://youtu.be/bh0u34wZoGo",
	"Adventure Quiz 2: Capcom World 2|https://youtu.be/Kqi8H-bn6GI",
	"Adventure Quiz 2: Hatena? no Daibouken|https://youtu.be/3bD6sUz3oAw",
	"Adventure Quiz: Capcom World|https://youtu.be/2Xaxqz1tnlM",
	"Aero Fighters|http://www.youtube.com/watch?v=h8tJBvz-sHY",
	"Aero Fighters 2|http://www.youtube.com/watch?v=PXc0Rksr61I",
	"Aero Fighters 3|http://www.youtube.com/watch?v=mKpC_lnB7FM",
	"Aeroboto|https://youtu.be/tQ_4GPTCJUw",
	"Afterburner|https://youtu.be/84qaXESXdT4",
	"Afterburner II|https://youtu.be/W2loyeq9pDA",
	"Aggressors of Dark Combat|http://www.youtube.com/watch?v=KQXR1f1aonA",
	"Air Assault|https://youtu.be/565rOZePGZ0",
	"Air Attack|https://youtu.be/wVsjJssfBwA",
	"Air Buster: Trouble Speciality Raid Unit|http://youtu.be/fhqVIVgsYo4",
	"Air Duel|http://youtu.be/iL5HPq1B4-g",
	"Air Gallet|http://www.youtube.com/watch?v=bTAls1WnjsE",
	"Airwolf|http://www.youtube.com/watch?v=D--ajlwPCac",
	"Akkanbeder|https://youtu.be/OlfLpwyafrw",
	"Akumajou Dracula|https://youtu.be/d5HGvVfiNN8",
	"Alcon|https://youtu.be/kT_mHWEztXc",
	"Alex Kidd: The Lost Stars|http://www.youtube.com/watch?v=DXXD2v7PeN4",
	"Alien 3: The Gun|https://youtu.be/htUjhFtgtEY",
	"Alien Challenge|http://www.youtube.com/watch?v=Y98RKNIvvLE",
	"Alien Sector|https://youtu.be/cRnmBj036Mw",
	"Alien Storm|http://www.youtube.com/watch?v=t5w707nUsnU",
	"Alien Syndrome|https://www.youtube.com/watch?v=dC0wrCI0-EI",
	"Alien vs Predator|http://www.youtube.com/watch?v=l5oFATk5gh0",
	"Aliens|http://www.youtube.com/watch?v=1Yumj628t2Y",
	"Alpha Mission II|http://www.youtube.com/watch?v=sZN0b4STzwU",
	"Alpine Ski|https://youtu.be/YXCaZ47rvus",
	"Altered Beast|http://www.youtube.com/watch?v=DqHpyHR1P0I",
	"Ambush|https://youtu.be/vqEj_oKo0tE",
	"Andro Dunos|http://www.youtube.com/watch?v=iQOrXlf34es",
	"Anteater|https://youtu.be/Lz_i7ZUH218",
	"Aqua Jack|http://www.youtube.com/watch?v=bZ5nZHy8atA",
	"Arabian Fight|http://youtu.be/TDMCcbn1CKg",
	"Arabian Magic|https://youtu.be/VDXdF10I4Gs",
	"Arbalester|http://www.youtube.com/watch?v=3HYXNFSFTf8",
	"Arcadia|https://youtu.be/leip3TgYLFY",
	"Arcana Heart 3|http://www.youtube.com/watch?v=iYJQQt7GpzE",
	"Arch Rivals|https://youtu.be/F1qAuu0ZnNE",
	"Area 88|https://youtu.be/gDn5c_yG_pg",
	"Arkanoid|http://www.youtube.com/watch?v=Th-Z6QQ5AOQ",
	"Armed Police Batrider|http://www.youtube.com/watch?v=fjZMLAKkGJ0",
	"Armed Police Unit Gallop|https://youtu.be/OLIlg3Q2vIc",
	"Armored Warriors|http://www.youtube.com/watch?v=v0RwBJPtEGw",
	"Art of Fighting|http://www.youtube.com/watch?v=-iQwJMIS7OU",
	"Art of Fighting 2|http://www.youtube.com/watch?v=QBPmfdl2iDw",
	"Art of Fighting 3|http://www.youtube.com/watch?v=CYHK6nMj-nU",
	"Ashita no Joe|https://youtu.be/_N7BilQOF_A",
	"Ashura Blaster|http://www.youtube.com/watch?v=sq7JgDmUu2I",
	"Asterix|http://youtu.be/-LhEovW4Uqw",
	"Asteroids|https://youtu.be/_TKiRvGfw3Q",
	"Astra Superstars|https://youtu.be/M0unp5Rw5k8",
	"Astro Flash|https://youtu.be/BtVuxQQtsjE",
	"Asuka & Asuka|https://youtu.be/RKHTiubXjMQ",
	"Asura Blade: Sword of Destiny|https://youtu.be/duF6jOfuywo",
	"Athena|https://youtu.be/tba3bc7AXfY",
	"Athena no Hatena?|https://youtu.be/psGif5w4ktM",
	"Atomic Boy|https://youtu.be/YN1n6rIJIrQ",
	"Atomic Punk|https://youtu.be/ND7KQkEshc8",
	"Atomic Robo-Kid|https://youtu.be/uoY2DF5u2BI",
	"Atomic Runner Chelnov|http://www.youtube.com/watch?v=Xr6C5vX5YxM",
	"Aurail|http://www.youtube.com/watch?v=hzjVU0ApKcA",
	"Avengers|http://www.youtube.com/watch?v=T8bY4UxOF4M",
	"Avengers In Galactic Storm|http://www.youtube.com/watch?v=nQJk8OhAGoM",
	"Avenging Spirit|http://youtu.be/M9vrVknosUM",
	"Azurian Attack|https://youtu.be/zuO1VI1W3jo",
	"B.Rap Boys|http://youtu.be/Ey9qUTwawsQ",
	"Back Fire|https://youtu.be/tn8MF9jtjNc",
	"Backfire!|http://www.youtube.com/watch?v=x3tpBOMzLyw",
	"Backstreet Soccer|http://www.youtube.com/watch?v=WLqERZwUTvM",
	"Bad Dudes vs. Dragon Ninja|http://www.youtube.com/watch?v=u2ddQfLZ0PM",
	"Badlands|https://youtu.be/tJy40mkUKcY",
	"Badlands (Konami)|http://www.youtube.com/watch?v=mvItwCcdIaE",
	"Bagman|https://youtu.be/LigsGhuo2Zg",
	"Bakuretsu Quiz Ma-Q Dai Bouken|https://youtu.be/2Brl1msjj8g",
	"Bakutotsu Kijuutei|https://youtu.be/EJu8IK4giQI",
	"Ball Boy|https://youtu.be/bMjLlpLgMlk",
	"Balloon Brothers|https://youtu.be/6VLr7p7Ul4g",
	"Baluba-Louk no Densetsu|https://youtu.be/fQiFlw29yBE",
	"Bang Bang Ball|https://youtu.be/Iyua_ttSylw",
	"Bang Bang Buster|http://www.youtube.com/watch?v=3DncxpUdQEQ",
	"Bang Bead|http://www.youtube.com/watch?v=OXfnZekue90",
	"Bank Panic|https://youtu.be/7H_2mqjR92A",
	"Baryon: Future Assault|https://youtu.be/MEqKaNebfDY",
	"Batman|https://youtu.be/0Puqqj66G2Q",
	"Batsugun|http://www.youtube.com/watch?v=qSMwbFgcdys",
	"Battlantis|http://youtu.be/UibcZcr4sCI",
	"Battle Balls|http://youtu.be/pbVg27r1RFA",
	"Battle Bubble|https://youtu.be/vf8O0H6UjHM",
	"Battle Chopper|http://youtu.be/RBCrNoEiTOE",
	"Battle Circuit|http://www.youtube.com/watch?v=zSjtMzhcRWM",
	"Battle Flip Shot|http://www.youtube.com/watch?v=sFZHNw2DxYY",
	"Battle K-Road|http://youtu.be/c2Xv-KWGPBI",
	"Battle Rangers|https://www.youtube.com/watch?v=qsbpsBqVK5c",
	"Battletoads|http://youtu.be/EH40wIgWU-g",
	"Bay Route|http://www.youtube.com/watch?v=W8u7raSo-Ho",
	"Beastorizer|https://youtu.be/JsfXCbD3SXI",
	"Bega's Battle|https://youtu.be/UjBp4qrdRxw",
	"Bells & Whistles|http://youtu.be/gOmsBZyinUY",
	"Bermuda Triangle|https://youtu.be/5Il_xik0sXc",
	"Berzerk|http://youtu.be/DFSQ0Pl4KDk",
	"Best Bout Boxing|https://youtu.be/hFogjWbDUfc",
	"Best of Best|http://www.youtube.com/watch?v=VejTF27dcp4",
	"Bestri|http://youtu.be/PuxbpQoh6PI",
	"Big Bang|http://youtu.be/YJ_mLjRMLIA",
	"Big Karnak|http://youtu.be/mw8QpIejpg4",
	"Big Striker|https://youtu.be/pYeDp9reiGc",
	"Biomechanical Toy|http://www.youtube.com/watch?v=7jHx1DpttSw",
	"Bionic Commando|http://www.youtube.com/watch?v=xkTasNER4vI",
	"Black Heart|https://youtu.be/eoXqOcWZBdA",
	"Black Tiger|http://youtu.be/ZzKStmMAiHM",
	"Blade Master|http://www.youtube.com/watch?v=SMsWyT9DxTk",
	"Blasteroids|https://youtu.be/hE4VHvGlsmE",
	"BlaZeon|http://www.youtube.com/watch?v=Y3gw4DI_X9s",
	"Blazing Star|http://www.youtube.com/watch?v=NLpLqgqimtI",
	"Blazing Tornado|https://youtu.be/PwSe6fDJ7l4",
	"Block Hole|http://www.youtube.com/watch?v=-IcRX3O6aAQ",
	"Block Out|http://www.youtube.com/watch?v=2Tn_WoNxG2M",
	"Blomby Car|http://youtu.be/wiUpzhaRq-4",
	"Blood Bros.|http://www.youtube.com/watch?v=jGNoU-dQzNk",
	"Blood Warrior|http://www.youtube.com/watch?v=NBpFTYavXNY",
	"Bloodstorm|http://youtu.be/ade9hmVbDbI",
	"Bloody Roar|http://youtu.be/3bvGSBe5woo",
	"Blue Hawk|http://youtu.be/JVi1J6oT-_Q",
	"Blues Journey|http://www.youtube.com/watch?v=68slIqrMEEo",
	"Bomb Jack|http://www.youtube.com/watch?v=XvHk6LTh-Ks",
	"Bomb Jack Twin|https://youtu.be/80C-qubo3YI",
	"Bomb Kick|http://youtu.be/7AgRZAA6-ZI",
	"Bomber Man World|http://youtu.be/cVslW13HDl0",
	"Bongo|https://youtu.be/S4Nze1NMsEY",
	"Bonze Adventure|http://www.youtube.com/watch?v=qHNt_ocn85o",
	"Boogie Wings|http://www.youtube.com/watch?v=zBJaVkJdvsc",
	"Boong-Ga Boong-Ga|https://youtu.be/aNTtaDV_yvU",
	"Boot Hill|https://youtu.be/HXFkVN0fq5Q",
	"Brain|https://youtu.be/Bssw-eSNFAY",
	"Brave Blade|http://youtu.be/f7oOuylh_BI",
	"Break Thru|https://www.youtube.com/watch?v=2CX4-iGuC4E",
	"Breakers|http://www.youtube.com/watch?v=WqtsNLfo0jA",
	"Breakers Revenge|http://www.youtube.com/watch?v=Z8JCOSNqX-c",
	"Brute Force|https://youtu.be/ziA6EWZjqLU",
	"Bubble Bobble|http://www.youtube.com/watch?v=BuXOSBb4hQw",
	"Buccaneers|http://www.youtube.com/watch?v=p4V-UnoXxoI",
	"Bucky O'Hare|https://www.youtube.com/watch?v=cx97kGScC00",
	"Buggy Boy|http://youtu.be/KV4BzTMATuM",
	"Bullet|http://www.youtube.com/watch?v=N6zARWRGXWY",
	"Bump'n'Jump|https://youtu.be/hakrA4aSeT8",
	"Burger Time|https://youtu.be/QlPp7WEnaCI",
	"Burning Fight|http://www.youtube.com/watch?v=LR2NzP9Zrts",
	"Burning Rival|http://youtu.be/0fEELKWwRpg",
	"Buster Bros.|https://www.youtube.com/watch?v=aOTSD_BhWHk",
	"C.O.W.Boys of Moo Mesa|http://youtu.be/ipWubItVIvo",
	"Cabal|http://youtu.be/WPSwJPsPiek",
	"Cachat|https://youtu.be/wm1BOKZZwiY",
	"Cadash|http://www.youtube.com/watch?v=ajL8HAj8dYU",
	"Cadillacs and Dinosaurs|http://www.youtube.com/watch?v=uif1ONYv660",
	"Cal .50 - Caliber Fifty|http://youtu.be/hXLjvCkW1wM",
	"Cannon Dancer|https://youtu.be/FHzBMyF1HQU",
	"Captain America and The Avengers|http://youtu.be/JBRZkOfEKgM",
	"Captain Commando|http://www.youtube.com/watch?v=eu9QOpj3r-Q",
	"Captain Tomaday|http://www.youtube.com/watch?v=a4KXiUd3Yq4",
	"Carket Ball|https://youtu.be/zkKOIBQMR5A",
	"CarnEvil|http://www.youtube.com/watch?v=gBMslh22Vr0",
	"Carrier Air Wing|http://www.youtube.com/watch?v=ev1rgJm6uWw",
	"Catt|http://youtu.be/UJZQYspZZLg",
	"Caveman Ninja|http://www.youtube.com/watch?v=nj8M8WZWIzM",
	"Centipede|http://youtu.be/oQhUKhgWUac",
	"Chack'n Pop|https://youtu.be/t5s-98uyGkY",
	"Chain Reaction|http://www.youtube.com/watch?v=sYWNFrXdl8E",
	"Champion Boxing|https://youtu.be/YHFuxeql35E",
	"Champion Pro Wrestling|https://youtu.be/0KXoEkR-KcQ",
	"Championship Sprint|https://www.youtube.com/watch?v=PI7kZf9QSac",
	"Change Air Blade|http://youtu.be/oVA4Zf3FzQc",
	"Chaos Heat|http://youtu.be/cmSo4g_Wlfo",
	"Charlie Ninja|http://www.youtube.com/watch?v=Y4afrDm-k9o",
	"Chase H.Q.|https://youtu.be/K_BJrvI0fec",
	"Check Man|https://youtu.be/lrGrP1vouUw",
	"Chequered Flag|https://www.youtube.com/watch?v=P6db6qm-Xaw",
	"Chibi Marukochan Deluxe Quiz|http://www.youtube.com/watch?v=oPuVFSIG6P4",
	"Chicken Shift|http://youtu.be/VDLwaPtsdGo",
	"Chiki Chiki Boys|https://www.youtube.com/watch?v=cNGnvxG_q88",
	"Chimera Beast (Prototype)|http://youtu.be/H3W-dlYuN9A",
	"Chinese Hero|https://youtu.be/4s-0wNkDoyg",
	"Cho Zetsurin Jin Beraboman|https://youtu.be/pSKS5U5b9o4",
	"Choky! Choky!|http://www.youtube.com/watch?v=HVHT7ZDFUYY",
	"Chopper|https://youtu.be/oVOehsGUqzw",
	"Chouji Meikyuu Legion|http://www.youtube.com/watch?v=2tdljHmvjL8",
	"Choukou Senki Kikaioh|https://youtu.be/5cmN1E4O3gs",
	"Chuka Taisen|http://www.youtube.com/watch?v=IpVS5MQVs5U",
	"City Bomber|http://youtu.be/r5hXvFCXa00",
	"Clash Road|https://youtu.be/mAXnCMjtp0E",
	"Cleopatra Fortune|http://youtu.be/qiarmdPXaRw",
	"Cobra Command|http://www.youtube.com/watch?v=h9fMG6pjGdo",
	"Commando|http://www.youtube.com/watch?v=-LY3OHf8hUs",
	"Congo Bongo|https://youtu.be/8Chz73oZgyg",
	"Continental Circus|http://www.youtube.com/watch?v=k5HrTM4quqg",
	"Contra|http://www.youtube.com/watch?v=rD9G7OCmsfk",
	"Cookie & Bibi|https://youtu.be/whrImtXm2s8",
	"Cookie & Bibi 2|https://youtu.be/8YNaRxg0fU0",
	"Cookie & Bibi 3|https://youtu.be/BR2ZXHBrJBg",
	"Cop 01|http://youtu.be/vpXGHkl_d3M",
	"Cosmic Chasm|http://youtu.be/yJ0Szz8gpiE",
	"Cosmic Cop|http://youtu.be/D6SbOFh_6h8",
	"Cotton|https://youtu.be/8KvfSDONQpM",
	"Cotton 2|http://youtu.be/-SlkhfU4T4g",
	"Crayon Shinchan Orato Asobo|https://youtu.be/B2RjWooZ-nY",
	"Crazy Cop|https://youtu.be/0l9xB1QfJUY",
	"Crazy Fight|http://www.youtube.com/watch?v=SicXKKHPjzk",
	"Crazy Taxi|http://youtu.be/qjIGkv0_dEM",
	"Crime City|http://www.youtube.com/watch?v=kGpNWSWscAk",
	"Crime Fighters|http://www.youtube.com/watch?v=BpsfZZnZes4",
	"Cross Blades|https://www.youtube.com/watch?v=QPghq3pu-qI",
	"Crossed Swords|http://www.youtube.com/watch?v=H485or8VOC8",
	"Crouching Tiger Hidden Dragon 2003 Super Plus (Unlicensed)|https://youtu.be/wkj08ignM4w",
	"Crude Buster|http://www.youtube.com/watch?v=UErpVgQKRMI",
	"Crystal Castles|https://youtu.be/ZXyY96YFRtg",
	"Cybattler|http://youtu.be/T2XiOdMFcHM",
	"Cyber Cycles|http://youtu.be/RCLdg6RO-GU",
	"Cyberbots: Fullmetal Madness|http://www.youtube.com/watch?v=bQ9iCjncR8I",
	"Cyberlip|http://www.youtube.com/watch?v=11mrYej9b_g",
	"Cyvern|http://youtu.be/IfjSAM1OVvQ",
	"D.D. Crew|http://www.youtube.com/watch?v=k0T8NdU0u3U",
	"Daiku no Gensan|https://youtu.be/WyQj8ErHsbM",
	"Daioh|https://youtu.be/ECc2myURZgo",
	"Daisenpuu|https://youtu.be/MJD4B0M6eu0",
	"Daisu Kiss|https://youtu.be/peJtarBtD8Y",
	"Dancing Eyes|https://www.youtube.com/watch?v=kV06tzbAM2g",
	"Dangerous Seed|http://youtu.be/86_uLpzkVE8",
	"Daraku Tenshi - The Fallen Angels|http://www.youtube.com/watch?v=LlbLYhYOCKo",
	"Darius|http://www.youtube.com/watch?v=dw2PMdIpHdE",
	"Darius II|http://www.youtube.com/watch?v=ezpkyTjXBBM",
	"Dark Edge|http://youtu.be/zBXZ9f-dCMM",
	"Darkstalkers: Night Warriors|https://youtu.be/dgxkP6ZiEGQ",
	"Darwin 4078|https://youtu.be/YpNE-rnJI-0",
	"Daytona USA|http://www.youtube.com/watch?v=GAcMqFTkAs8",
	"Dead Angle|https://youtu.be/kE6-o0sGiQc",
	"Dead Connection|http://www.youtube.com/watch?v=_o5n8rhiwdw",
	"Deathsmiles|https://youtu.be/FPIs5r0ksss",
	"Defender|https://youtu.be/0FXDLtwz86E",
	"Demon Front|http://www.youtube.com/watch?v=FojNKSZWX4U",
	"Demon's World|http://youtu.be/BvDI3amnozE",
	"Denjin Makai II: Guardians|http://www.youtube.com/watch?v=mn3xLSz_YpY",
	"Desert Assault|http://youtu.be/N4fwrObCbrw",
	"Desert Breaker|http://www.youtube.com/watch?v=MprUV7Y7sXE",
	"Devastators|https://youtu.be/14ARJ5YJOzw",
	"Devil World|http://www.youtube.com/watch?v=gSRH2qXpcL8",
	"Die Hard Arcade|https://youtu.be/NkgGX4ELgNE",
	"Diet Family|http://youtu.be/RH9UUbOU_cI",
	"Diet Go Go|http://www.youtube.com/watch?v=sOWvhemQmtw",
	"Dino Rex|http://www.youtube.com/watch?v=TzoK9LFiMHI",
	"Discs of Tron|http://youtu.be/9ZGW8QvysdU",
	"DJ Boy|http://youtu.be/PlAjXwu5y6k",
	"DoDonPachi|http://youtu.be/iJwhq2pkhhc",
	"DoDonPachi Dai-Ou-Jou|http://youtu.be/LBuKNb673SU",
	"DoDonPachi Dai-Ou-Jou Black Label|http://youtu.be/TD779mLfW_8",
	"Dogyuun|http://www.youtube.com/watch?v=jEsbGf0XC7Y",
	"Dolmen|https://youtu.be/mQ1V5tevi2g",
	"Domino Man|https://youtu.be/o9cbxTFGxVQ",
	"Don Doko Don|http://www.youtube.com/watch?v=ttOqXyGSnwA",
	"Donkey Kong|http://youtu.be/UBHJhla8TO4",
	"Donkey Kong 3|https://youtu.be/n3kjQzcp7Lk",
	"Donkey Kong Jr.|http://www.youtube.com/watch?v=GmOJN-zq6yg",
	"DonPachi|http://www.youtube.com/watch?v=lDZAso9vsX0",
	"Double Dragon|http://youtu.be/jo6R6LqpNNY",
	"Double Dragon (NeoGeo)|http://www.youtube.com/watch?v=byIIafnor_s",
	"Double Dragon 2 - The Revenge|http://youtu.be/jjLJbucpCak",
	"Double Dragon 3 - The Rosetta Stone|http://youtu.be/kvadjk-srWg",
	"Double Wings|http://youtu.be/Irk_pE6GGHI",
	"DownTown|https://www.youtube.com/watch?v=0DNRTo_LRTg",
	"Dr. Micro|https://youtu.be/mqa_10imdt4",
	"Dragon Blaze|http://www.youtube.com/watch?v=FaEiqlUd6cs",
	"Dragon Bowl|http://www.youtube.com/watch?v=vxuIKgEVmCY",
	"Dragon Breed|http://www.youtube.com/watch?v=lfr0VkasGoc",
	"Dragon Buster|https://youtu.be/EX3Ca28mJdM",
	"Dragon Master|https://www.youtube.com/watch?v=p__Jo2ArHG4",
	"Dragon Saber|https://youtu.be/Po0x3MLt2ns",
	"Dragon Spirit|https://youtu.be/evyjfb50UvQ",
	"Dragon Unit|http://www.youtube.com/watch?v=dXov_6JNkAQ",
	"Dragonball Z V.R.V.S|http://youtu.be/GRVWH2uzRB8",
	"Dragoon Might|https://www.youtube.com/watch?v=oKUjRvXDmM8",
	"Dramatic Adventure Quiz Keith & Lucy|https://www.youtube.com/watch?v=7HNc-6U2Y3w",
	"Dream Soccer '94|http://youtu.be/DG-pDwd0YPc",
	"Dream World|https://youtu.be/i7J3DSY4K1Y",
	"Drift Out|http://www.youtube.com/watch?v=PIY-iZAaPKM",
	"Drift Out '94: The Hard Order|http://youtu.be/KanDNIo6m9Y",
	"Driving Force|http://youtu.be/4jHB32dR7JU",
	"Dungeon Magic|https://youtu.be/bXxFGK75LnU",
	"Dungeons & Dragons: Shadow Over Mystara|http://www.youtube.com/watch?v=8alVk4Zi5A0",
	"Dungeons & Dragons: Tower of Doom|http://www.youtube.com/watch?v=axBRSw0gDWk",
	"Dunk Dream '95|http://youtu.be/JNrlrNVGFow",
	"Dyger|https://youtu.be/mq7JInMgcF4",
	"Dyna Gear|http://youtu.be/ZzkZMMnXjVQ",
	"Dynablaster|https://youtu.be/T8kdVYRkY0A",
	"Dynamic Shoot Kyousou|https://www.youtube.com/watch?v=Z05d0FafG4M",
	"Dynamite Dux|http://www.youtube.com/watch?v=MNk12p9vIlg",
	"Dynasty Wars|http://www.youtube.com/watch?v=cWCOZ76_3jA",
	"E-SWAT|http://www.youtube.com/watch?v=1Bk04N-0ZLM",
	"Eagle Shot Golf|https://youtu.be/C-Bai3a5vFk",
	"Earth Defense Force|https://youtu.be/BJeRy7Ygwwk",
	"Eco Fighters|http://www.youtube.com/watch?v=94UTtzYdJw0",
	"Ehrgeiz: God Bless the Ring|http://youtu.be/bC-4HWcLF1U",
	"Eight Forces|http://www.youtube.com/watch?v=HlGb4FR1SlA",
	"Eight Man|http://www.youtube.com/watch?v=hObhDF6DEvQ",
	"Elevator Action|http://youtu.be/LM5reigEnv4",
	"Emeraldia|http://youtu.be/X3cMm3ZJFV0",
	"Empire City: 1931|http://youtu.be/IjArVzMFmZw",
	"Enduro Racer|http://youtu.be/JExdaxGxjko",
	"Escape from the Planet of the Robot Monsters|http://youtu.be/nFYwBqC11EQ",
	"Espgaluda|http://youtu.be/TMlPLXJojc0",
	"Evil Stone|http://youtu.be/kXvhWQuPQLY",
	"Exciting Soccer|https://youtu.be/CTjDj6MEtCw",
	"Explosive Breaker|http://youtu.be/PGSxIjwovrU",
	"Express Raider|http://youtu.be/pTTkzWoY6jM",
	"Extermination|https://www.youtube.com/watch?v=Ym14oRbCLUY",
	"Extreme Downhill|https://www.youtube.com/watch?v=02WmBvmvNYY",
	"Exzisus|http://youtu.be/Du13h9D2Zt4",
	"F-1 Dream|http://youtu.be/q4YKHfaUmfI",
	"F-1 Grand Prix|https://youtu.be/64Mcc0QoZeg",
	"Fancy World|http://youtu.be/cuNigg0KbgA",
	"Fantasy Land|http://youtu.be/w-0DEoIMJvo",
	"Fantasy Zone|http://www.youtube.com/watch?v=As3rKii7pZA",
	"Fantasy Zone II:  The Tears of Opa Opa|http://www.youtube.com/watch?v=iP6EHTkr-C0",
	"Fast Lane|http://youtu.be/2OfQ6BenNHY",
	"Fatal Fury|http://www.youtube.com/watch?v=GuO1BhTUdvE",
	"Fatal Fury 2|http://youtu.be/HbWPpkTN4tY",
	"Fatal Fury 3: Road to the Final Victory|http://youtu.be/aZa05jLtFi0",
	"Fatal Fury Special|http://www.youtube.com/watch?v=AlZ1q2Gddsc",
	"Fight Fever|http://www.youtube.com/watch?v=GniTJ2VdP8Y",
	"Fighter's Impact A|https://youtu.be/IfoptBWEv0Y",
	"Fighting Layer|https://youtu.be/pfHnbcUVPgA",
	"Fighting Roller|https://youtu.be/54YDa7ZM1s4",
	"Fighting Vipers|http://www.youtube.com/watch?v=-zJwjXUG8u8",
	"Final Fight|http://www.youtube.com/watch?v=xm3OqLXBt2I",
	"Final Star Force|http://www.youtube.com/watch?v=jRwvBRIek5s",
	"Final Tetris|http://youtu.be/cd_g8CLYoIc",
	"Fire Barrel|https://www.youtube.com/watch?v=f8f_EuMj170",
	"FixEight|http://www.youtube.com/watch?v=0CgUFvLAbKA",
	"Flash Point|http://youtu.be/9KyUgK3o5cM",
	"Flashgal|http://youtu.be/g18DwWMLnGc",
	"Flying Tiger|https://www.youtube.com/watch?v=np3FNNSAjDQ",
	"Football Champ|http://www.youtube.com/watch?v=4mgjOMzq68k",
	"Forgotten Worlds|https://www.youtube.com/watch?v=PYJfoesXYC8",
	"Formation Armed F|http://www.youtube.com/watch?v=gSRxnNM3bo8",
	"Fujiyama Buster|http://youtu.be/KgDNiUVhuIU",
	"Full Throttle|http://youtu.be/S90VrljRDGQ",
	"Funky Jet|http://www.youtube.com/watch?v=DguGCHmZ4k8",
	"G-LOC Air Battle|https://www.youtube.com/watch?v=58JKeizTZF0",
	"G-Stream|https://youtu.be/ozY2M-Zjuis",
	"G.I. Joe|http://www.youtube.com/watch?v=NYODi95wIcQ",
	"Gaia Crusaders|http://www.youtube.com/watch?v=TSb8hrMLGCI",
	"Gaiapolis|http://youtu.be/cts1-rHBjrk",
	"Gain Ground|http://youtu.be/na94rrvmJNI",
	"Galactic Storm|https://youtu.be/0NShg2Tb3iI",
	"Galaga|http://youtu.be/29VVkfuXkVI",
	"Galaga '88|https://youtu.be/62h9LUt3OQg",
	"Galaga 3|https://www.youtube.com/watch?v=1MQl56etots",
	"Galaxy Fight|http://www.youtube.com/watch?v=tPvO1ab-JrA",
	"Galaxy Force II|https://youtu.be/-uzBUwh5msY",
	"Galaxy Gunners|https://youtu.be/gA825t0kNOI",
	"Galmedes|https://www.youtube.com/watch?v=bXShhEWOQGE",
	"Ganbare Ginkun|http://youtu.be/2SgO8OeXmRg",
	"Gang Wars|http://youtu.be/BkcGz-I4QxU",
	"Ganryu|http://www.youtube.com/watch?v=nVAplIZtbSE",
	"Gardia|http://youtu.be/gXJVr5TYMiM",
	"Garou - Mark of the Wolves|http://www.youtube.com/watch?v=yOkyX-eiofw",
	"Gate of Doom|http://youtu.be/42-jSs4XWrs",
	"Gemini Wing|https://youtu.be/5Pk6e7lIzVE",
	"Genix|https://youtu.be/lN_HUOLv3XM",
	"Geo Storm|https://www.youtube.com/watch?v=Yt5TsutdBHE",
	"Ghost Pilots|http://www.youtube.com/watch?v=W-eirUeg2AM",
	"Ghostlop (Prototype)|http://www.youtube.com/watch?v=oaUCJWiTBZ4",
	"Ghosts'n'Goblins|http://www.youtube.com/watch?v=uIhyjrXVhzg",
	"Ghouls 'n Ghosts|http://youtu.be/odPJN_lZJgY",
	"Gigandes|http://www.youtube.com/watch?v=-7nbULSUVws",
	"Gigawing|http://www.youtube.com/watch?v=j56eUNx4sZk",
	"Ginga NinkyouDen|https://youtu.be/4HNanHjFWFI",
	"Goal! Goal! Goal!|http://www.youtube.com/watch?v=bSPQbx5He-U",
	"Gokujou Parodius|http://www.youtube.com/watch?v=1bLDK-b-ll8",
	"Golden Axe|http://youtu.be/1v7VL4P4tbI",
	"Golden Axe: The Duel|http://youtu.be/ZGRA_z29SlQ",
	"Got-cha Mini Game Festival|https://youtu.be/2q05cc3NroA",
	"Gourmet Battle Quiz Ryorioh CooKing|https://youtu.be/qkhVbonDqz0",
	"Gradius|http://youtu.be/2-OaZv3Jfkg",
	"Gradius II: GOFER no Yabou|http://youtu.be/h1kF4k3xUW4",
	"Gradius III|http://youtu.be/KMf-pNBCG_4",
	"Gradius IV: Fukkatsu|http://youtu.be/xsVarCMS5js",
	"Grand Cross|https://youtu.be/-sZrQmI1GcY",
	"Grand Striker 2|https://www.youtube.com/watch?v=zPXaoy4Z30w",
	"Great 1000 Miles Rally: Evolution Model!!!|https://www.youtube.com/watch?v=_4MxtSGZ9FY",
	"Green Beret: Rush'n Attack|http://www.youtube.com/watch?v=L4cgbzMJ-Ps",
	"Grind Stormer|http://www.youtube.com/watch?v=Xq2iQIFLfs0",
	"Grobda|http://youtu.be/c4B0iUN1GpA",
	"Groove on Fight: Gouketsuji Ichizoku 3|https://youtu.be/-8F0HmtDomE",
	"Growl|http://www.youtube.com/watch?v=GKyk45O4LCw",
	"Guardian|https://youtu.be/z-kbrxPnUmc",
	"Guardian Force|http://youtu.be/gY32Ny8cuWw",
	"Guardian Storm|https://youtu.be/NNnpmr9VVPs",
	"Guardians of the 'Hood|http://youtu.be/fVUj52KMS4U",
	"Gulf War II|http://youtu.be/DoyCAe9opbk",
	"Gulf. Storm|https://youtu.be/lW7wGFOSQFU",
	"Gun Ball|https://youtu.be/SVUCL5kuujA",
	"Gun Force II|http://youtu.be/L2KP4rjACXQ",
	"Gun Frontier|http://youtu.be/-ZY_-5GWZsk",
	"Gun Master|https://youtu.be/lJkctMCOvXM",
	"Gun.Smoke|https://youtu.be/gZ4LUuk1kAc",
	"Gunbarich|https://youtu.be/qDuysH2-O3o",
	"Gunbird|http://www.youtube.com/watch?v=Edyfmww6kzA",
	"Gundhara|http://youtu.be/qpqxTU2Rpvs",
	"Gunforce: Battle Fire Engulfed Terror Island|http://youtu.be/Br4UoLiwqF8",
	"Gururin|http://www.youtube.com/watch?v=l38qT7SjzwY",
	"Gyrodine|https://www.youtube.com/watch?v=tlNQBt6DG_o",
	"Gyruss|http://youtu.be/haehLgNNB4c",
	"Hachoo!|https://www.youtube.com/watch?v=-6T6o17BPKU",
	"Hammerin' Harry|http://youtu.be/SFzLIDNhYcU",
	"Hang-On|http://www.youtube.com/watch?v=TopLKeDqYhw",
	"Hang-On Jr.|https://www.youtube.com/watch?v=TS2avY5zO_A",
	"Hard Hat|https://www.youtube.com/watch?v=LYKLW36ZMLY",
	"Hard Head|https://youtu.be/sZHMZ2czRg4",
	"Haunted Castle|http://www.youtube.com/watch?v=WSLRJP2iXGk",
	"Head Panic|https://youtu.be/AoDNEXBXOzg",
	"Heaven's Gate|https://youtu.be/VQLf_lA3FaU",
	"Heavy Barrel|https://youtu.be/WRy2MLavHVM",
	"Heavy Smash: The Future Sports|https://youtu.be/2QCD8u-3YTw",
	"Heavy Unit|https://youtu.be/pSO-e5OMuhk",
	"Hellfire|https://youtu.be/GgO-EAwksVE",
	"Hippodrome|https://youtu.be/Vp18MpLmTzA",
	"Holosseum|https://youtu.be/Xz8vH06BzMU",
	"Hook|http://youtu.be/ZGIYWabon2Q",
	"Hoops '96|http://youtu.be/pSr0eb_yZ3E",
	"Hotdog Storm|https://www.youtube.com/watch?v=aPuqESX2mtE",
	"House of the Dead|http://www.youtube.com/watch?v=aSmaU6Rm2Xk",
	"Hunchback|https://youtu.be/9o5nh-URiJA",
	"Hyper Athlethe|https://youtu.be/Yr__NUHrCdo",
	"Hyper Bishi Bashi Champ|http://youtu.be/Q9Ihi8B9z5U",
	"Hyper Crash|http://youtu.be/BYNbuuH1pCA",
	"Hyper Duel|http://youtu.be/XHfJmubD6JA",
	"Hyper Pacman|https://youtu.be/W2WSo4Y0gDQ",
	"Hyper Street Fighter 2: The Anniversary Edition|http://www.youtube.com/watch?v=UbKrhj-dEgk",
	"Ikari III: The Rescue|https://www.youtube.com/watch?v=tP6Hyi1A-po",
	"Ikari Warriors|https://www.youtube.com/watch?v=8ECiZUWoz8c",
	"Image Fight|https://www.youtube.com/watch?v=A9ONA6YYz_4",
	"In the Hunt|https://www.youtube.com/watch?v=Bew_JEgZbUc",
	"Indiana Jones and the Temple of Doom|http://youtu.be/HnFM7qP4cZo",
	"Insector X|http://www.youtube.com/watch?v=gpNHzsanASw",
	"Intrepid|https://youtu.be/yM_m2G-a_Rg",
	"Iron|https://youtu.be/iUvGtxUBuqU",
	"Iron Horse|http://youtu.be/rzSBlUAx9Qw",
	"Ironclad:  Brikin'ger Choutetsu|http://www.youtube.com/watch?v=dIRJMOtFMlI",
	"Irritating Maze|http://www.youtube.com/watch?v=9E-201c6Vv8",
	"Itazura Tenshi|http://youtu.be/orbr0x_oODI",
	"J. J. Squawkers|https://www.youtube.com/watch?v=Er-FEpd9bZQ",
	"Jail Break|https://www.youtube.com/watch?v=ku79EaDfetE",
	"Joe & Mac Returns|http://www.youtube.com/watch?v=b00R5Yis14I",
	"Joshi Volleyball|https://youtu.be/pBM7J7Q03QM",
	"Judge Dredd (Prototype)|https://youtu.be/xvml11tToOE",
	"Jue Zhan Tian Huang|https://youtu.be/2401Oip3cdQ",
	"Juju Densetsu|https://www.youtube.com/watch?v=nnRMfeuoR5w",
	"Jump Kids|https://www.youtube.com/watch?v=YxLHVkGM-eY",
	"Jungle King & Jungle Hunt & Pirate Pete|https://youtu.be/9hw3hOSRymA",
	"Juno First|https://youtu.be/abYqxh6QDQw",
	"Jurassic Park|http://www.youtube.com/watch?v=l6I-4CcKAXo",
	"Kabuki Klash: Far East of Eden|http://www.youtube.com/watch?v=_bF_QCUX72w",
	"Kabuki-Z|https://youtu.be/h9JgQrvbTzY",
	"Kageki|https://youtu.be/7AL2zNOKeJo",
	"Kaiketsu Yanchamaru|https://www.youtube.com/watch?v=T25TJyRWx08",
	"Kaitei Dai Sensou|https://youtu.be/JQfkqV6Vy08",
	"Karaoke Quiz Intro Don Don!|https://youtu.be/0JOZoeOUUSk",
	"Karate Blazers|http://www.youtube.com/watch?v=ZQKfkyZVCeA",
	"Karate Champ|http://youtu.be/gwV3xqS9_aQ",
	"Karate Champ (a)|https://youtu.be/CqMWIKKpnTk",
	"Karnov|http://youtu.be/tK5v-QWQ4_w",
	"Karnovs Revenge|http://www.youtube.com/watch?v=ujnRoLwiIlg",
	"Kero Kero Keroppi no Issyoni Asobou|http://www.youtube.com/watch?v=VKY4U3lAfaI",
	"Ketsui:  Kizuna Jigoku Tachi|http://youtu.be/xPesUmCpBKI",
	"Kick and Run|http://youtu.be/DY9C6yq8CUA",
	"Kick Rider|http://youtu.be/230GMjHOMTU",
	"Kick Start Wheelie King|http://youtu.be/WidQOU67JWo",
	"Kid Niki: Radical Ninja|https://www.youtube.com/watch?v=BQFsBfOawtM",
	"KiKi KaiKai|http://www.youtube.com/watch?v=KhY0l2d5GOU",
	"Killer Instinct|http://www.youtube.com/watch?v=85C7bF0osAc",
	"Killer Instinct 2|http://www.youtube.com/watch?v=vTqPLuy1D8E",
	"King of the Monsters|http://www.youtube.com/watch?v=fpkyLJsiHSw",
	"King of the Monsters 2: The Next Thing|http://www.youtube.com/watch?v=hzcGFbUBWhY",
	"Kingdom Grand Prix|http://youtu.be/71c8lhy4x-o",
	"Kizuna Encounter - Super Tag Battle|http://www.youtube.com/watch?v=LlgnUr_5_JE",
	"Knights of the Round|http://www.youtube.com/watch?v=jwv_I7dy0z4",
	"Knights of Valour|http://youtu.be/bvhzKHkNLkk",
	"Knights of Valour 2|http://youtu.be/yqQs8msFugA",
	"Knights of Valour 2 Plus: Nine Dragons|http://youtu.be/WKyM7rMwG5k",
	"Knuckle Bash|http://www.youtube.com/watch?v=SsogXXPF92A",
	"Knuckle Joe|https://youtu.be/fZ1cLtNeKec",
	"Kollon|http://youtu.be/Lflg3LexFNk",
	"Kozure Okami|http://www.youtube.com/watch?v=kxhpLIbwMLU",
	"Krull|https://www.youtube.com/watch?v=rleN__MKNts",
	"Kung-Fu Master|https://youtu.be/sx9ive1tFPM",
	"Kyukyouku Sentai Dadandarn|https://youtu.be/i51jyMB57EI",
	"LA Girl|https://youtu.be/z2J_GF45oUU",
	"Labyrinth Runner|http://youtu.be/39yVta4J_ic",
	"Lady Frog|http://youtu.be/Lf9h2FoZtEo",
	"Lady Master of Kung Fu|https://youtu.be/R6tfGkplt4c",
	"Last Blade|http://www.youtube.com/watch?v=pYoVkj-WCrg",
	"Last Blade 2|http://www.youtube.com/watch?v=-DQsa_nM9e4",
	"Last Duel: Inter Planet War 2012|http://youtu.be/oBr0h3wTRCI",
	"Last Resort|http://www.youtube.com/watch?v=y1xUT7QJ-mA",
	"Last Striker|https://youtu.be/Irj1SXJXcCw",
	"Last Survivor|http://www.youtube.com/watch?v=dvWBlaj1LiI",
	"League Bowling|http://www.youtube.com/watch?v=UWoGPJGjnAo",
	"LED Storm|https://youtu.be/vsqJtga-raU",
	"Legend of Heroes|https://youtu.be/t7kwu5L0byg",
	"Legend of Success Joe|http://www.youtube.com/watch?v=PHhuFChvqd0",
	"Legendary Wings|http://www.youtube.com/watch?v=0f4jWQyf-fs",
	"Leprechaun|https://youtu.be/_8MPSXMq820",
	"Let's Attack Crazy Cross|https://youtu.be/hHnuJtcv7UQ",
	"Lethal Crash Race|http://www.youtube.com/watch?v=Q5AjMDp7zKY",
	"Lethal Enforcers II: Gun Fighters|http://www.youtube.com/watch?v=NVJepwG-r74",
	"Lethal Thunder|http://youtu.be/_zw1lV9M_IU",
	"Liberator|https://youtu.be/NxR2DB8bR6g",
	"Lifeforce|http://youtu.be/Nt9BQvDEXk0",
	"Lightning Fighters|https://youtu.be/dVYqLLuHK9g",
	"Liquid Kids|http://www.youtube.com/watch?v=sKU1FuVCgiM",
	"Logger|https://youtu.be/9R0m3bAj2_Q",
	"M.I.A.: Missing in Action|https://youtu.be/ZWaVbe5tkPg",
	"Mach Breakers: Numan Athletics 2|https://youtu.be/fFugiDuY3W0",
	"Macross Plus|https://www.youtube.com/watch?v=bANmQHetFOo",
	"Mad Alien|https://www.youtube.com/watch?v=lRj-2qhpB0Y",
	"Mad Crasher|https://youtu.be/rIvj5Y7jGVw",
	"Mad Motor|https://www.youtube.com/watch?v=gye9qXvXOOE",
	"Mad Shark|http://www.youtube.com/watch?v=7ikbiABYriA",
	"Magic Bubble|https://www.youtube.com/watch?v=wnhhcTObCJQ",
	"Magic Sword - Heroic Fantasy|http://www.youtube.com/watch?v=63oFgwnruxQ",
	"Magical Crystals|https://youtu.be/9c03VytA1hQ",
	"Magical Drop|https://www.youtube.com/watch?v=8Ov62aA919E",
	"Magical Drop 2|http://www.youtube.com/watch?v=mywJySnhYPU",
	"Magical Drop III|http://www.youtube.com/watch?v=X4aOHQxbJ9o",
	"Magical Error wo Sagase|https://youtu.be/Nh-i5A91dO8",
	"Magican Lord|http://www.youtube.com/watch?v=H7ToKGzgXm0",
	"Marble Madness|http://youtu.be/XzlA1JTPMto",
	"Marchen Maze|https://youtu.be/9vlP4rwl7zs",
	"Mariner|https://youtu.be/NitwXQSNz4o",
	"Mario Bros.|http://youtu.be/JHlUEJXaxfY",
	"Markham|https://youtu.be/WHRqBHGNKDs",
	"Mars Matrix|http://www.youtube.com/watch?v=wPn2J842gyg",
	"Martial Champion|https://youtu.be/tiw52nIiAeQ",
	"Martial Masters|http://www.youtube.com/watch?v=ac65Nf9HmKI",
	"Marvel Super Heroes|https://youtu.be/zaRBbaKT8oY",
	"Marvel Super Heroes VS Street Fighter|https://youtu.be/Y70AlMBPoIY",
	"Marvel Vs Capcom|https://youtu.be/gLWS5SrVohQ",
	"Masked Riders Club Battle Race|https://youtu.be/gWf2a_6yI3U",
	"Master of Weapon|http://www.youtube.com/watch?v=FvgL7enhDK4",
	"Maximum Force|http://www.youtube.com/watch?v=W3hQ9feh7u4",
	"Mazinger Z|https://www.youtube.com/watch?v=GOEaTRrJtTA",
	"Mega Blast|http://www.youtube.com/watch?v=jlaXGd-SUbY",
	"Mega Man: The Power Battle|http://www.youtube.com/watch?v=PbIjksXp6RI",
	"Mega Zone|http://youtu.be/3CKC1qfRew8",
	"Megaman 2: The Power Fighters|http://www.youtube.com/watch?v=Hxsoq3Fqu6U",
	"Meikyu Jima|https://youtu.be/dIyCOmDEtIQ",
	"Mercs|https://www.youtube.com/watch?v=1p4CZHwFWYo",
	"Metafox|http://www.youtube.com/watch?v=5HecsMeP_so",
	"Metal Black|http://www.youtube.com/watch?v=V3cwogMB9o0",
	"Metal Saver|https://youtu.be/io5CwFWKnGM",
	"Metal Slug|http://www.youtube.com/watch?v=lMx4iLp-EAc",
	"Metal Slug 2|http://www.youtube.com/watch?v=lw8yq1ubQG0",
	"Metal Slug 3|http://www.youtube.com/watch?v=OPCHeaqZZBQ",
	"Metal Slug 4|http://www.youtube.com/watch?v=ngfD2YrTbIo",
	"Metal Slug 5|http://www.youtube.com/watch?v=IjM7kJ6Kj1Q",
	"Metal Slug X|http://www.youtube.com/watch?v=sfParGc8BJw",
	"Metamoquester|http://www.youtube.com/watch?v=3qZ5sNZvpIQ",
	"Metamorphic Force|http://youtu.be/bmhQpUngdf4",
	"Metro-Cross|https://youtu.be/tyTHqUgqu3k",
	"Michael Jacksons Moonwalker|http://www.youtube.com/watch?v=pzth1QT6xoY",
	"Midnight Resistance|https://www.youtube.com/watch?v=v2o3MzMAsBY",
	"Mighty Monkey|https://www.youtube.com/watch?v=f2LziS7XYgA",
	"Mighty! Pang|http://youtu.be/goXjMzjcBU4",
	"Mikie|https://youtu.be/J5kmuBP4GYk",
	"Mille Miglia 2: Great 1000 Miles Rally|http://youtu.be/ESdXz1ioN1c",
	"Mirax|https://youtu.be/Gc-Fvrx_iU8",
	"Missile Command|https://youtu.be/nokIGklnBGY",
	"Mobile Suit Gundam|http://youtu.be/KtJSdRSNQOo",
	"Mobile Suit Gundam: EX Revue|http://www.youtube.com/watch?v=QKOXq7Wgp88",
	"Money Idol Exchanger|http://www.youtube.com/watch?v=QizG-EGkizU",
	"Monster Maulers|https://www.youtube.com/watch?v=KTuFWYfn9eg",
	"Moon Cresta|http://www.youtube.com/watch?v=Dl5stQgPGYQ",
	"Moon Patrol|https://www.youtube.com/watch?v=QoH2zNAIcXI",
	"Moon Shuttle|https://youtu.be/6IqAiBYxeLg",
	"Mortal Kombat|http://www.youtube.com/watch?v=6jgrW12Eg_A",
	"MotoRace USA|https://youtu.be/ZMvTmZmvWPY",
	"Mouse Shooter GoGo|http://youtu.be/q8BW9oFl0Bo",
	"Mr. Do|https://youtu.be/5_BBQWed8Vk",
	"Mr. Driller|https://www.youtube.com/watch?v=pt3QawOSoqI",
	"Mr. Goemon|http://www.youtube.com/watch?v=uy3if2RKwK8",
	"Mug Smashers|http://www.youtube.com/watch?v=FbRQMFHQuVU",
	"Multi Champ|https://youtu.be/cUvUChimtYU",
	"Munch Mobile|https://www.youtube.com/watch?v=GoCi7DUsX2M",
	"Muscle Bomber Duo: Ultimate Team Battle|http://www.youtube.com/watch?v=_IrHPOcVFNU",
	"Mustache Boy|https://youtu.be/YV4RLSZ0nQ4",
	"Mutant Fighter|http://youtu.be/zhmRsnWWJWY",
	"Mutant Night|https://youtu.be/ns50vZAtp1w",
	"Mutation Nation|http://www.youtube.com/watch?v=16FdFl3KK0I",
	"MX 5000|http://youtu.be/ivxaKT1uslM",
	"My Hero|https://youtu.be/MxFlq-CfVZ8",
	"Mysterious Stones - Dr. John's Adventure|http://youtu.be/4syCpg4gjn4",
	"Mystic Riders|http://www.youtube.com/watch?v=qUANz79oWTs",
	"Mystic Warriors|http://youtu.be/aKYRJ4PoYM0",
	"NAM-1975|http://www.youtube.com/watch?v=TfvBhYF-6jI",
	"Naname de Magic!|https://youtu.be/9F6iLe2pV7k",
	"Nastar|http://www.youtube.com/watch?v=_XWM_yuPSNo",
	"Nekettsu Kouha Kunio-kun|http://youtu.be/7Sq_K5_xdsU",
	"Nemesis|http://www.youtube.com/watch?v=_sicx5em-V0",
	"Nemo|http://www.youtube.com/watch?v=ZOF0C9jyeWY",
	"Neo Bomberman|http://www.youtube.com/watch?v=It8l3CNXUyg",
	"Neo Drift Out|http://www.youtube.com/watch?v=d50YE00hO98",
	"Neo Geo Cup|http://www.youtube.com/watch?v=miTLcvursxk",
	"Neo Mr Do|http://www.youtube.com/watch?v=l4pmbdAtjYg",
	"Neo Turf Masters:  Big Tournament Golf|http://www.youtube.com/watch?v=WDt9HYniyHs",
	"New Zero Team|https://www.youtube.com/watch?v=w3cAvQ6Vgco",
	"Night Star|https://youtu.be/nEeXnqk-ehs",
	"Night Warriors: DarkStalkers Revenge|https://youtu.be/z441EuNeYnc",
	"Nightmare in the Dark|http://www.youtube.com/watch?v=esTq3L5LR0U",
	"Ninja Baseball Bat Man|http://youtu.be/zxbWyA3L-jE",
	"Ninja Combat|http://www.youtube.com/watch?v=ShfdduWAyJg",
	"Ninja Commando|http://www.youtube.com/watch?v=eoyQdxJgD0I",
	"Ninja Hayate|http://youtu.be/vFH2oUgtRBo",
	"Ninja Masters|http://www.youtube.com/watch?v=4auIUYQD5_E",
	"Ninja Spirit|https://youtu.be/xOCqNAS0TbQ",
	"Nostradamus|http://www.youtube.com/watch?v=1oicnBZSX6M",
	"Numan Athlethics|https://youtu.be/epMg5AEnjRQ",
	"Operation Wolf|http://youtu.be/Ujgy2ziBF8w",
	"Operation Wolf 3|http://www.youtube.com/watch?v=T1Uen25j7lg",
	"Osman|http://www.youtube.com/watch?v=rVMlC8uVjqU",
	"OutRun|http://www.youtube.com/watch?v=J7tZFW4WedI",
	"OutZone|http://www.youtube.com/watch?v=LxexKAhMwIk",
	"OverTop|http://www.youtube.com/watch?v=8fE_PMryMuM",
	"P-47: Aces|https://youtu.be/9aMrhgixRrQ",
	"P-47: The Phantom Fighter|https://youtu.be/YBjkswNGOh8",
	"P.O.W.|http://www.youtube.com/watch?v=9P7l73d19Dc",
	"Pac-Land|https://youtu.be/yvHPE20pPPo",
	"Pang Pom's|https://youtu.be/I_hVx6L9S1k",
	"Panic Bomber|http://www.youtube.com/watch?v=3XHS5n7HuRM",
	"Panic Road|https://youtu.be/yg8pcEtkOjw",
	"Paperboy|https://youtu.be/aCnpP-4pQwo",
	"Parodius Da!|http://www.youtube.com/watch?v=nYgYHffJ6aQ",
	"Perfect Soldier|https://youtu.be/NiZnVSZNdlo",
	"Phoenix|https://youtu.be/OEyOJt-ZjNU",
	"Pinball Action|https://youtu.be/tQlQJzKDbss",
	"Pirate Ship Higemaru|https://youtu.be/R5mg6XPqtBs",
	"Pirate Treasure|https://youtu.be/5B7xHsk1jLY",
	"Pirates|http://www.youtube.com/watch?v=9pZMgRfVa3g",
	"Pleasure Goal / Futsal 5 on 5 Mini Soccer|http://www.youtube.com/watch?v=qcvsKWSfKgE",
	"Plus Alpha|https://www.youtube.com/watch?v=xs8ww9_b8ws",
	"Pochi and Nyaa|http://www.youtube.com/watch?v=f22CCxJ9eko",
	"Pocket Fighter - Super Gem Fighter Mini Mix|http://www.youtube.com/watch?v=ZhCEMkUcpVs",
	"Pole Position|https://www.youtube.com/watch?v=I2HArfckAZk",
	"Pop 'n Bounce|http://www.youtube.com/watch?v=U4FXsVClQpA",
	"Popeye|https://youtu.be/MSSKpeeB23s",
	"Power Instinct|http://www.youtube.com/watch?v=YMJnrGGUiAY",
	"Power Instinct Matrimelee|http://www.youtube.com/watch?v=WR-s4dd7X8Y",
	"Power Spikes|https://www.youtube.com/watch?v=OQTfX5feJSw",
	"Power Spikes II|http://www.youtube.com/watch?v=dYpYqoHqWUM",
	"Prehistoric Isle 2|http://www.youtube.com/watch?v=pCUuVrxNH2A",
	"Prehistoric Isle in 1930|http://www.youtube.com/watch?v=TAF3j-643N8",
	"Pretty Soldier Sailor Moon|http://www.youtube.com/watch?v=EizPltEFypw",
	"Princess Clara Daisakusen|https://youtu.be/3wP1k0p6nW0",
	"Pro Soccer|https://youtu.be/iuydnEnpukk",
	"Progear|http://www.youtube.com/watch?v=LOUxSbUg0Mo",
	"Psychic 5|https://youtu.be/HCtX8-9hHZM",
	"Psycho Soldier|http://www.youtube.com/watch?v=SWbqQnDhsLQ",
	"Psycho-Nics Oscar|http://youtu.be/QcZqkbqe_I8",
	"PuLiRuLa|http://www.youtube.com/watch?v=t3wsFFCncrY",
	"Pulstar|http://www.youtube.com/watch?v=GHkRiKPhito",
	"Punch-Out|http://www.youtube.com/watch?v=1T8hoeVpdV0",
	"Puzzle Bobble|http://www.youtube.com/watch?v=F1I0lzM_UZI",
	"Puzzle Bobble 2|http://www.youtube.com/watch?v=_MMq7yrV6fI",
	"Puzzle de Pon|http://www.youtube.com/watch?v=elldJ5ZZsvU",
	"Puzzle De Pon R|https://youtu.be/PRQmuMbvJb0",
	"Puzzled|http://www.youtube.com/watch?v=-ar3NP0hNOI",
	"Pyros|https://youtu.be/_8fa66RNghw",
	"Quiz & Dragons:  Capcom Quiz Game|http://www.youtube.com/watch?v=eBHIiV2xmaw",
	"Quiz Bishoujo Senshi Sailor Moon: Chiryoku Tairyoku Toki no Un|https://www.youtube.com/watch?v=eOQET7tF_1A",
	"Quiz Crayon Shinchan|https://youtu.be/YJ-0hYaeBsQ",
	"Quiz Daisousasen: The Last Count Down|https://youtu.be/Ldk7C3UU8lw",
	"Quiz Gekiretsu Scramble|https://www.youtube.com/watch?v=P2_iOnVYX_g",
	"Quiz King of Fighters|https://youtu.be/w0PCL2WjBWI",
	"Quiz Meitantei Neo and Geo: Quiz Daisousasen Part 2|https://youtu.be/4zwNAxdA-X4",
	"Quiz Nanairo Dreams: Nijiirochou no Kiseki|https://youtu.be/EWuKBBEj3t4",
	"R-Type|http://www.youtube.com/watch?v=pVWtI0426mU",
	"R-Type II|http://www.youtube.com/watch?v=T2ms0lORGiU",
	"R-Type Leo|https://youtu.be/Xv-II1vnZRU",
	"Rabio Lepus|https://youtu.be/uMaUui6UPkY",
	"Racing Hero|http://www.youtube.com/watch?v=H9CH_nZR99Y",
	"Rad Action|https://youtu.be/e2QCVfzHQqE",
	"Rafflesia|https://youtu.be/nywVINJBaHk",
	"Rage of the Dragons|http://www.youtube.com/watch?v=msZUQkEZKZQ",
	"Ragnagard|http://www.youtube.com/watch?v=9rEcf390X-Y",
	"Raiden|https://www.youtube.com/watch?v=KeajSN7g9ro",
	"Raiden DX|https://www.youtube.com/watch?v=owPQViXnGfo",
	"Raiden II|https://www.youtube.com/watch?v=1oj6zi1ZfNw",
	"Raiga - Strato Fighter|http://www.youtube.com/watch?v=3ahC8OJ4FtI",
	"Rail Chase|http://www.youtube.com/watch?v=GQd3FFT7pnc",
	"Rally Bike|http://www.youtube.com/watch?v=PvhDLk0Hm-8",
	"Rambo III|https://youtu.be/hVdhFP817BQ",
	"Rapid Hero|https://youtu.be/x-ImXABBcIw",
	"Rastan|http://www.youtube.com/watch?v=RfdOIMkXotw",
	"Real Bout Fatal Fury|http://www.youtube.com/watch?v=uxvLQbNznLQ",
	"Real Bout Fatal Fury 2|http://www.youtube.com/watch?v=XqNFCAU3aqc",
	"Real Bout Fatal Fury Special|http://www.youtube.com/watch?v=Q4O6a9RYQ7A",
	"Red Earth - Warzard|http://www.youtube.com/watch?v=Pkwn-iloYNg",
	"Return of the Jedi|http://youtu.be/w9mTDorbaAM",
	"Riding Hero|http://www.youtube.com/watch?v=iwsIuiK7Rjo",
	"Riot City|http://www.youtube.com/watch?v=0jkwp-TZSGw",
	"Robo Army|http://www.youtube.com/watch?v=6f4U5CMLjro",
	"RoboCop|http://www.youtube.com/watch?v=nQutm0TjZfw",
	"Roc' N Rope|https://youtu.be/mWyVRPchwrk",
	"Rolling Thunder|http://youtu.be/ADEF8Uue7_0",
	"Rolling Thunder 2|https://youtu.be/9sHXfIM3axE",
	"Rougien|https://youtu.be/MeWuFbRt_Sg",
	"Rygar|http://www.youtube.com/watch?v=FK_OQIgIPqw",
	"Ryu Jin|http://www.youtube.com/watch?v=0D3LUcKFlyw",
	"Saboten Bombers|https://youtu.be/nrga5m-h8_c",
	"Sagaia|https://www.youtube.com/watch?v=FdsX891l_vo",
	"Sakura Taisen: Hanagumi Taisen Columns|http://youtu.be/G1ReC1yRZ34",
	"Salamander 2|https://youtu.be/NKvcvA5VeV8",
	"Samurai Aces|http://www.youtube.com/watch?v=lJsJsdZ6hi0",
	"Samurai Shodown|http://www.youtube.com/watch?v=zWmOMwJB8xQ",
	"Samurai Shodown II|http://www.youtube.com/watch?v=pJdfRC0fnEc",
	"Samurai Shodown III|http://www.youtube.com/watch?v=in6ojxEZH1I",
	"Samurai Shodown IV - Amakusas Revenge|http://www.youtube.com/watch?v=KxtpJEvTBv4",
	"Samurai Shodown V|http://www.youtube.com/watch?v=P8Oeqpqlx9w",
	"Satan of Saturn|https://youtu.be/2-UKpuWY6kU",
	"Savage Reign|http://www.youtube.com/watch?v=QPng_eh_864",
	"Scramble|http://www.youtube.com/watch?v=zRlRcIsIKkY",
	"SD Gundam Neo Battling|https://youtu.be/iXJha6E0PBU",
	"SD-Fighters|http://www.youtube.com/watch?v=jPXZeD_-dMk",
	"SEGA Rally Championship 1995|http://www.youtube.com/watch?v=6REoftI1lbQ",
	"Sengoku|http://www.youtube.com/watch?v=SLLKQLYHQWw",
	"Sengoku 2|http://www.youtube.com/watch?v=NReHy05g26g",
	"Sengoku 3|http://www.youtube.com/watch?v=17F_NMw_tXo",
	"Sexy Parodius|http://www.youtube.com/watch?v=qf8MRUgyAtE",
	"Shadow Dancer|http://www.youtube.com/watch?v=1rzGgSGZX0c",
	"Shadow Force|http://www.youtube.com/watch?v=bykZ0qK29mY",
	"Shadow Warriors|http://www.youtube.com/watch?v=SfTy8f4FazM",
	"Shinobi|http://www.youtube.com/watch?v=IiVhLpQtQcI",
	"Shock Troopers|http://www.youtube.com/watch?v=RuFGB_h1_3Q",
	"Shock Troopers 2nd Squad|http://www.youtube.com/watch?v=4DF5ZFsX1MY",
	"Silent Dragon|http://www.youtube.com/watch?v=wqVU4J2SAwU",
	"SilkWorm|http://www.youtube.com/watch?v=y-Eq361-xWE",
	"Sindbad Mystery|https://youtu.be/zg_5L6exU8U",
	"Sinistar|https://youtu.be/U8S5VSwcNag",
	"Slap Fight|http://www.youtube.com/watch?v=aVTaphXj_Ps",
	"Sly Spy|http://www.youtube.com/watch?v=OIBPrDVM6xk",
	"SNK vs Capcom: SvC Chaos|http://www.youtube.com/watch?v=bQnd4Cw4oMU",
	"Snow Bros. 2:  With New Elves|http://www.youtube.com/watch?v=UHxyHy8YqxI",
	"Snow Bros.:  Nick & Tom|http://www.youtube.com/watch?v=aZbW52_j-ws",
	"Soccer Brawl|http://www.youtube.com/watch?v=2_k2dnstm6w",
	"Solar Assault|http://youtu.be/Dn6wBN3qmNwArcade",
	"Soldier Girl Amazon|https://www.youtube.com/watch?v=bh0u34wZoGo",
	"Sonic Boom|http://www.youtube.com/watch?v=Q7IuVZiRmvI",
	"Sonic the Fighters|http://youtu.be/DR8PwP4Oq1o",
	"SonSon|https://youtu.be/yDpAaNVXZ9U",
	"Sorcer Striker|http://youtu.be/r-BdDAty_0k",
	"SOS|http://www.youtube.com/watch?v=6hKLat4W3Ls",
	"Soul Edge|http://youtu.be/bYgoJfD0Idk",
	"Space Bomber|http://www.youtube.com/watch?v=h3bQWFnj5VQ",
	"Space Gun|http://www.youtube.com/watch?v=Br_meKpLUfY",
	"Speed Coin|https://youtu.be/Ji2nP7YGVp8",
	"Spider-Man: The Videogame|https://youtu.be/Xypy3CAjHcI",
	"Spinal Breakers|http://www.youtube.com/watch?v=dMAZbfpcqgE",
	"SpinMaster|http://www.youtube.com/watch?v=VVK7dZGYgfA",
	"Stakes Winner 2|http://www.youtube.com/watch?v=Acd2QX8DSzw",
	"Stakes Winner:  GI Kinzen Seihae No Michi|http://www.youtube.com/watch?v=fa9LWD7MxuE",
	"Street Fighter Alpha|http://www.youtube.com/watch?v=R_aeNaJCc2g",
	"Street Fighter Alpha 2|http://www.youtube.com/watch?v=cFZLsfhw4m0",
	"Street Fighter Alpha 3|http://www.youtube.com/watch?v=xJwwVeQuZ6I",
	"Street Fighter II: Champion Edition|http://www.youtube.com/watch?v=KJne-82X4L0",
	"Street Fighter II: The World Warrior|http://www.youtube.com/watch?v=xI284D4y1q4",
	"Street Fighter III 2nd Impact: Giant Attack|http://www.youtube.com/watch?v=yOZuaz2Lnbc",
	"Street Fighter III 3rd Strike: Fight for the Future|http://www.youtube.com/watch?v=Vz4d2Gl3NbM",
	"Street Fighter III: New Generation|http://www.youtube.com/watch?v=DaQOlBlEb0o",
	"Street Hoop|http://www.youtube.com/watch?v=JLLyd7ZQuoo",
	"Strider|http://www.youtube.com/watch?v=FZwzRRHn53k",
	"Strike Gunner S.T.G|http://www.youtube.com/watch?v=SQY9p4KZT4Q",
	"Strikers 1945 Plus|http://www.youtube.com/watch?v=Zv-sd9C4ne8",
	"Subroc -3D|https://youtu.be/W06ODkUHjhg",
	"Sunset Riders|http://www.youtube.com/watch?v=yP2ba-QYQY8",
	"Super Cobra|http://www.youtube.com/watch?v=Y6FK9jNBURY",
	"Super Contra|http://www.youtube.com/watch?v=4UB-1-cWR0o",
	"Super Dodge Ball: Kunio no Nekketsu Toukyuu Densetsu|http://www.youtube.com/watch?v=Np7-xrlYhLg",
	"Super Double Tennis|https://youtu.be/gnRRdV45t3Y",
	"Super Punch-Out|https://youtu.be/NkCICvuJh8E",
	"Super Puzzle Fighter II Turbo|http://www.youtube.com/watch?v=zVIY0vbdHQ0",
	"Super Ranger|https://youtu.be/Ip6MfSM8_2U",
	"Super Sidekicks|https://www.youtube.com/watch?v=OrP_V6lrSDI",
	"Super Sidekicks 2:  The World Championship|http://www.youtube.com/watch?v=4-piSx2a1zQ",
	"Super Sidekicks 3:  The Next Glory|http://www.youtube.com/watch?v=sBUa5xJrlyo",
	"Superman|http://www.youtube.com/watch?v=H0l6f3bmiGU",
	"Surprise Attack|https://youtu.be/4bc-5LuehxI",
	"Survival|https://youtu.be/_xT9yaGTIc4",
	"SWAT Police|http://www.youtube.com/watch?v=0F95wN91lcc",
	"Swimmer|https://youtu.be/5DFaQZvNegU",
	"Talbot|https://youtu.be/ICeHbR5k7Aw",
	"Tao Taido|http://www.youtube.com/watch?v=VFrD0IuIrk8",
	"Task Force Harrier|https://www.youtube.com/watch?v=4wy5VKpL7AY",
	"Tatakae Genshijin Joe & Mac|http://youtu.be/JhLT0g_ZDO8",
	"Tecmo World Soccer '96|http://www.youtube.com/watch?v=Nf2KPfuNxCs",
	"Teenage Mutant Ninja Turtles|http://youtu.be/QyRIxVEpi3o",
	"Tekken|https://youtu.be/shjn6ldFf_Y",
	"Tekken 2|https://youtu.be/O3uUpSya7pM",
	"Tekken 3|https://youtu.be/IQbkNc11SkQ",
	"Tekken Tag Tournament|https://youtu.be/4VEJwtGrRYo",
	"Tetris|https://youtu.be/gTeaC1GpsOk",
	"The Age of Heroes|https://youtu.be/LNRur1t3JOw",
	"The Alphax Z|https://youtu.be/LS7s2KFtOTk",
	"The Astyanax|http://youtu.be/lGWAhXM8Obw",
	"The Battle Road|https://youtu.be/Cmh8ElenmJk",
	"The Berlin Wall|https://youtu.be/kCwGzNieTwc",
	"The Cliffhanger: Edward Randy|http://youtu.be/m2A-1hAsLls",
	"The Combatribes|http://www.youtube.com/watch?v=JG0tVG9SltA",
	"The Fairyland Story|https://youtu.be/jLiIU6m4L4o",
	"The Game Paradise: Master Of Shooting|https://youtu.be/wFogf-DDUX8",
	"The Guiness|https://youtu.be/7O-2NvU1yR0",
	"The Karate Tournament|http://youtu.be/4iUg62Nneus",
	"The Killing Blade|https://www.youtube.com/watch?v=IdicFebgAvI",
	"The King of Dragons|http://www.youtube.com/watch?v=IsM3_h1xav0",
	"The King of Fighters '94|http://www.youtube.com/watch?v=g4G0dX-w8QI",
	"The King of Fighters '95|http://www.youtube.com/watch?v=greALx7jn4U",
	"The King of Fighters '96|http://www.youtube.com/watch?v=yuR-XEzUHAA",
	"The King of Fighters '97|http://www.youtube.com/watch?v=H5lc6Lle2lc",
	"The King of Fighters '98|http://www.youtube.com/watch?v=ziyqWaKqb1Y",
	"The King of Fighters '99|http://www.youtube.com/watch?v=DuAg9ILvzUo",
	"The King of Fighters 2000|http://www.youtube.com/watch?v=xrQLRCwM1Ds",
	"The King of Fighters 2001|http://www.youtube.com/watch?v=-2TcH2ismsY",
	"The King of Fighters 2002|http://www.youtube.com/watch?v=YNfD5ndPSjs",
	"The King of Fighters 2003|http://www.youtube.com/watch?v=IFHvDdUAnzI",
	"The Last Day|https://youtu.be/KCkXt7UyR58",
	"The Legend of Kage|https://youtu.be/hHExwVWvhVw",
	"The Lost Castle in Dark Mist|https://youtu.be/wJBm4bg9r8Y",
	"The Main Event|http://www.youtube.com/watch?v=2CNpVCP7m04",
	"The Ninja Warriors|https://youtu.be/DJ7-4ldPqdA",
	"The Pit|https://youtu.be/1_YHTew6CzQ",
	"The Punisher|http://www.youtube.com/watch?v=BMmI1Ez9ajo",
	"The Real Ghostbusters|https://youtu.be/doytXjzzwLM",
	"The Simpsons Arcade Game|http://www.youtube.com/watch?v=S9DE-KyZnLc",
	"The Super Spy|http://www.youtube.com/watch?v=5bFFkNmhN_w",
	"The Ultimate 11|http://www.youtube.com/watch?v=eqW5SkPLh0M",
	"Thrash Rally|http://www.youtube.com/watch?v=KjMP7PxKixA",
	"Three Wonders|http://www.youtube.com/watch?v=uxClDHEPjGI",
	"Thunder Force AC|https://youtu.be/nMeNx-UAe0U",
	"Thunder Fox|http://www.youtube.com/watch?v=DeqQlOUKFzM",
	"Tiger Heli|http://www.youtube.com/watch?v=fL4X-sbLvr8",
	"Time Gal|http://youtu.be/j5nLn2LLvAY",
	"Time Soldiers|https://youtu.be/C9omf1-iO7M",
	"Toki|https://www.youtube.com/watch?v=tKtqKq3137U",
	"Top Hunter|http://www.youtube.com/watch?v=zNM63ypeoxk",
	"Tower of Druaga|https://youtu.be/LdNGOARBDJ0",
	"Traverse USA|http://www.youtube.com/watch?v=st2sK7nz4UU",
	"Treasure Island|https://youtu.be/oR6XcstEHxo",
	"Treasure of the Caribbean|http://www.youtube.com/watch?v=VbI89A8AEJE",
	"Trigon|http://www.youtube.com/watch?v=-CQUfrrK3A4",
	"Trio the Punch - Never Forget Me|http://www.youtube.com/watch?v=rIPtzZHJnkg",
	"Trojan|http://www.youtube.com/watch?v=L1FVWdlQNG8",
	"Truxton|http://www.youtube.com/watch?v=9_fX0yXVDh0",
	"Tumble Pop|https://www.youtube.com/watch?v=ge9qA5oqbBE",
	"Turbo Out Run|http://www.youtube.com/watch?v=azdofC423Oo",
	"Turtle Ship|https://www.youtube.com/watch?v=IwmegLjw7M0",
	"Twin Cobra II|http://youtu.be/Lhm7DC9sEps",
	"Twinkle Star Sprites|http://www.youtube.com/watch?v=zEhFh_-DVD8",
	"U.N. Defense Force: Earth Joker|http://youtu.be/E-bFa-vofNs",
	"U.N. Squadron|http://www.youtube.com/watch?v=4TB62ZPYGLU",
	"UFO Robo Dangar|https://youtu.be/2K1jhKY0vPU",
	"UFO Senshi Yohko Chan|https://www.youtube.com/watch?v=3o9Ly3RjofY",
	"Ultimate Tennis|https://www.youtube.com/watch?v=jQEuaB8C9Gw",
	"USAAF Mustang|https://www.youtube.com/watch?v=BSgJT3FrVmA",
	"Vampire Hunter 2: DarkStalkers Revenge|https://youtu.be/bevWXe8oG5M",
	"Vampire Savior 2: The Lord of Vampire|https://youtu.be/yRfFtIAtfHU",
	"Vampire Savior: The Lord of Vampire|https://youtu.be/H7Y4quP8ii0",
	"Vapor Trail: Hyper Offense Formation|https://youtu.be/G2vwlmGvz90",
	"ViewPoint|http://www.youtube.com/watch?v=IPBQ2NhSO9M",
	"Vigilante|http://www.youtube.com/watch?v=9Ue1JnXheWo",
	"Violent Storm|http://www.youtube.com/watch?v=zGl4iJUnw_w",
	"Viper Phase 1|https://www.youtube.com/watch?v=nOdzI1WDUA8",
	"Virtua Fighter 2|http://www.youtube.com/watch?v=F7OYlmdhOZY",
	"Voltage Fighter Gowcaizer|http://www.youtube.com/watch?v=t8SvI-2nq-Q",
	"VS. Super Mario Bros|http://youtu.be/OvfBUntkYcg",
	"Waku Waku 7|http://www.youtube.com/watch?v=DefAwU3GcEI",
	"War Gods|http://www.youtube.com/watch?v=stYMjSOxk70",
	"Warrior Blade: Rastan Saga Episode III|https://www.youtube.com/watch?v=X11yiwgrnfU",
	"Warriors of Fate|http://www.youtube.com/watch?v=iNo7UhzwZs4",
	"Wild Western|https://youtu.be/1u1f93qzAY8",
	"Willow|http://www.youtube.com/watch?v=LumZP0rpoDM",
	"Wily Tower|https://youtu.be/gn33LPp8pvM",
	"WindJammers|http://www.youtube.com/watch?v=Eg93nPgR6rw",
	"Wing Force (Prototype)|https://youtu.be/A7NO2842oLY",
	"Wonder Boy|http://www.youtube.com/watch?v=Bvim7O9RvK0",
	"Wonder Boy III:  Monster Lair|http://www.youtube.com/watch?v=2CTB6Eg2ssw",
	"World Cup 90|http://www.youtube.com/watch?v=yoZZxmJRmfE",
	"World Heroes|http://www.youtube.com/watch?v=QDYhvy7uCCo",
	"World Heroes 2|http://www.youtube.com/watch?v=iVBHgr6TH2w",
	"World Heroes 2 Jet|http://www.youtube.com/watch?v=1jOGp4Gtt3w",
	"World Heroes Perfect|http://www.youtube.com/watch?v=snP1uLk0s_8",
	"WWF Superstars|http://www.youtube.com/watch?v=hTnZZsY3Jgg",
	"WWF Wrestlefest|http://youtu.be/-2ak_BjxKZo",
	"X-Men VS Street Fighter|https://youtu.be/XrFB2N1aBbs",
	"X-Men: Children Of The Atom|https://youtu.be/6rmyvfXayME",
	"Yakyuu Kakutou League-Man|https://youtu.be/TjAn6xWzQVs",
	"Youjyuden|https://youtu.be/-hGNlvt8zZU",
	"Yukiwo (Prototype)|https://www.youtube.com/watch?v=or8dBxlkbXs",
	"Zaviga|https://www.youtube.com/watch?v=cE8618OTAqY",
	"ZedBlade|http://www.youtube.com/watch?v=E_YAKJSFvR4",
	"Zero Team|https://youtu.be/gHcxkbnh-ZQ",
	"Zero Team 2000|https://www.youtube.com/watch?v=zhM3a1rghfU",
	"Zero Team U.S.A.|https://www.youtube.com/watch?v=vM6trJfz1b4",
	"Zero Wing|http://www.youtube.com/watch?v=WIT3OvfDlyk",
	"Zeroize|https://youtu.be/oe9n9eqm-2g",
	"Zing Zing Zip|http://www.youtube.com/watch?v=Kw7Cq8CHBM8",
	"Zintrick|http://www.youtube.com/watch?v=lawxVuJi9VY",
	"Zoar|https://youtu.be/YjZ3ZSbI39g",
	"Zodiack|https://youtu.be/WATQPKvYG4s",
	"Zupapa|https://youtu.be/a2diSxAds2Q",
}
