package main

func generateMisterGameGearGames(generate bool) {
	gamegearTitleAdded := make(map[string]bool)
	gamegearImages := make(map[string]string)
	gamegearGameList := []string{}
	compileMisterConsoleData(gamegearTitleAdded, &gamegearGameList, gamegearImages, gamegearVideos, "gamegear")
	// gamegearVideoReport(&gamegearGameList)
	if generate {
		generateMisterConsoleHTML("Game Gear", &gamegearGameList, gamegearImages, gamegearVideos, "gamegear", "game gear")
	}
}

var gamegearVideos = map[string]string{}

var gamegearGameInfo = map[string]string{
	"5 in One Fun Pak":                           "https://www.smspower.org/Games/5InOneFunPak-GG",
	"Aerial Assault":                             "https://www.smspower.org/Games/AerialAssault-GG",
	"Aladdin":                                    "https://www.smspower.org/Games/Aladdin-GG",
	"Alien 3":                                    "https://www.smspower.org/Games/Alien3-GG",
	"Alien Syndrome":                             "https://www.smspower.org/Games/AlienSyndrome-GG",
	"Andre Agassi Tennis":                        "https://www.smspower.org/Games/AndreAgassiTennis-GG",
	"Arcade Classics":                            "https://www.smspower.org/Games/ArcadeClassics-GG",
	"Arena - Maze of Death":                      "https://www.smspower.org/Games/ArenaMazeOfDeath-GG",
	"Ariel - The Little Mermaid":                 "https://www.smspower.org/Games/ArielTheLittleMermaid-GG",
	"Asterix and the Great Rescue":               "https://www.smspower.org/Games/AsterixAndTheGreatRescue-GG",
	"Asterix and the Secret Mission":             "https://www.smspower.org/Games/AsterixAndTheSecretMission-GG",
	"Ax Battler - A Legend of Golden Axe":        "https://www.smspower.org/Games/AxBattler-GG",
	"Baku Baku":                                  "https://www.smspower.org/Games/BakuBakuAnimal-GG",
	"Barbie Super Model":                         "https://www.smspower.org/Games/BarbieSuperModel-GG",
	"Bart vs. The World":                         "https://www.smspower.org/Games/BartVsTheWorld-GG",
	"Batter Up":                                  "https://www.smspower.org/Games/BatterUp-GG",
	"Battletoads":                                "https://www.smspower.org/Games/Battletoads-GG",
	"Berlin no Kabe - The BerlinWall":            "https://www.smspower.org/Games/BerlinNoKabe-GG",
	"Bonkers Wax Up!":                            "https://www.smspower.org/Games/BonkersWaxUp-GG",
	"BreakThru!":                                 "https://www.smspower.org/Games/BreakThru-GG",
	"Bubble Bobble":                              "https://www.smspower.org/Games/BubbleBobble-GG",
	"Bugs Bunny in Double Trouble":               "https://www.smspower.org/Games/BugsBunnyInDoubleTrouble-GG",
	"Buster Fight":                               "https://www.smspower.org/Games/BusterFight-GG",
	"Car Licence":                                "https://www.smspower.org/Games/CarLicence-GG",
	"Castle of Illusion - Starring Mickey Mouse": "https://www.smspower.org/Games/CastleOfIllusion-GG",
	"Cave Dude":                                  "https://www.smspower.org/Games/CaveDude-GG",
	"Championship Hockey":                        "https://www.smspower.org/Games/ChampionshipHockey-GG",
	"Chase H.Q.":                                 "https://www.smspower.org/Games/ChaseHQ-GG",
	"Cheese Cat-Astrophe":                        "https://www.smspower.org/Games/CheeseCatastrophe-GG",
	"The Chessmaster":                            "https://www.smspower.org/Games/Chessmaster-GG",
	"Chicago Syndicate":                          "https://www.smspower.org/Games/ChicagoSyndicate-GG",
	"Chuck Rock":                                 "https://www.smspower.org/Games/ChuckRock-GG",
	"Chuck Rock II Son of Chuck":                 "https://www.smspower.org/Games/ChuckRockII-GG",
	"CJ Elephant Fugitive":                       "https://www.smspower.org/Games/CJElephantFugitive-GG",
	"Cliffhanger":                                "https://www.smspower.org/Games/Cliffhanger-GG",
	"Clutch Hitter":                              "https://www.smspower.org/Games/ClutchHitter-GG",
	"Columns":                                    "https://www.smspower.org/Games/Columns-GG",
	"Cool Spot":                                  "https://www.smspower.org/Games/CoolSpot-GG",
	"Cosmic Spacehead":                           "https://www.smspower.org/Games/CosmicSpacehead-GG",
	"Crazy Faces":                                "https://www.smspower.org/Games/CrazyFaces-GG",
	"Crystal Warriors":                           "https://www.smspower.org/Games/CrystalWarriors-GG",
	"Cutthroat Island":                           "https://www.smspower.org/Games/CutthroatIsland-GG",
	"Daffy Duck in Hollywood":                    "https://www.smspower.org/Games/DaffyDuckInHollywood-GG",
	"David Robinson's Supreme Court":             "https://www.smspower.org/Games/DavidRobinsonSupremeCourt-GG",
	"Deep Duck Trouble":                          "https://www.smspower.org/Games/DeepDuckTrouble-GG",
	"Defenders of Oasis":                         "https://www.smspower.org/Games/DefendersOfOasis-GG",
	"Desert Strike - Return to the Gulf":         "https://www.smspower.org/Games/DesertStrike-GG",
	"Devilish":                                   "https://www.smspower.org/Games/Devilish-GG",
	"Dinobasher - Starring Bignose the Caveman":  "https://www.smspower.org/Games/Dinobasher-GG",
	"Doraemon Waku Waku Pocket Paradise":         "https://www.smspower.org/Games/DoraemonWakuWakuPocketParadise-GG",
	"Double Dragon":                              "https://www.smspower.org/Games/DoubleDragon-GG",
	"Dracula":                                    "https://www.smspower.org/Games/Dracula-GG",
	"Dragon The Bruce Lee Story":                 "https://www.smspower.org/Games/Dragon-GG",
	"Dr. Franken":                                "https://www.smspower.org/Games/DrFranken-GG",
	"Dropzone":                                   "https://www.smspower.org/Games/Dropzone-GG",
	"Dynamite Headdy":                            "https://www.smspower.org/Games/DynamiteHeaddy-GG",
	"Earthworm Jim":                              "https://www.smspower.org/Games/EarthwormJim-GG",
	"Ecco the Dolphin":                           "https://www.smspower.org/Games/EccoTheDolphin-GG",
	"Ecco - The Tides of Time":                   "https://www.smspower.org/Games/EccoTheTidesOfTime-GG",
	"Ernie Els Golf":                             "https://www.smspower.org/Games/ErnieElsGolf-GG",
	"Eternal Legend":                             "https://www.smspower.org/Games/EternalLegend-GG",
	"F1":                                         "https://www.smspower.org/Games/F1-GG",
	"F-15 Strike Eagle":                          "https://www.smspower.org/Games/F15StrikeEagle-GG",
	"F1 - World Championship Edition":            "https://www.smspower.org/Games/F1WorldChampionshipEdition-GG",
	"Face Ball 2000":                             "https://www.smspower.org/Games/FaceBall2000-GG",
	"Factory Panic":                              "https://www.smspower.org/Games/FactoryPanic-GG",
	"Fatal Fury Special":                         "https://www.smspower.org/Games/FatalFurySpecial-GG",
	"FIFA International Soccer":                  "https://www.smspower.org/Games/FIFAInternationalSoccer-GG",
	"FIFA Soccer 96":                             "https://www.smspower.org/Games/FIFASoccer96-GG",
	"Foreman for Real":                           "https://www.smspower.org/Games/ForemanForReal-GG",
	"Fray -Shugyou hen-":                         "https://www.smspower.org/Games/Fray-GG",
	"Fred Couples Golf":                          "https://www.smspower.org/Games/FredCouplesGolf-GG",
	"Frogger":                                    "https://www.smspower.org/Games/Frogger-GG",
	"Galaga '91":                                 "https://www.smspower.org/Games/Galaga91-GG",
	"Gamble Panic":                               "https://www.smspower.org/Games/GamblePanic-GG",
	"Garfield Caught in the Act":                 "https://www.smspower.org/Games/GarfieldCaughtInTheAct-GG",
	"Gear Stadium Heiseiban":                     "https://www.smspower.org/Games/GearStadiumHeiseiban-GG",
	"GG Portrait - Pai Chen":                     "https://www.smspower.org/Games/GGPortraitPaiChen-GG",
	"GG Portrait - Yuuki Akira":                  "https://www.smspower.org/Games/GGPortraitYuukiAkira-GG",
	"The GG Shinobi":                             "https://www.smspower.org/Games/GGShinobi-GG",
	"G-LOC - Air Battle":                         "https://www.smspower.org/Games/GLOCAirBattle-GG",
	"Godzilla - Kaijuu Daishingeki":              "https://www.smspower.org/Games/Godzilla-GG",
	"GP Rider":                                   "https://www.smspower.org/Games/GPRider-GG",
	"Greendog - The Beached Surfer Dude!":        "https://www.smspower.org/Games/Greendog-GG",
	"Halley Wars":                                "https://www.smspower.org/Games/HalleyWars-GG",
	"Heavy weight Champ":                         "https://www.smspower.org/Games/HeavyweightChamp-GG",
	"Home Alone":                                 "https://www.smspower.org/Games/HomeAlone-GG",
	"House of Tarot":                             "https://www.smspower.org/Games/HouseOfTarot-GG",
	"Hurricanes":                                 "https://www.smspower.org/Games/Hurricanes-GG",
	"Hyper Pro Yakyuu '92":                       "https://www.smspower.org/Games/HyperProYakyuu92-GG",
	"Ichidant-R GG":                              "https://www.smspower.org/Games/IchidantRGG-GG",
	"Indiana Jones and the Last Crusade The Action Game": "https://www.smspower.org/Games/IndianaJonesAndTheLastCrusade-GG",
	"The Itchy & Scratchy Game":                          "https://www.smspower.org/Games/ItchyAndScratchyGame-GG",
	"James Bond 007 The Duel":                            "https://www.smspower.org/Games/JamesBond007TheDuel-GG",
	"James Pond 3 - Operation Starfi5h":                  "https://www.smspower.org/Games/JamesPond3-GG",
	"James Pond II - Codename RoboCod":                   "https://www.smspower.org/Games/JamesPondII-GG",
	"Jang Pung II":                                       "https://www.smspower.org/Games/JangPungII-GG",
	"Jeopardy!":                                          "https://www.smspower.org/Games/Jeopardy-GG",
	"Jeopardy! Sports Edition":                           "https://www.smspower.org/Games/JeopardySportsEdition-GG",
	"J League GG Pro Striker '94":                        "https://www.smspower.org/Games/JLeagueGGProStriker94-GG",
	"J League Soccer Dream Eleven":                       "https://www.smspower.org/Games/JLeagueSoccerDreamEleven-GG",
	"Joe Montana Football":                               "https://www.smspower.org/Games/JoeMontanaFootball-GG",
	"Junction":                                           "https://www.smspower.org/Games/Junction-GG",
	"The Jungle Book":                                    "https://www.smspower.org/Games/JungleBook-GG",
	"Jungle Strike":                                      "https://www.smspower.org/Games/JungleStrike-GG",
	"Jurassic Park":                                      "https://www.smspower.org/Games/JurassicPark-GG",
	"Kawasaki Superbike Challenge":                       "https://www.smspower.org/Games/KawasakiSuperbikeChallenge-GG",
	"Kishin Douji Zenki":                                 "https://www.smspower.org/Games/KishinDoujiZenki-GG",
	"KLAX":                                               "https://www.smspower.org/Games/KLAX-GG",
	"Land of Illusion - Starring Mickey Mouse":           "https://www.smspower.org/Games/LandOfIllusion-GG",
	"Last Action Hero":                                   "https://www.smspower.org/Games/LastActionHero-GG",
	"Lemmings":                                           "https://www.smspower.org/Games/Lemmings-GG",
	"Lemmings 2 The Tribes":                              "https://www.smspower.org/Games/Lemmings2-GG",
	"The Lion King":                                      "https://www.smspower.org/Games/LionKing-GG",
	"The Lost World Jurassic Park":                       "https://www.smspower.org/Games/LostWorld-GG",
	"The Lucky Dime Caper - Starring Donald Duck":        "https://www.smspower.org/Games/LuckyDimeCaper-GG",
	"Madden 96":                                          "https://www.smspower.org/Games/Madden96-GG",
	"Madoh Monogatari II - Aruru 16-sai":                 "https://www.smspower.org/Games/MadohMonogatariII-GG",
	"Madoh Monogatari III - Kyuukyoku Joou-sama":         "https://www.smspower.org/Games/MadohMonogatariIII-GG",
	"Man Overboard!":                                     "https://www.smspower.org/Games/ManOverboard-GG",
	"Marble Madness":                                     "https://www.smspower.org/Games/MarbleMadness-GG",
	"Marko's Magic Football":                             "https://www.smspower.org/Games/MarkosMagicFootball-GG",
	"Micro Machines":                                     "https://www.smspower.org/Games/MicroMachines-GG",
	"Micro Machines 2 Turbo Tournament":                  "https://www.smspower.org/Games/MicroMachines2-GG",
	"Mighty Morphin Power Rangers":                       "https://www.smspower.org/Games/MightyMorphinPowerRangers-GG",
	"Moldorian -Hikari to Yami no Shisutaa-":             "https://www.smspower.org/Games/Moldorian-GG",
	"Monster Truck Wars":                                 "https://www.smspower.org/Games/MonsterTruckWars-GG",
	"Mortal Kombat":                                      "https://www.smspower.org/Games/MortalKombat-GG",
	"Mortal Kombat 3":                                    "https://www.smspower.org/Games/MortalKombat3-GG",
	"Mortal Kombat II":                                   "https://www.smspower.org/Games/MortalKombatII-GG",
	"Ms. Pac-Man":                                        "https://www.smspower.org/Games/MsPacMan-GG",
	"Nazo Puyo":                                          "https://www.smspower.org/Games/NazoPuyo-GG",
	"Nazo Puyo 2":                                        "https://www.smspower.org/Games/NazoPuyo2-GG",
	"Nazo Puyo Aruru no Ruu":                             "https://www.smspower.org/Games/NazoPuyoAruruNoRuu-GG",
	"NBA Action - Starring David Robinson":               "https://www.smspower.org/Games/NBAAction-GG",
	"NBA Jam":                                            "https://www.smspower.org/Games/NBAJam-GG",
	"NBA Jam T.E.":                                       "https://www.smspower.org/Games/NBAJamTE-GG",
	"Neko Dai Suki!":                                     "https://www.smspower.org/Games/NekoDaiSuki-GG",
	"NFL '95":                                            "https://www.smspower.org/Games/NFL95-GG",
	"NHL Hockey":                                         "https://www.smspower.org/Games/NHLHockey-GG",
	"Ninja Gaiden":                                       "https://www.smspower.org/Games/NinjaGaiden-GG",
	"Ninkuu":                                             "https://www.smspower.org/Games/Ninkuu-GG",
	"Ninkuu 2 -Tenkuuryuu-e no Michi-":                   "https://www.smspower.org/Games/Ninkuu2-GG",
	"Ninkuu Gaiden - Hiroyuki Daikatsugeki":              "https://www.smspower.org/Games/NinkuuGaiden-GG",
	"Nomo Hideo no World Series Baseball":                "https://www.smspower.org/Games/NomosWorldSeriesBaseball-GG",
	"Off the Wall":                                       "https://www.smspower.org/Games/OffTheWall-GG",
	"Olympic Gold":                                       "https://www.smspower.org/Games/OlympicGold-GG",
	"Out Run":                                            "https://www.smspower.org/Games/OutRun-GG",
	"Out Run Europa":                                     "https://www.smspower.org/Games/OutRunEuropa-GG",
	"Pac-Attack":                                         "https://www.smspower.org/Games/PacAttack-GG",
	"Pac-In-Time":                                        "https://www.smspower.org/Games/PacInTime-GG",
	"Pac-Man":                                            "https://www.smspower.org/Games/PacMan-GG",
	"Panzer Dragoon Mini":                                "https://www.smspower.org/Games/PanzerDragoonMini-GG",
	"Paperboy 2":                                         "https://www.smspower.org/Games/Paperboy2-GG",
	"Pengo":                                              "https://www.smspower.org/Games/Pengo-GG",
	"Pet Club Inu Dai Suki!":                             "https://www.smspower.org/Games/PetClubInuDaiSuki-GG",
	"Pete Sampras Tennis":                                "https://www.smspower.org/Games/PeteSamprasTennis-GG",
	"PGA TOUR 96":                                        "https://www.smspower.org/Games/PGATour96-GG",
	"Pinball Dreams":                                     "https://www.smspower.org/Games/PinballDreams-GG",
	"Poker Face Paul's Gin":                              "https://www.smspower.org/Games/PokerFacePaulsGin-GG",
	"Poker Face Paul's Poker":                            "https://www.smspower.org/Games/PokerFacePaulsPoker-GG",
	"Poker Face Paul's Solitaire":                        "https://www.smspower.org/Games/PokerFacePaulsSolitaire-GG",
	"Popeye Beach Volley Ball":                           "https://www.smspower.org/Games/PopeyeBeachVolleyBall-GG",
	"Power Drive":                                        "https://www.smspower.org/Games/PowerDrive-GG",
	"Primal Rage":                                        "https://www.smspower.org/Games/PrimalRage-GG",
	"Pro Yakyuu GG League":                               "https://www.smspower.org/Games/ProYakyuuGGLeague-GG",
	"Putt & Putter":                                      "https://www.smspower.org/Games/PuttAndPutter-GG",
	"Puyo Puyo 2":                                        "https://www.smspower.org/Games/PuyoPuyo2-GG",
	"Puzzle Bobble":                                      "https://www.smspower.org/Games/PuzzleBobble-GG",
	"Quest for the Shaven Yak Starring Ren Hoëk & Stimpy": "https://www.smspower.org/Games/QuestForTheShavenYak-GG",
	"Rastan Saga":              "https://www.smspower.org/Games/RastanSaga-GG",
	"R.B.I. Baseball '94":      "https://www.smspower.org/Games/RBIBaseball94-GG",
	"Rise of the Robots":       "https://www.smspower.org/Games/RiseOfTheRobots-GG",
	"Ristar the Shooting Star": "https://www.smspower.org/Games/RistarTheShootingStar-GG",
	"Road Rash":                "https://www.smspower.org/Games/RoadRash-GG",
	"Samurai Shodown":          "https://www.smspower.org/Games/SamuraiShodown-GG",
	"Scratch Golf":             "https://www.smspower.org/Games/ScratchGolf-GG",
	"Sega Game Pack 4 in 1":    "https://www.smspower.org/Games/SegaGamePack4In1-GG",
	"Sensible Soccer":          "https://www.smspower.org/Games/SensibleSoccer-GG",
	"Shanghai II":              "https://www.smspower.org/Games/ShanghaiII-GG",
	"Shaq Fu":                  "https://www.smspower.org/Games/ShaqFu-GG",
	"Shining Force Gaiden -Ensei Jashin no Kuni e-": "https://www.smspower.org/Games/ShiningForceGaiden-GG",
	"Shining Force Gaiden II -Jashin no Mezame-":    "https://www.smspower.org/Games/ShiningForceGaidenII-GG",
	"Side Pocket":                        "https://www.smspower.org/Games/SidePocket-GG",
	"Slam Dunk - Shouri-e no Starting 5": "https://www.smspower.org/Games/SlamDunk-GG",
	"Slider":                             "https://www.smspower.org/Games/Slider-GG",
	"The Smurfs":                         "https://www.smspower.org/Games/Smurfs-GG",
	"The Smurfs Travel the World":        "https://www.smspower.org/Games/SmurfsTravelTheWorld-GG",
	"Solitaire Poker":                    "https://www.smspower.org/Games/SolitairePoker-GG",
	"Sonic Blast":                        "https://www.smspower.org/Games/SonicBlast-GG",
	"Sonic Chaos":                        "https://www.smspower.org/Games/SonicChaos-GG",
	"Sonic Drift":                        "https://www.smspower.org/Games/SonicDrift-GG",
	"Sonic Drift 2":                      "https://www.smspower.org/Games/SonicDrift2-GG",
	"Sonic Labyrinth":                    "https://www.smspower.org/Games/SonicLabyrinth-GG",
	"Sonic Spinball":                     "https://www.smspower.org/Games/SonicSpinball-GG",
	"Sonic The Hedgehog":                 "https://www.smspower.org/Games/SonicTheHedgehog-GG",
	"Sonic The Hedgehog 2":               "https://www.smspower.org/Games/SonicTheHedgehog2-GG",
	"Sonic The Hedgehog Triple Trouble":  "https://www.smspower.org/Games/SonicTripleTrouble-GG",
	"Space Harrier":                      "https://www.smspower.org/Games/SpaceHarrier-GG",
	"Spirou":                             "https://www.smspower.org/Games/Spirou-GG",
	"Sports Illustrated Championship Football & Baseball": "https://www.smspower.org/Games/SportsIllustrated-GG",
	"Sports Trivia": "https://www.smspower.org/Games/SportsTrivia-GG",
	"Star Trek Generations - Beyond the Nexus":                       "https://www.smspower.org/Games/StarTrekGenerations-GG",
	"Star Trek The Next Generation - The Advanced Holodeck Tutorial": "https://www.smspower.org/Games/StarTrekTheNextGeneration-GG",
	"Star Wars":                         "https://www.smspower.org/Games/StarWars-GG",
	"Street Hero":                       "https://www.smspower.org/Games/StreetHero-GG",
	"Streets of Rage":                   "https://www.smspower.org/Games/StreetsOfRage-GG",
	"Streets of Rage II":                "https://www.smspower.org/Games/StreetsOfRageII-GG",
	"Striker":                           "https://www.smspower.org/Games/Striker-GG",
	"Super Battletank":                  "https://www.smspower.org/Games/SuperBattletank-GG",
	"Super Columns":                     "https://www.smspower.org/Games/SuperColumns-GG",
	"Superman The Man of Steel":         "https://www.smspower.org/Games/Superman-GG",
	"Super Momotarou Dentetsu III":      "https://www.smspower.org/Games/SuperMomotarouDentetsuIII-GG",
	"Super Monaco GP":                   "https://www.smspower.org/Games/SuperMonacoGP-GG",
	"Super Monaco GP II":                "https://www.smspower.org/Games/SuperMonacoGPII-GG",
	"Super Off Road":                    "https://www.smspower.org/Games/SuperOffRoad-GG",
	"Super Tetris":                      "https://www.smspower.org/Games/SuperTetris-GG",
	"T2 The Arcade Game":                "https://www.smspower.org/Games/T2TheArcadeGame-GG",
	"Tails Adventures":                  "https://www.smspower.org/Games/TailsAdventures-GG",
	"Tails' Skypatrol":                  "https://www.smspower.org/Games/TailsSkypatrol-GG",
	"Tant-R":                            "https://www.smspower.org/Games/TantR-GG",
	"Tarzan - Lord of the Jungle":       "https://www.smspower.org/Games/Tarzan-GG",
	"Tatakae! Pro Yakyuu Twin League":   "https://www.smspower.org/Games/TatakaeProYakyuuTwinLeague-GG",
	"Tempo Jr.":                         "https://www.smspower.org/Games/TempoJr-GG",
	"Tengen World Cup Soccer":           "https://www.smspower.org/Games/TengenWorldCupSoccer-GG",
	"The Terminator":                    "https://www.smspower.org/Games/Terminator-GG",
	"Tesserae":                          "https://www.smspower.org/Games/Tesserae-GG",
	"Tintin in Tibet":                   "https://www.smspower.org/Games/TintinInTibet-GG",
	"Torarete Tamaruka!?":               "https://www.smspower.org/Games/TorareteTamaruka-GG",
	"Virtua Fighter Animation":          "https://www.smspower.org/Games/VirtuaFighterAnimation-GG",
	"VR Troopers":                       "https://www.smspower.org/Games/VRTroopers-GG",
	"WildSnake":                         "https://www.smspower.org/Games/WildSnake-GG",
	"Winter Olympics":                   "https://www.smspower.org/Games/WinterOlympics-GG",
	"Wizard Pinball":                    "https://www.smspower.org/Games/WizardPinball-GG",
	"Wolfchild":                         "https://www.smspower.org/Games/Wolfchild-GG",
	"Wonder Boy":                        "https://www.smspower.org/Games/WonderBoy-GG",
	"Wonder Boy The Dragon's Trap":      "https://www.smspower.org/Games/WonderBoyIII-GG",
	"Woody Pop":                         "https://www.smspower.org/Games/WoodyPop-GG",
	"World Class Leader Board":          "https://www.smspower.org/Games/WorldClassLeaderBoard-GG",
	"World Cup USA 94":                  "https://www.smspower.org/Games/WorldCupUSA94-GG",
	"World Series Baseball":             "https://www.smspower.org/Games/WorldSeriesBaseball-GG",
	"WWF Raw":                           "https://www.smspower.org/Games/WWFRaw-GG",
	"X-Men Mojo World":                  "https://www.smspower.org/Games/XMenMojoWorld-GG",
	"X-Terminator":                      "https://www.smspower.org/Games/XTerminator-GG",
	"Yogi Bear in Yogi Bear's Goldrush": "https://www.smspower.org/Games/YogiBear-GG",
	"Yu Yu Hakusho II - Gekitou! Nanakyou no Tatakai": "https://www.smspower.org/Games/YuYuHakushoII-GG",
	"Zoop": "https://www.smspower.org/Games/Zoop-GG",
}
