package main

import (
	"fmt"
	"strconv"
	"strings"
)

func generateMisterGameGearGames(generate bool) {
	gamegearTitleAdded := make(map[string]bool)
	gamegearImages := make(map[string]string)
	gamegearGameList := []string{}
	compileMisterConsoleData(gamegearTitleAdded, &gamegearGameList, gamegearImages, gamegearVideos, "gamegear")
	// gamegearVideoReport(&gamegearGameList)
	if generate {
		generateMisterConsoleHTML("Game Gear", &gamegearGameList, gamegearImages, gamegearVideos, "gamegear", "game gear")
	}
}

func gamegearVideoReport(gameList *[]string) {
	// Calculate Best Video Matches
	var distZero = 0
	var distOne = 0
	var distTwo = 0
	var distThree = 0
	var distFour = 0
	var distFive = 0
	var distMoreThanFive = 0
	for _, v := range *gameList {
		// Only do this process for titles with no video
		if gamegearVideos[v] == "" {

			tempName := v

			if idx := strings.IndexByte(tempName, '('); idx >= 0 {
				tempName = strings.TrimRight(tempName[:idx], " ")
			}
			if strings.Contains(tempName, ", The") {
				tempName = strings.Replace(tempName, ", The", "", 1)
				tempName = "The " + tempName
			}

			var str1 = []rune(tempName)
			var lowestDistance = 99
			var lowestName = ""
			for _, n := range gamegearLongplays {
				temptemp := n[:strings.IndexByte(n, '|')]
				var str2 = []rune(temptemp)
				var tempDistance = levenshtein(str1, str2)
				if tempDistance < lowestDistance {
					lowestDistance = tempDistance
					lowestName = n //temptemp
				}
			}
			if lowestDistance == 0 {
				distZero = distZero + 1
			}
			if lowestDistance == 1 {
				distOne = distOne + 1
			}
			if lowestDistance == 2 {
				distTwo = distTwo + 1
			}
			if lowestDistance == 3 {
				distThree = distThree + 1
			}
			if lowestDistance == 4 {
				distFour = distFour + 1
			}
			if lowestDistance == 5 {
				distFive = distFive + 1
			}
			if lowestDistance > 5 {
				distMoreThanFive = distMoreThanFive + 1
			}

			// Cycle through: <= 2, == 3, == 4, == 5, > 5
			//  0, 1, 2 are correct
			if lowestDistance > 3 {

				//lowestName = lowestName[strings.IndexByte(lowestName, '|')+1:] // for final
				//fmt.Println("\"" + v + "\": \"" + lowestName + "\",")          // for testing

				// For the rest without matches
				fmt.Println("\"" + v + "\": \"\",")
				if false {
					fmt.Println(lowestName)
				}
			}
		}
	}
	// Reporting
	fmt.Println("Distance 0: " + strconv.Itoa(distZero))
	fmt.Println("Distance 1: " + strconv.Itoa(distOne))
	fmt.Println("Distance 2: " + strconv.Itoa(distTwo))
	fmt.Println("Distance 3: " + strconv.Itoa(distThree))
	fmt.Println("Distance 4: " + strconv.Itoa(distFour))
	fmt.Println("Distance 5: " + strconv.Itoa(distFive))
	fmt.Println("Distance 5+: " + strconv.Itoa(distMoreThanFive))
}

var gamegearVideos = map[string]string{
	"5 in One Fun Pak":                           "q0txhq5XNvc",
	"Aerial Assault":                             "Lx0Aqsd8kJ4",
	"Aladdin":                                    "xH1gHd_Nniw",
	"Alien 3":                                    "mdrPKcXjpDY",
	"Alien Syndrome":                             "jNKNYWRIbAg",
	"Andre Agassi Tennis":                        "tt6-LgtH_PY",
	"Arcade Classics":                            "eWOojcoLvf8",
	"Arena - Maze of Death":                      "00QigNZUNkg",
	"Ariel - The Little Mermaid":                 "L4DDbdUfIVk",
	"Asterix and the Great Rescue":               "Gp-NalOTebI",
	"Asterix and the Secret Mission":             "LRuwD2rhSLc",
	"Ax Battler - A Legend of Golden Axe":        "YB8LyyYoUj8",
	"Baku Baku":                                  "lPiftOXYQ7o",
	"Barbie Super Model":                         "YTm6ZbODw0s",
	"Bart vs. The World":                         "oc43SHm_vz4",
	"Batter Up":                                  "XKl-I1H6TuA",
	"Battletoads":                                "dY9fI916eH0",
	"Berlin no Kabe - The BerlinWall":            "BVJnpWL95Q8",
	"Bonkers Wax Up!":                            "lgvnMP23-h0",
	"BreakThru!":                                 "",
	"Bubble Bobble":                              "dMDLhdNnI6k",
	"Bugs Bunny in Double Trouble":               "xi6WWlbnXJQ",
	"Buster Fight":                               "nUt-i97cPWc",
	"Car Licence":                                "T9azFvVLWAE",
	"Castle of Illusion - Starring Mickey Mouse": "yn1bHWfS7kA",
	"Cave Dude":                                  "fzw2WayDkn4",
	"Championship Hockey":                        "GOCS3NmVwhE",
	"Chase H.Q.":                                 "PgxhPBvPPd8",
	"Cheese Cat-Astrophe":                        "R04v28QTzbk",
	"Chicago Syndicate":                          "Xbbd20ikLXk",
	"Chuck Rock II Son of Chuck":                 "Js0jX_sSJko",
	"Chuck Rock":                                 "nSEclmPePxw",
	"CJ Elephant Fugitive":                       "8uuZVmcE5Og",
	"Cliffhanger":                                "DcQpU3pVuYM",
	"Clutch Hitter":                              "y77Uwc7e_QY",
	"Columns":                                    "CCZ_2d_oF8Y",
	"Cool Spot":                                  "hZ-PgyXVS-w",
	"Cosmic Spacehead":                           "juU3NGQjDVw",
	"Crazy Faces":                                "w3rilpkKuTg",
	"Crystal Warriors":                           "80rdRFW9rJo",
	"Cutthroat Island":                           "N2UnYmvCJ9Q",
	"Daffy Duck in Hollywood":                    "Mqv899cT8gg",
	"David Robinson's Supreme Court":             "deRRZW2tnZo",
	"Deep Duck Trouble":                          "RfCemMq4sJQ",
	"Defenders of Oasis":                         "SeWY6Ef1GT0",
	"Desert Strike - Return to the Gulf":         "xzGgW3_OVQE",
	"Devilish":                                   "IF5SxPXpoM8",
	"Dinobasher - Starring Bignose the Caveman":  "jIw5YKe_BzQ",
	"Doraemon Waku Waku Pocket Paradise":         "SzU7v0PQS80",
	"Double Dragon":                              "pNaa6H3fXPU&index=2",
	"Dr. Franken":                                "lOUETFwi7Ls",
	"Dracula":                                    "lqKzn_bD7w4",
	"Dragon The Bruce Lee Story":                 "CAms-CTQrGs",
	"Dropzone":                                   "TEqijl9OOQc",
	"Dynamite Headdy":                            "jETQexromd0",
	"Earthworm Jim":                              "1vYm_wwp02U",
	"Ecco - The Tides of Time":                   "-uSipyHfZAg",
	"Ecco the Dolphin":                           "fcoIUsVlNmk",
	"Ernie Els Golf":                             "LT8z6vB1y1Y",
	"Eternal Legend":                             "KPQ-xTNmRrk",
	"F-15 Strike Eagle":                          "zGWDlg4sKR4",
	"F1 - World Championship Edition":            "j1O4822Bq2I",
	"F1":                                         "tzUwfJhtcUQ",
	"Face Ball 2000":                             "8LDEzR73_YU",
	"Factory Panic":                              "B8uak0W9Chc",
	"Fatal Fury Special":                         "auRr5UIb_2Y",
	"FIFA International Soccer":                  "vwH_ieU5Aos",
	"FIFA Soccer 96":                             "3GQ2awwpU_c",
	"Foreman for Real":                           "S8yLausaNjU",
	"Fray -Shugyou hen-":                         "9dJ0N8LYYIg",
	"Fred Couples Golf":                          "vF15CMMnFjo",
	"Frogger":                                    "MwrB8Tzkpak",
	"G-LOC - Air Battle":                         "",
	"Galaga '91":                                 "WEjhBzbCIic",
	"Gamble Panic":                               "tq2uHPojFmw",
	"Garfield Caught in the Act":                 "",
	"Gear Stadium Heiseiban":                     "",
	"GG Portrait - Pai Chen":                     "4Qcddl8WAUk",
	"GG Portrait - Yuuki Akira":                  "jtCNF7P0JGk",
	"Godzilla - Kaijuu Daishingeki":              "",
	"GP Rider":                                   "ts9gnl3y07A",
	"Greendog - The Beached Surfer Dude!":        "",
	"Halley Wars":                                "4g_9Ly3S72s&feature=plcp",
	"Heavy weight Champ":                         "",
	"Home Alone":                                 "",
	"House of Tarot":                             "4zdn4h9istw",
	"Hurricanes":                                 "QjMlgwnZPqM",
	"Hyper Pro Yakyuu '92":                       "",
	"Ichidant-R GG":                              "",
	"Indiana Jones and the Last Crusade The Action Game": "",
	"J League GG Pro Striker '94":                        "",
	"J League Soccer Dream Eleven":                       "",
	"James Bond 007 The Duel":                            "",
	"James Pond 3 - Operation Starfi5h":                  "",
	"James Pond II - Codename RoboCod":                   "",
	"Jang Pung II":                                       "",
	"Jeopardy! Sports Edition":                           "ZyyW3WYE13w",
	"Jeopardy!":                                          "aANGr-uWdO0",
	"Joe Montana Football":                               "ATjB36n0cAs",
	"Junction":                                           "",
	"Jungle Strike":                                      "",
	"Jurassic Park":                                      "",
	"Kawasaki Superbike Challenge":                       "",
	"Kishin Douji Zenki":                                 "FbXk-RsuxCA",
	"KLAX":                                               "",
	"Land of Illusion - Starring Mickey Mouse":           "",
	"Last Action Hero":                                   "",
	"Lemmings 2 The Tribes":                              "",
	"Lemmings":                                           "3jbiquCYOFE",
	"Madden 96":                                          "",
	"Madoh Monogatari II - Aruru 16-sai":                 "",
	"Madoh Monogatari III - Kyuukyoku Joou-sama":         "",
	"Man Overboard!":                                     "",
	"Marble Madness":                                     "BwjQWBx6xQE",
	"Marko's Magic Football":                             "",
	"Micro Machines 2 Turbo Tournament":                  "0l_eTU_pCac",
	"Micro Machines":                                     "IcVm0TnIA9c",
	"Mighty Morphin Power Rangers":                       "HZciijt8mGg",
	"Moldorian -Hikari to Yami no Shisutaa-":             "",
	"Monster Truck Wars":                                 "",
	"Mortal Kombat 3":                                    "8D-D-jTU09A",
	"Mortal Kombat II":                                   "67tnHzcKyOM",
	"Mortal Kombat":                                      "QKcWryFWc_s",
	"Ms. Pac-Man":                                        "bthgJuYM6F8",
	"Nazo Puyo 2":                                        "",
	"Nazo Puyo Aruru no Ruu":                             "",
	"Nazo Puyo":                                          "",
	"NBA Action - Starring David Robinson":               "",
	"NBA Jam T.E.":                                       "",
	"NBA Jam":                                            "",
	"Neko Dai Suki!":                                     "",
	"NFL '95":                                            "",
	"NHL Hockey":                                         "",
	"Ninja Gaiden":                                       "mHoPEgl85iE",
	"Ninkuu 2 -Tenkuuryuu-e no Michi-":                   "",
	"Ninkuu Gaiden - Hiroyuki Daikatsugeki":              "",
	"Ninkuu":                                             "E6Ysx897rrU",
	"Nomo Hideo no World Series Baseball":                "",
	"Off the Wall":                                       "",
	"Olympic Gold":                                       "",
	"Out Run Europa":                                     "x8w7WU5jwuU",
	"Out Run":                                            "HmlsVz-ypko",
	"Pac-Attack":                                         "",
	"Pac-In-Time":                                        "",
	"Pac-Man":                                            "OBVx8WgUyRo",
	"Panzer Dragoon Mini":                                "n3C55fzpMwU",
	"Paperboy 2":                                         "",
	"Pengo":                                              "",
	"Pet Club Inu Dai Suki!":                             "",
	"Pete Sampras Tennis":                                "",
	"PGA TOUR 96":                                        "",
	"Pinball Dreams":                                     "Uxtj6ZW3eIw",
	"Poker Face Paul's Gin":                              "",
	"Poker Face Paul's Poker":                            "",
	"Poker Face Paul's Solitaire":                        "",
	"Popeye Beach Volley Ball":                           "",
	"Power Drive":                                        "",
	"Primal Rage":                                        "krLU1mWISgM",
	"Pro Yakyuu GG League":                               "",
	"Putt & Putter":                                      "",
	"Puyo Puyo 2":                                        "",
	"Puzzle Bobble":                                      "",
	"Quest for the Shaven Yak Starring Ren Hoëk & Stimpy": "",
	"R.B.I. Baseball '94":      "",
	"Rastan Saga":              "",
	"Rise of the Robots":       "1bVMt_FhubA",
	"Ristar the Shooting Star": "",
	"Road Rash":                "",
	"Samurai Shodown":          "97v14F_7RxQ",
	"Scratch Golf":             "",
	"Sega Game Pack 4 in 1":    "",
	"Sensible Soccer":          "",
	"Shanghai II":              "",
	"Shaq Fu":                  "uoVSsEaZWs8",
	"Shining Force Gaiden -Ensei Jashin no Kuni e-": "",
	"Shining Force Gaiden II -Jashin no Mezame-":    "",
	"Side Pocket":                        "Wy4TlYSt1mg",
	"Slam Dunk - Shouri-e no Starting 5": "",
	"Slider":                             "TVL04b1iT_A",
	"Solitaire Poker":                    "",
	"Sonic Blast":                        "9BldSK2IllU",
	"Sonic Chaos":                        "_5-lLhmKqug",
	"Sonic Drift 2":                      "NZMkE1bsxwI",
	"Sonic Drift":                        "gbfTsGuPhzU",
	"Sonic Labyrinth":                    "97unZ7grgSc",
	"Sonic Spinball":                     "",
	"Sonic The Hedgehog 2":               "EYQhe5wskN0",
	"Sonic The Hedgehog Triple Trouble":  "",
	"Sonic The Hedgehog":                 "-D00HFMfmro",
	"Space Harrier":                      "69ewTAnYwk8",
	"Spirou":                             "",
	"Sports Illustrated Championship Football & Baseball": "",
	"Sports Trivia": "",
	"Star Trek Generations - Beyond the Nexus":                       "",
	"Star Trek The Next Generation - The Advanced Holodeck Tutorial": "",
	"Star Wars":                       "06poo5MgtsQ",
	"Street Hero":                     "",
	"Streets of Rage II":              "BGwChG7GY0o",
	"Streets of Rage":                 "XvyXWWdBWR0",
	"Striker":                         "",
	"Super Battletank":                "",
	"Super Columns":                   "",
	"Super Momotarou Dentetsu III":    "",
	"Super Monaco GP II":              "",
	"Super Monaco GP":                 "aRRZ38ZrtwM",
	"Super Off Road":                  "",
	"Super Tetris":                    "",
	"Superman The Man of Steel":       "",
	"T2 The Arcade Game":              "LDoyKgHLqgM",
	"Tails Adventures":                "W35oJcnF7qo",
	"Tails' Skypatrol":                "",
	"Tant-R":                          "",
	"Tarzan - Lord of the Jungle":     "",
	"Tatakae! Pro Yakyuu Twin League": "",
	"Tempo Jr.":                       "HkD-twOcRuU",
	"Tengen World Cup Soccer":         "",
	"Tesserae":                        "",
	"The Chessmaster":                 "",
	"The GG Shinobi":                  "",
	"The Itchy & Scratchy Game":       "b3GX9GuuFsU",
	"The Jungle Book":                 "",
	"The Lion King":                   "uSCkqtVTH0k",
	"The Lost World Jurassic Park":    "",
	"The Lucky Dime Caper - Starring Donald Duck": "",
	"The Smurfs Travel the World":                 "",
	"The Smurfs":                                  "",
	"The Terminator":                              "",
	"Tintin in Tibet":                             "SxdCgjVXGYw",
	"Torarete Tamaruka!?":                         "",
	"Virtua Fighter Animation":                    "dIO3zco9Nl8",
	"VR Troopers":                                 "9H-SUfoMci4",
	"WildSnake":                                   "",
	"Winter Olympics":                             "",
	"Wizard Pinball":                              "Byp7nfH4T-0",
	"Wolfchild":                                   "ouL0lGAcm8k",
	"Wonder Boy The Dragon's Trap":                "y57T5nlqR_Q",
	"Wonder Boy":                                  "",
	"Woody Pop":                                   "04XANNuUccY",
	"World Class Leader Board":                    "",
	"World Cup USA 94":                            "VEu-tr_qStU",
	"World Series Baseball":                       "",
	"WWF Raw":                                     "",
	"X-Men Mojo World":                            "",
	"X-Terminator":                                "",
	"Yogi Bear in Yogi Bear's Goldrush":           "",
	"Yu Yu Hakusho II - Gekitou! Nanakyou no Tatakai": "",
	"Zoop": "neGvWyEh4Pk",
}

var gamegearGameInfo = map[string]string{
	"5 in One Fun Pak":                           "https://www.smspower.org/Games/5InOneFunPak-GG",
	"Aerial Assault":                             "https://www.smspower.org/Games/AerialAssault-GG",
	"Aladdin":                                    "https://www.smspower.org/Games/Aladdin-GG",
	"Alien 3":                                    "https://www.smspower.org/Games/Alien3-GG",
	"Alien Syndrome":                             "https://www.smspower.org/Games/AlienSyndrome-GG",
	"Andre Agassi Tennis":                        "https://www.smspower.org/Games/AndreAgassiTennis-GG",
	"Arcade Classics":                            "https://www.smspower.org/Games/ArcadeClassics-GG",
	"Arena - Maze of Death":                      "https://www.smspower.org/Games/ArenaMazeOfDeath-GG",
	"Ariel - The Little Mermaid":                 "https://www.smspower.org/Games/ArielTheLittleMermaid-GG",
	"Asterix and the Great Rescue":               "https://www.smspower.org/Games/AsterixAndTheGreatRescue-GG",
	"Asterix and the Secret Mission":             "https://www.smspower.org/Games/AsterixAndTheSecretMission-GG",
	"Ax Battler - A Legend of Golden Axe":        "https://www.smspower.org/Games/AxBattler-GG",
	"Baku Baku":                                  "https://www.smspower.org/Games/BakuBakuAnimal-GG",
	"Barbie Super Model":                         "https://www.smspower.org/Games/BarbieSuperModel-GG",
	"Bart vs. The World":                         "https://www.smspower.org/Games/BartVsTheWorld-GG",
	"Batter Up":                                  "https://www.smspower.org/Games/BatterUp-GG",
	"Battletoads":                                "https://www.smspower.org/Games/Battletoads-GG",
	"Berlin no Kabe - The BerlinWall":            "https://www.smspower.org/Games/BerlinNoKabe-GG",
	"Bonkers Wax Up!":                            "https://www.smspower.org/Games/BonkersWaxUp-GG",
	"BreakThru!":                                 "https://www.smspower.org/Games/BreakThru-GG",
	"Bubble Bobble":                              "https://www.smspower.org/Games/BubbleBobble-GG",
	"Bugs Bunny in Double Trouble":               "https://www.smspower.org/Games/BugsBunnyInDoubleTrouble-GG",
	"Buster Fight":                               "https://www.smspower.org/Games/BusterFight-GG",
	"Car Licence":                                "https://www.smspower.org/Games/CarLicence-GG",
	"Castle of Illusion - Starring Mickey Mouse": "https://www.smspower.org/Games/CastleOfIllusion-GG",
	"Cave Dude":                                  "https://www.smspower.org/Games/CaveDude-GG",
	"Championship Hockey":                        "https://www.smspower.org/Games/ChampionshipHockey-GG",
	"Chase H.Q.":                                 "https://www.smspower.org/Games/ChaseHQ-GG",
	"Cheese Cat-Astrophe":                        "https://www.smspower.org/Games/CheeseCatastrophe-GG",
	"The Chessmaster":                            "https://www.smspower.org/Games/Chessmaster-GG",
	"Chicago Syndicate":                          "https://www.smspower.org/Games/ChicagoSyndicate-GG",
	"Chuck Rock":                                 "https://www.smspower.org/Games/ChuckRock-GG",
	"Chuck Rock II Son of Chuck":                 "https://www.smspower.org/Games/ChuckRockII-GG",
	"CJ Elephant Fugitive":                       "https://www.smspower.org/Games/CJElephantFugitive-GG",
	"Cliffhanger":                                "https://www.smspower.org/Games/Cliffhanger-GG",
	"Clutch Hitter":                              "https://www.smspower.org/Games/ClutchHitter-GG",
	"Columns":                                    "https://www.smspower.org/Games/Columns-GG",
	"Cool Spot":                                  "https://www.smspower.org/Games/CoolSpot-GG",
	"Cosmic Spacehead":                           "https://www.smspower.org/Games/CosmicSpacehead-GG",
	"Crazy Faces":                                "https://www.smspower.org/Games/CrazyFaces-GG",
	"Crystal Warriors":                           "https://www.smspower.org/Games/CrystalWarriors-GG",
	"Cutthroat Island":                           "https://www.smspower.org/Games/CutthroatIsland-GG",
	"Daffy Duck in Hollywood":                    "https://www.smspower.org/Games/DaffyDuckInHollywood-GG",
	"David Robinson's Supreme Court":             "https://www.smspower.org/Games/DavidRobinsonSupremeCourt-GG",
	"Deep Duck Trouble":                          "https://www.smspower.org/Games/DeepDuckTrouble-GG",
	"Defenders of Oasis":                         "https://www.smspower.org/Games/DefendersOfOasis-GG",
	"Desert Strike - Return to the Gulf":         "https://www.smspower.org/Games/DesertStrike-GG",
	"Devilish":                                   "https://www.smspower.org/Games/Devilish-GG",
	"Dinobasher - Starring Bignose the Caveman":  "https://www.smspower.org/Games/Dinobasher-GG",
	"Doraemon Waku Waku Pocket Paradise":         "https://www.smspower.org/Games/DoraemonWakuWakuPocketParadise-GG",
	"Double Dragon":                              "https://www.smspower.org/Games/DoubleDragon-GG",
	"Dracula":                                    "https://www.smspower.org/Games/Dracula-GG",
	"Dragon The Bruce Lee Story":                 "https://www.smspower.org/Games/Dragon-GG",
	"Dr. Franken":                                "https://www.smspower.org/Games/DrFranken-GG",
	"Dropzone":                                   "https://www.smspower.org/Games/Dropzone-GG",
	"Dynamite Headdy":                            "https://www.smspower.org/Games/DynamiteHeaddy-GG",
	"Earthworm Jim":                              "https://www.smspower.org/Games/EarthwormJim-GG",
	"Ecco the Dolphin":                           "https://www.smspower.org/Games/EccoTheDolphin-GG",
	"Ecco - The Tides of Time":                   "https://www.smspower.org/Games/EccoTheTidesOfTime-GG",
	"Ernie Els Golf":                             "https://www.smspower.org/Games/ErnieElsGolf-GG",
	"Eternal Legend":                             "https://www.smspower.org/Games/EternalLegend-GG",
	"F1":                                         "https://www.smspower.org/Games/F1-GG",
	"F-15 Strike Eagle":                          "https://www.smspower.org/Games/F15StrikeEagle-GG",
	"F1 - World Championship Edition":            "https://www.smspower.org/Games/F1WorldChampionshipEdition-GG",
	"Face Ball 2000":                             "https://www.smspower.org/Games/FaceBall2000-GG",
	"Factory Panic":                              "https://www.smspower.org/Games/FactoryPanic-GG",
	"Fatal Fury Special":                         "https://www.smspower.org/Games/FatalFurySpecial-GG",
	"FIFA International Soccer":                  "https://www.smspower.org/Games/FIFAInternationalSoccer-GG",
	"FIFA Soccer 96":                             "https://www.smspower.org/Games/FIFASoccer96-GG",
	"Foreman for Real":                           "https://www.smspower.org/Games/ForemanForReal-GG",
	"Fray -Shugyou hen-":                         "https://www.smspower.org/Games/Fray-GG",
	"Fred Couples Golf":                          "https://www.smspower.org/Games/FredCouplesGolf-GG",
	"Frogger":                                    "https://www.smspower.org/Games/Frogger-GG",
	"Galaga '91":                                 "https://www.smspower.org/Games/Galaga91-GG",
	"Gamble Panic":                               "https://www.smspower.org/Games/GamblePanic-GG",
	"Garfield Caught in the Act":                 "https://www.smspower.org/Games/GarfieldCaughtInTheAct-GG",
	"Gear Stadium Heiseiban":                     "https://www.smspower.org/Games/GearStadiumHeiseiban-GG",
	"GG Portrait - Pai Chen":                     "https://www.smspower.org/Games/GGPortraitPaiChen-GG",
	"GG Portrait - Yuuki Akira":                  "https://www.smspower.org/Games/GGPortraitYuukiAkira-GG",
	"The GG Shinobi":                             "https://www.smspower.org/Games/GGShinobi-GG",
	"G-LOC - Air Battle":                         "https://www.smspower.org/Games/GLOCAirBattle-GG",
	"Godzilla - Kaijuu Daishingeki":              "https://www.smspower.org/Games/Godzilla-GG",
	"GP Rider":                                   "https://www.smspower.org/Games/GPRider-GG",
	"Greendog - The Beached Surfer Dude!":        "https://www.smspower.org/Games/Greendog-GG",
	"Halley Wars":                                "https://www.smspower.org/Games/HalleyWars-GG",
	"Heavy weight Champ":                         "https://www.smspower.org/Games/HeavyweightChamp-GG",
	"Home Alone":                                 "https://www.smspower.org/Games/HomeAlone-GG",
	"House of Tarot":                             "https://www.smspower.org/Games/HouseOfTarot-GG",
	"Hurricanes":                                 "https://www.smspower.org/Games/Hurricanes-GG",
	"Hyper Pro Yakyuu '92":                       "https://www.smspower.org/Games/HyperProYakyuu92-GG",
	"Ichidant-R GG":                              "https://www.smspower.org/Games/IchidantRGG-GG",
	"Indiana Jones and the Last Crusade The Action Game": "https://www.smspower.org/Games/IndianaJonesAndTheLastCrusade-GG",
	"The Itchy & Scratchy Game":                          "https://www.smspower.org/Games/ItchyAndScratchyGame-GG",
	"James Bond 007 The Duel":                            "https://www.smspower.org/Games/JamesBond007TheDuel-GG",
	"James Pond 3 - Operation Starfi5h":                  "https://www.smspower.org/Games/JamesPond3-GG",
	"James Pond II - Codename RoboCod":                   "https://www.smspower.org/Games/JamesPondII-GG",
	"Jang Pung II":                                       "https://www.smspower.org/Games/JangPungII-GG",
	"Jeopardy!":                                          "https://www.smspower.org/Games/Jeopardy-GG",
	"Jeopardy! Sports Edition":                           "https://www.smspower.org/Games/JeopardySportsEdition-GG",
	"J League GG Pro Striker '94":                        "https://www.smspower.org/Games/JLeagueGGProStriker94-GG",
	"J League Soccer Dream Eleven":                       "https://www.smspower.org/Games/JLeagueSoccerDreamEleven-GG",
	"Joe Montana Football":                               "https://www.smspower.org/Games/JoeMontanaFootball-GG",
	"Junction":                                           "https://www.smspower.org/Games/Junction-GG",
	"The Jungle Book":                                    "https://www.smspower.org/Games/JungleBook-GG",
	"Jungle Strike":                                      "https://www.smspower.org/Games/JungleStrike-GG",
	"Jurassic Park":                                      "https://www.smspower.org/Games/JurassicPark-GG",
	"Kawasaki Superbike Challenge":                       "https://www.smspower.org/Games/KawasakiSuperbikeChallenge-GG",
	"Kishin Douji Zenki":                                 "https://www.smspower.org/Games/KishinDoujiZenki-GG",
	"KLAX":                                               "https://www.smspower.org/Games/KLAX-GG",
	"Land of Illusion - Starring Mickey Mouse":           "https://www.smspower.org/Games/LandOfIllusion-GG",
	"Last Action Hero":                                   "https://www.smspower.org/Games/LastActionHero-GG",
	"Lemmings":                                           "https://www.smspower.org/Games/Lemmings-GG",
	"Lemmings 2 The Tribes":                              "https://www.smspower.org/Games/Lemmings2-GG",
	"The Lion King":                                      "https://www.smspower.org/Games/LionKing-GG",
	"The Lost World Jurassic Park":                       "https://www.smspower.org/Games/LostWorld-GG",
	"The Lucky Dime Caper - Starring Donald Duck":        "https://www.smspower.org/Games/LuckyDimeCaper-GG",
	"Madden 96":                                          "https://www.smspower.org/Games/Madden96-GG",
	"Madoh Monogatari II - Aruru 16-sai":                 "https://www.smspower.org/Games/MadohMonogatariII-GG",
	"Madoh Monogatari III - Kyuukyoku Joou-sama":         "https://www.smspower.org/Games/MadohMonogatariIII-GG",
	"Man Overboard!":                                     "https://www.smspower.org/Games/ManOverboard-GG",
	"Marble Madness":                                     "https://www.smspower.org/Games/MarbleMadness-GG",
	"Marko's Magic Football":                             "https://www.smspower.org/Games/MarkosMagicFootball-GG",
	"Micro Machines":                                     "https://www.smspower.org/Games/MicroMachines-GG",
	"Micro Machines 2 Turbo Tournament":                  "https://www.smspower.org/Games/MicroMachines2-GG",
	"Mighty Morphin Power Rangers":                       "https://www.smspower.org/Games/MightyMorphinPowerRangers-GG",
	"Moldorian -Hikari to Yami no Shisutaa-":             "https://www.smspower.org/Games/Moldorian-GG",
	"Monster Truck Wars":                                 "https://www.smspower.org/Games/MonsterTruckWars-GG",
	"Mortal Kombat":                                      "https://www.smspower.org/Games/MortalKombat-GG",
	"Mortal Kombat 3":                                    "https://www.smspower.org/Games/MortalKombat3-GG",
	"Mortal Kombat II":                                   "https://www.smspower.org/Games/MortalKombatII-GG",
	"Ms. Pac-Man":                                        "https://www.smspower.org/Games/MsPacMan-GG",
	"Nazo Puyo":                                          "https://www.smspower.org/Games/NazoPuyo-GG",
	"Nazo Puyo 2":                                        "https://www.smspower.org/Games/NazoPuyo2-GG",
	"Nazo Puyo Aruru no Ruu":                             "https://www.smspower.org/Games/NazoPuyoAruruNoRuu-GG",
	"NBA Action - Starring David Robinson":               "https://www.smspower.org/Games/NBAAction-GG",
	"NBA Jam":                                            "https://www.smspower.org/Games/NBAJam-GG",
	"NBA Jam T.E.":                                       "https://www.smspower.org/Games/NBAJamTE-GG",
	"Neko Dai Suki!":                                     "https://www.smspower.org/Games/NekoDaiSuki-GG",
	"NFL '95":                                            "https://www.smspower.org/Games/NFL95-GG",
	"NHL Hockey":                                         "https://www.smspower.org/Games/NHLHockey-GG",
	"Ninja Gaiden":                                       "https://www.smspower.org/Games/NinjaGaiden-GG",
	"Ninkuu":                                             "https://www.smspower.org/Games/Ninkuu-GG",
	"Ninkuu 2 -Tenkuuryuu-e no Michi-":                   "https://www.smspower.org/Games/Ninkuu2-GG",
	"Ninkuu Gaiden - Hiroyuki Daikatsugeki":              "https://www.smspower.org/Games/NinkuuGaiden-GG",
	"Nomo Hideo no World Series Baseball":                "https://www.smspower.org/Games/NomosWorldSeriesBaseball-GG",
	"Off the Wall":                                       "https://www.smspower.org/Games/OffTheWall-GG",
	"Olympic Gold":                                       "https://www.smspower.org/Games/OlympicGold-GG",
	"Out Run":                                            "https://www.smspower.org/Games/OutRun-GG",
	"Out Run Europa":                                     "https://www.smspower.org/Games/OutRunEuropa-GG",
	"Pac-Attack":                                         "https://www.smspower.org/Games/PacAttack-GG",
	"Pac-In-Time":                                        "https://www.smspower.org/Games/PacInTime-GG",
	"Pac-Man":                                            "https://www.smspower.org/Games/PacMan-GG",
	"Panzer Dragoon Mini":                                "https://www.smspower.org/Games/PanzerDragoonMini-GG",
	"Paperboy 2":                                         "https://www.smspower.org/Games/Paperboy2-GG",
	"Pengo":                                              "https://www.smspower.org/Games/Pengo-GG",
	"Pet Club Inu Dai Suki!":                             "https://www.smspower.org/Games/PetClubInuDaiSuki-GG",
	"Pete Sampras Tennis":                                "https://www.smspower.org/Games/PeteSamprasTennis-GG",
	"PGA TOUR 96":                                        "https://www.smspower.org/Games/PGATour96-GG",
	"Pinball Dreams":                                     "https://www.smspower.org/Games/PinballDreams-GG",
	"Poker Face Paul's Gin":                              "https://www.smspower.org/Games/PokerFacePaulsGin-GG",
	"Poker Face Paul's Poker":                            "https://www.smspower.org/Games/PokerFacePaulsPoker-GG",
	"Poker Face Paul's Solitaire":                        "https://www.smspower.org/Games/PokerFacePaulsSolitaire-GG",
	"Popeye Beach Volley Ball":                           "https://www.smspower.org/Games/PopeyeBeachVolleyBall-GG",
	"Power Drive":                                        "https://www.smspower.org/Games/PowerDrive-GG",
	"Primal Rage":                                        "https://www.smspower.org/Games/PrimalRage-GG",
	"Pro Yakyuu GG League":                               "https://www.smspower.org/Games/ProYakyuuGGLeague-GG",
	"Putt & Putter":                                      "https://www.smspower.org/Games/PuttAndPutter-GG",
	"Puyo Puyo 2":                                        "https://www.smspower.org/Games/PuyoPuyo2-GG",
	"Puzzle Bobble":                                      "https://www.smspower.org/Games/PuzzleBobble-GG",
	"Quest for the Shaven Yak Starring Ren Hoëk & Stimpy": "https://www.smspower.org/Games/QuestForTheShavenYak-GG",
	"Rastan Saga":              "https://www.smspower.org/Games/RastanSaga-GG",
	"R.B.I. Baseball '94":      "https://www.smspower.org/Games/RBIBaseball94-GG",
	"Rise of the Robots":       "https://www.smspower.org/Games/RiseOfTheRobots-GG",
	"Ristar the Shooting Star": "https://www.smspower.org/Games/RistarTheShootingStar-GG",
	"Road Rash":                "https://www.smspower.org/Games/RoadRash-GG",
	"Samurai Shodown":          "https://www.smspower.org/Games/SamuraiShodown-GG",
	"Scratch Golf":             "https://www.smspower.org/Games/ScratchGolf-GG",
	"Sega Game Pack 4 in 1":    "https://www.smspower.org/Games/SegaGamePack4In1-GG",
	"Sensible Soccer":          "https://www.smspower.org/Games/SensibleSoccer-GG",
	"Shanghai II":              "https://www.smspower.org/Games/ShanghaiII-GG",
	"Shaq Fu":                  "https://www.smspower.org/Games/ShaqFu-GG",
	"Shining Force Gaiden -Ensei Jashin no Kuni e-": "https://www.smspower.org/Games/ShiningForceGaiden-GG",
	"Shining Force Gaiden II -Jashin no Mezame-":    "https://www.smspower.org/Games/ShiningForceGaidenII-GG",
	"Side Pocket":                        "https://www.smspower.org/Games/SidePocket-GG",
	"Slam Dunk - Shouri-e no Starting 5": "https://www.smspower.org/Games/SlamDunk-GG",
	"Slider":                             "https://www.smspower.org/Games/Slider-GG",
	"The Smurfs":                         "https://www.smspower.org/Games/Smurfs-GG",
	"The Smurfs Travel the World":        "https://www.smspower.org/Games/SmurfsTravelTheWorld-GG",
	"Solitaire Poker":                    "https://www.smspower.org/Games/SolitairePoker-GG",
	"Sonic Blast":                        "https://www.smspower.org/Games/SonicBlast-GG",
	"Sonic Chaos":                        "https://www.smspower.org/Games/SonicChaos-GG",
	"Sonic Drift":                        "https://www.smspower.org/Games/SonicDrift-GG",
	"Sonic Drift 2":                      "https://www.smspower.org/Games/SonicDrift2-GG",
	"Sonic Labyrinth":                    "https://www.smspower.org/Games/SonicLabyrinth-GG",
	"Sonic Spinball":                     "https://www.smspower.org/Games/SonicSpinball-GG",
	"Sonic The Hedgehog":                 "https://www.smspower.org/Games/SonicTheHedgehog-GG",
	"Sonic The Hedgehog 2":               "https://www.smspower.org/Games/SonicTheHedgehog2-GG",
	"Sonic The Hedgehog Triple Trouble":  "https://www.smspower.org/Games/SonicTripleTrouble-GG",
	"Space Harrier":                      "https://www.smspower.org/Games/SpaceHarrier-GG",
	"Spirou":                             "https://www.smspower.org/Games/Spirou-GG",
	"Sports Illustrated Championship Football & Baseball": "https://www.smspower.org/Games/SportsIllustrated-GG",
	"Sports Trivia": "https://www.smspower.org/Games/SportsTrivia-GG",
	"Star Trek Generations - Beyond the Nexus":                       "https://www.smspower.org/Games/StarTrekGenerations-GG",
	"Star Trek The Next Generation - The Advanced Holodeck Tutorial": "https://www.smspower.org/Games/StarTrekTheNextGeneration-GG",
	"Star Wars":                         "https://www.smspower.org/Games/StarWars-GG",
	"Street Hero":                       "https://www.smspower.org/Games/StreetHero-GG",
	"Streets of Rage":                   "https://www.smspower.org/Games/StreetsOfRage-GG",
	"Streets of Rage II":                "https://www.smspower.org/Games/StreetsOfRageII-GG",
	"Striker":                           "https://www.smspower.org/Games/Striker-GG",
	"Super Battletank":                  "https://www.smspower.org/Games/SuperBattletank-GG",
	"Super Columns":                     "https://www.smspower.org/Games/SuperColumns-GG",
	"Superman The Man of Steel":         "https://www.smspower.org/Games/Superman-GG",
	"Super Momotarou Dentetsu III":      "https://www.smspower.org/Games/SuperMomotarouDentetsuIII-GG",
	"Super Monaco GP":                   "https://www.smspower.org/Games/SuperMonacoGP-GG",
	"Super Monaco GP II":                "https://www.smspower.org/Games/SuperMonacoGPII-GG",
	"Super Off Road":                    "https://www.smspower.org/Games/SuperOffRoad-GG",
	"Super Tetris":                      "https://www.smspower.org/Games/SuperTetris-GG",
	"T2 The Arcade Game":                "https://www.smspower.org/Games/T2TheArcadeGame-GG",
	"Tails Adventures":                  "https://www.smspower.org/Games/TailsAdventures-GG",
	"Tails' Skypatrol":                  "https://www.smspower.org/Games/TailsSkypatrol-GG",
	"Tant-R":                            "https://www.smspower.org/Games/TantR-GG",
	"Tarzan - Lord of the Jungle":       "https://www.smspower.org/Games/Tarzan-GG",
	"Tatakae! Pro Yakyuu Twin League":   "https://www.smspower.org/Games/TatakaeProYakyuuTwinLeague-GG",
	"Tempo Jr.":                         "https://www.smspower.org/Games/TempoJr-GG",
	"Tengen World Cup Soccer":           "https://www.smspower.org/Games/TengenWorldCupSoccer-GG",
	"The Terminator":                    "https://www.smspower.org/Games/Terminator-GG",
	"Tesserae":                          "https://www.smspower.org/Games/Tesserae-GG",
	"Tintin in Tibet":                   "https://www.smspower.org/Games/TintinInTibet-GG",
	"Torarete Tamaruka!?":               "https://www.smspower.org/Games/TorareteTamaruka-GG",
	"Virtua Fighter Animation":          "https://www.smspower.org/Games/VirtuaFighterAnimation-GG",
	"VR Troopers":                       "https://www.smspower.org/Games/VRTroopers-GG",
	"WildSnake":                         "https://www.smspower.org/Games/WildSnake-GG",
	"Winter Olympics":                   "https://www.smspower.org/Games/WinterOlympics-GG",
	"Wizard Pinball":                    "https://www.smspower.org/Games/WizardPinball-GG",
	"Wolfchild":                         "https://www.smspower.org/Games/Wolfchild-GG",
	"Wonder Boy":                        "https://www.smspower.org/Games/WonderBoy-GG",
	"Wonder Boy The Dragon's Trap":      "https://www.smspower.org/Games/WonderBoyIII-GG",
	"Woody Pop":                         "https://www.smspower.org/Games/WoodyPop-GG",
	"World Class Leader Board":          "https://www.smspower.org/Games/WorldClassLeaderBoard-GG",
	"World Cup USA 94":                  "https://www.smspower.org/Games/WorldCupUSA94-GG",
	"World Series Baseball":             "https://www.smspower.org/Games/WorldSeriesBaseball-GG",
	"WWF Raw":                           "https://www.smspower.org/Games/WWFRaw-GG",
	"X-Men Mojo World":                  "https://www.smspower.org/Games/XMenMojoWorld-GG",
	"X-Terminator":                      "https://www.smspower.org/Games/XTerminator-GG",
	"Yogi Bear in Yogi Bear's Goldrush": "https://www.smspower.org/Games/YogiBear-GG",
	"Yu Yu Hakusho II - Gekitou! Nanakyou no Tatakai": "https://www.smspower.org/Games/YuYuHakushoII-GG",
	"Zoop": "https://www.smspower.org/Games/Zoop-GG",
}

var gamegearLongplays = []string{
	"Aerial Assault|Lx0Aqsd8kJ4",
	"Aladdin|xH1gHd_Nniw",
	"Alien 3|mdrPKcXjpDY",
	"Alien Syndrome|jNKNYWRIbAg",
	"Ax Battler - A Legend of Golden Axe|YB8LyyYoUj8",
	"Baku Baku Animal|lPiftOXYQ7o",
	"Batman Forever|D0ShWKzNSRQ",
	"Batman Returns|0vob7jybaD4",
	"Battletoads|dY9fI916eH0",
	"Berlin no Kabe|BVJnpWL95Q8",
	"Bishoujo Senshi Sailor Moon S|yjc8L3-wwqk",
	"Bubble Bobble|dMDLhdNnI6k",
	"Bugs Bunny in Double Trouble|xi6WWlbnXJQ",
	"Bust-A-Move|RR6tgYJiP2I",
	"Buster Fight|nUt-i97cPWc",
	"Caesars Palace|jcRJNNJ7sAM",
	"Captain America and the Avengers|nOq9KtmJeXY",
	"Chuck Rock|nSEclmPePxw",
	"Chuck Rock II - Son of Chuck|Js0jX_sSJko",
	"Cliffhanger|DcQpU3pVuYM",
	"Columns|CCZ_2d_oF8Y",
	"Cool Spot|hZ-PgyXVS-w",
	"Cutthroat Island|N2UnYmvCJ9Q",
	"Daffy Duck in Hollywood|Mqv899cT8gg",
	"Deep Duck Trouble Starring Donald Duck|RfCemMq4sJQ",
	"Devilish|IF5SxPXpoM8",
	"Donald no Magical World|DiXCwJgUmUE",
	"Double Dragon|pNaa6H3fXPU&index=2",
	"Dr. Robotniks Mean Bean Machine|dqm6SFHOIJ4",
	"Dragon - The Bruce Lee Story|CAms-CTQrGs",
	"Dropzone|TEqijl9OOQc",
	"Dunk Kids|v6CtmiNK5oo",
	"Dynamite Headdy|jETQexromd0",
	"Dynamte Headdy (a)|nSpjnU7wmFo",
	"Earthworm Jim|1vYm_wwp02U",
	"Factory Panic|B8uak0W9Chc",
	"Fantasy Zone Gear|UXkLPKh04Wk",
	"Fatal Fury Special|auRr5UIb_2Y",
	"FIFA International Soccer|vwH_ieU5Aos",
	"Fifa Soccer 96|3GQ2awwpU_c",
	"Galaga '91|WEjhBzbCIic",
	"Gamble Panic|tq2uHPojFmw",
	"GG Aleste|mtTCYyXL_oE&feature=plcp",
	"GG Doraemon - Noranosuke no Yabou|NpWnlPQqSPQ",
	"GG Portrait - Pai Chen|4Qcddl8WAUk",
	"GG Portrait - Yuuki Akira|jtCNF7P0JGk",
	"GG Shinobi|0KlcleL8suw",
	"GP Rider|ts9gnl3y07A",
	"Griffin|9YyY_spmMXY",
	"Gunstar Heroes|TtBotRj8JDQ",
	"Halley Wars|4g_9Ly3S72s&feature=plcp",
	"Hook|0I8n6ci6KW4",
	"Hurricanes|QjMlgwnZPqM",
	"Jang Pung II (Unlicensed)|kxbG1iduLrE",
	"Jeopardy!|aANGr-uWdO0",
	"Jeopardy!: Sports Edition|ZyyW3WYE13w",
	"Joe Montana Football|ATjB36n0cAs",
	"Kenyuu Densetsu Yaiba|rtJ0bMhRjhU",
	"Kishin Douji Zenki|FbXk-RsuxCA",
	"Kuni-chan no Game Tengoku Part 2|t_Dl6R4PkxE",
	"Lemmings|3jbiquCYOFE",
	"Lemmings 2: The Tribes (Prototype)|SDXp8SetkUY",
	"Madou Monogatari II|p_LgWXtyukY",
	"Madou Monogatari III|0JlaIkzNTYI",
	"Magical Taruruuto-kun|-PNVDdY_LqU",
	"Mappy|NqJ2bWYws_o",
	"Marble Madness|BwjQWBx6xQE",
	"Megaman|1BEv6TwiYcs",
	"Mick & Mack as the Global Gladiators|iNhb89mfwGM",
	"Mickey's Ultimate Challenge|pw90KuJRgJc",
	"Micro Machines|IcVm0TnIA9c",
	"Micro Machines 2: Turbo Tournament|0l_eTU_pCac",
	"Mighty Morphin Power Rangers|HZciijt8mGg",
	"Mighty Morphin Power Rangers: The Movie|nU-GAwnGCRs",
	"Mortal Kombat|QKcWryFWc_s",
	"Mortal Kombat 3|8D-D-jTU09A",
	"Mortal Kombat II|67tnHzcKyOM",
	"Ms. Pac-Man|bthgJuYM6F8",
	"Ninja Gaiden|mHoPEgl85iE",
	"Ninku|E6Ysx897rrU",
	"Ninku 2: Tenkuuryuu e no Michi|GdqMAoDFOq8",
	"Out Run Europa|x8w7WU5jwuU",
	"OutRun|HmlsVz-ypko",
	"Pac-Man|OBVx8WgUyRo",
	"Panzer Dragoon Mini|n3C55fzpMwU",
	"Paperboy|hyfuxcWhUQI",
	"Paperboy II|DyxP6HH2NiQ",
	"Phantasy Star Adventures (Fan Translation)|FoAZupv6HQE",
	"Phantasy Star Gaiden (Fan Translation)|tiXtLQtPmu0",
	"Pinball Dreams|Uxtj6ZW3eIw",
	"Power Strike II|2cZs0-8zepk",
	"Primal Rage|krLU1mWISgM",
	"Prince of Persia|zFDyWSqkp5E",
	"Psychic World|1-WPEzW-ML0",
	"Rise of the Robots|1bVMt_FhubA",
	"RoboCop 3|OU7KwA-6odM",
	"Samurai Shodown|97v14F_7RxQ",
	"Samurai Spirits|QMavcOIZ15k",
	"Sassou Shounen Eiyuuden Coca-Cola Kid (Fan Translation)|YeQxYHJyt1c",
	"Shaq Fu|uoVSsEaZWs8",
	"Shining Force Gaiden II: Jashin no Kakusei|XubELcJU5CI",
	"Shining Force Gaiden: Ensei - Jashin no Kuni he|2ttK14GgFK4",
	"Shining Force Gaiden: Final Conflict (Fan Translation)|RHr_isvKMp0",
	"Shining Force II: The Sword of Hajya|c09h7z6pBUA",
	"Shinobi II - The Silent Fury|QKhtumandNo",
	"Side Pocket|Wy4TlYSt1mg",
	"Slider|TVL04b1iT_A",
	"Sonic Blast|9BldSK2IllU",
	"Sonic Chaos|_5-lLhmKqug",
	"Sonic Drift|gbfTsGuPhzU",
	"Sonic Drift 2|NZMkE1bsxwI",
	"Sonic Labyrinth|97unZ7grgSc",
	"Sonic the Hedgehog|-D00HFMfmro",
	"Sonic The Hedgehog 2|EYQhe5wskN0",
	"Sonic Triple Trouble|drcKKfWnYF8",
	"Space Harrier|69ewTAnYwk8",
	"Spider-Man: Return of the Sinister Six|JfZZkyk9w18",
	"Star Wars|06poo5MgtsQ",
	"Streets of Rage|XvyXWWdBWR0",
	"Streets of Rage II|BGwChG7GY0o",
	"Super Monaco GP|aRRZ38ZrtwM",
	"Super Space Invaders|oTsj71e2dak",
	"Super Star Wars: Return of the Jedi|20CM5W483sE",
	"Surf Ninjas|rdwzrGYKyvo",
	"T2 - The Arcade Game|LDoyKgHLqgM",
	"Tails' Adventures|W35oJcnF7qo",
	"Taito Chase H.Q.|PgxhPBvPPd8",
	"Taz-Mania: The Search for the Lost Seabirds|Oj-7hQgtOnA",
	"Tempo Jr.|HkD-twOcRuU",
	"The Berenstain Bears' Camping Adventure|AmTC0GSBRoE",
	"The Excellent Dizzy Collection|7zpP66FXr3M",
	"The Itchy & Scratchy Game|b3GX9GuuFsU",
	"The Lion King|uSCkqtVTH0k",
	"The Ottifants|0YE3PJypSKY",
	"The Simpsons: Bart vs. the Space Mutants|oc43SHm_vz4",
	"The Simpsons: Bartman Meets Radioactive Man|mpIOEVC5VLM",
	"Tintin in Tibet|SxdCgjVXGYw",
	"Tom and Jerry - The Movie|7vdtFP3Duzk",
	"Ultimate Soccer|HI1e4VIzGM0",
	"Virtua Fighter Animation|dIO3zco9Nl8",
	"VR Troopers|9H-SUfoMci4",
	"Wheel of Fortune|Z3lEhgv_kEE",
	"Wizard Pinball|Byp7nfH4T-0",
	"Wolfchild|ouL0lGAcm8k",
	"Wonder Boy - The Dragons Trap|y57T5nlqR_Q",
	"Woody Pop|04XANNuUccY",
	"World Cup Usa 94|VEu-tr_qStU",
	"Yuu Yuu Hakusho|rYeCY7u_6ko",
	"Yuu Yuu Hakusho II|20cH-5Ka0ew",
	"Zool|neGvWyEh4Pk",
}
