package main

func generateMisterLynxGames(generate bool) {
	lynxTitleAdded := make(map[string]bool)
	lynxImages := make(map[string]string)
	lynxGameList := []string{}
	compileMisterConsoleData(lynxTitleAdded, &lynxGameList, lynxImages, lynxVideos, "lynx")
	if generate {
		generateMisterConsoleHTML("Lynx Games", &lynxGameList, lynxImages, lynxVideos, "lynx")
	}
}

var lynxVideos = map[string]string{}

var lynxGameInfo = map[string]string{
	"A.P.B.":                            "https://atarigamer.com/lynx/game/APB/1513416078",
	"Awesome Golf":                      "https://atarigamer.com/lynx/game/AwesomeGolf/420322826",
	"Baseball Heroes":                   "https://atarigamer.com/lynx/game/BaseballHeroes/1999363434",
	"Basketbrawl":                       "https://atarigamer.com/lynx/game/Basketbrawl/278645002",
	"Batman Returns":                    "https://atarigamer.com/lynx/game/BatmanReturns/411617623",
	"BattleWheels":                      "https://atarigamer.com/lynx/game/BattleWheels/249599870",
	"Battlezone 2000":                   "https://atarigamer.com/lynx/game/Battlezone2000/1622914826",
	"Bill & Ted's Excellent Adventure":  "https://atarigamer.com/lynx/game/BillampTedsExcellentAdventure/1397989147",
	"Block Out":                         "https://atarigamer.com/lynx/game/BlockOut/1686572735",
	"Blue Lightning":                    "https://atarigamer.com/lynx/game/BlueLightning/1382971832",
	"California Games":                  "https://atarigamer.com/lynx/game/CaliforniaGames/625857223",
	"Checkered Flag":                    "https://atarigamer.com/lynx/game/CheckeredFlag/1034307975",
	"Chip's Challenge":                  "https://atarigamer.com/lynx/game/ChipsChallenge/2022819869",
	"Crystal Mines II":                  "https://atarigamer.com/lynx/game/CrystalMinesII/635347429",
	"Desert Strike":                     "https://atarigamer.com/lynx/game/DesertStrike/619991931",
	"Dinolympics":                       "https://atarigamer.com/lynx/game/Dinolympics/979699310",
	"Dirty Larry - Renegade Cop":        "https://atarigamer.com/lynx/game/DirtyLarryRenegadeCop/1519759294",
	"Double Dragon":                     "https://atarigamer.com/lynx/game/DoubleDragon/2041198702",
	"Dracula - The Undead":              "https://atarigamer.com/lynx/game/DraculaTheUndead/358004199",
	"Electrocop":                        "https://atarigamer.com/lynx/game/Electrocop/376582658",
	"European Soccer Challenge":         "https://atarigamer.com/lynx/game/EuropeanSoccerChallenge/1967037688",
	"Fidelity Ultimate Chess Challenge": "https://atarigamer.com/lynx/game/FidelityUltimateChessChallenge/287160750",
	"Gates of Zendocon":                 "https://atarigamer.com/lynx/game/GatesofZendocon/1628880814",
	"Gauntlet - The Third Encounter":    "https://atarigamer.com/lynx/game/GauntletTheThirdEncounter/1424091724",
	"Gordo 106":                         "https://atarigamer.com/lynx/game/Gordo106/1208819515",
	"Hard Drivin'":                      "https://atarigamer.com/lynx/game/HardDrivin/1546263734",
	"Hockey":                            "https://atarigamer.com/lynx/game/Hockey/2124334099",
	"Hydra":                             "https://atarigamer.com/lynx/game/Hydra/355953500",
	"Ishido - The Way of the Stones":    "https://atarigamer.com/lynx/game/IshidoTheWayoftheStones/428251110",
	"Jimmy Connors' Tennis":             "https://atarigamer.com/lynx/game/JimmyConnorsTennis/781957960",
	"Joust":                             "https://atarigamer.com/lynx/game/Joust/2070457013",
	"KLAX":                              "https://atarigamer.com/lynx/game/KLAX/1284965295",
	"Kung Food":                         "https://atarigamer.com/lynx/game/KungFood/519135118",
	"Lemmings":                          "https://atarigamer.com/lynx/game/Lemmings/654071298",
	"Lynx Casino":                       "https://atarigamer.com/lynx/game/LynxCasino/592741719",
	"Malibu Bikini Volleyball":          "https://atarigamer.com/lynx/game/MalibuBikiniVolleyball/604444289",
	"Ms. Pac-Man":                       "https://atarigamer.com/lynx/game/MsPacMan/1016758045",
	"NFL Football":                      "https://atarigamer.com/lynx/game/NFLFootball/2168813906",
	"Ninja Gaiden":                      "https://atarigamer.com/lynx/game/NinjaGaiden/827588241",
	"Ninja Gaiden III - The Ancient Ship of Doom": "https://atarigamer.com/lynx/game/NinjaGaidenIIITheAncientShipofDoom/1587437967",
	"Pac-Land":                          "https://atarigamer.com/lynx/game/PacLand/849005384",
	"Paperboy":                          "https://atarigamer.com/lynx/game/Paperboy/1049850191",
	"Pinball Jam":                       "https://atarigamer.com/lynx/game/PinballJam/1337434009",
	"Pit-Fighter":                       "https://atarigamer.com/lynx/game/PitFighter/1689876186",
	"Power Factor":                      "https://atarigamer.com/lynx/game/PowerFactor/1929084752",
	"Qix":                               "https://atarigamer.com/lynx/game/Qix/358975471",
	"Rampage":                           "https://atarigamer.com/lynx/game/Rampage/780287746",
	"Rampart":                           "https://atarigamer.com/lynx/game/Rampart/1158997951",
	"RoadBlasters":                      "https://atarigamer.com/lynx/game/RoadBlasters/1758123820",
	"Robo-Squash":                       "https://atarigamer.com/lynx/game/RoboSquash/31958652",
	"Robotron 2084":                     "https://atarigamer.com/lynx/game/Robotron2084/550563919",
	"Rygar":                             "https://atarigamer.com/lynx/game/Rygar/1204550012",
	"S.T.U.N. Runner":                   "https://atarigamer.com/lynx/game/STUNRunner/486488701",
	"Scrapyard Dog":                     "https://atarigamer.com/lynx/game/ScrapyardDog/257159884",
	"Shadow of the Beast":               "https://atarigamer.com/lynx/game/ShadowoftheBeast/1261224969",
	"Shanghai":                          "https://atarigamer.com/lynx/game/Shanghai/1902366290",
	"Steel Talons":                      "https://atarigamer.com/lynx/game/SteelTalons/1174986717",
	"Super Asteroids & Missile Command": "https://atarigamer.com/lynx/game/SuperAsteroidsMissileCommand/1968158458",
	"Super Off Road":                    "https://atarigamer.com/lynx/game/SuperOffRoad/215317696",
	"Super Skweek":                      "https://atarigamer.com/lynx/game/SuperSkweek/1621976337",
	"Switchblade II":                    "https://atarigamer.com/lynx/game/SwitchbladeII/2076886345",
	"Todd's Adventures in Slime World":  "https://atarigamer.com/lynx/game/ToddsAdventuresinSlimeWorld/1301381345",
	"Toki":                              "https://atarigamer.com/lynx/game/Toki/1313984342",
	"Tournament Cyberball 2072":         "https://atarigamer.com/lynx/game/TournamentCyberball2072/1667194341",
	"Turbo Sub":                         "https://atarigamer.com/lynx/game/TurboSub/752912127",
	"Viking Child":                      "https://atarigamer.com/lynx/game/VikingChild/596449372",
	"Warbirds":                          "https://atarigamer.com/lynx/game/Warbirds/586329012",
	"World Class Fussball - Soccer":     "https://atarigamer.com/lynx/game/WorldClassFussballSoccer/990173250",
	"Xenophobe":                         "https://atarigamer.com/lynx/game/Xenophobe/1367643974",
	"Xybots":                            "https://atarigamer.com/lynx/game/Xybots/329677926",
	"Zarlor Mercenary":                  "https://atarigamer.com/lynx/game/ZarlorMercenary/1243783599",
}
