package main

func generateMisterNESGames() {
	nesTitleAdded := make(map[string]bool)
	nesImages := make(map[string]string)
	nesGameList := []string{}
	compileMisterConsoleData(nesTitleAdded, &nesGameList, nesImages, "nes")
	generateMisterConsoleHTML("NES Games", &nesGameList, nesImages, nesVideos, "nes")
}

var nesVideos = map[string]string{
	"10-Yard Fight":                 "5LUyTv9j1TM",
	"1942":                          "bupAR6Rbn3I",
	"1943 - The Battle of Midway":   "sBV5PaRfrSo",
	"3-D WorldRunner":               "",
	"4 Nin Uchi Mahjong":            "",
	"720 Degrees":                   "",
	"8 Eyes":                        "Bu65YKM9BRE",
	"Abadox - The Deadly Inner War": "lEpiGnTSuTE",
	"Abadox":                        "",
	"Abarenbou Tengu":               "pCtALFe6h4k",
	"Action in New York":            "dRTvMeMggsw",
	"Addams Family, The - Pugsley's Scavenger Hunt":       "s_ZgSzOvhnA",
	"Addams Family, The - Uncle Fester's Quest":           "",
	"Addams Family, The":                                  "S8FjRU3QdRE",
	"Advanced Dungeons & Dragons - DragonStrike":          "",
	"Advanced Dungeons & Dragons - Heroes of the Lance":   "",
	"Advanced Dungeons & Dragons - Hillsfar":              "",
	"Advanced Dungeons & Dragons - Pool of Radiance":      "",
	"Adventure Island 3":                                  "",
	"Adventure Island II":                                 "",
	"Adventures in the Magic Kingdom":                     "UZ3H_wcDQpY",
	"Adventures of Bayou Billy, The":                      "CUZcbojyLBs",
	"Adventures of Dino Riki":                             "j_SbnwBD9U4",
	"Adventures of Dr. Franken, The":                      "",
	"Adventures of Gilligan's Island, The":                "Ilsx3wm1nVY",
	"Adventures of Lolo 2":                                "",
	"Adventures of Lolo 3":                                "",
	"Adventures of Lolo":                                  "xUU4Jfj9Gjs",
	"Adventures of Rad Gravity, The":                      "",
	"Adventures of Rocky and Bullwinkle and Friends, The": "",
	"Adventures of Tom Sawyer":                            "uYiJM1MKCiI",
	"After Burner":                                        "",
	"Air Fortress":                                        "bPyf_mU0j0g",
	"Airwolf":                                             "3JEAeUXg4Zo",
	"Akagawa Jirou no Yuurei Ressha":                      "jSnE7SkWLgI",
	"Akumajou Densetsu":                                   "T3jsG0o9NJs",
	"Akumajou Dracula":                                    "MSUsE2dBMmk",
	"Al Unser Jr. Turbo Racing":                           "",
	"Alfred Chicken":                                      "H7epJ1Eucok",
	"Alien 3":                                             "LrzxhBQoYBA",
	"Alien Syndrome":                                      "vfnFlKPh5zw",
	"All-Pro Basketball":                                  "lmxDuLb1C2U",
	"Alpha Mission":                                       "pEDFMMEZw5Q",
	"Amagon":                                              "M0qCwvjv87s",
	"America Daitouryou Senkyo":                           "fsfyMIUVLOI",
	"American Gladiators":                                 "ZVSnWCw0F9M",
	"Anticipation":                                        "yxbhxes6k7g",
	"Arch Rivals - A Basketbrawl!":                        "",
	"Archon":                                              "1aJYm4mJZSg",
	"Arctic":                                              "",
	"Argus":                                               "OTLp349Xppw",
	"Arkanoid II":                                         "",
	"Arkanoid":                                            "",
	"Arkista's Ring":                                      "TC-gurG8dvA",
	"Asmik-kun Land":                                      "",
	"Asterix":                                             "cbZveRmHbyE",
	"Astro Fang - Super Machine":                          "K0uLrXDfxq4",
	"Astro Robo Sasa":                                     "X0JEvuu-U2s",
	"Astyanax":                                            "Yt2CU8H7BMI",
	"Athena":                                              "yD9rNhafCFA",
	"Athletic World":                                      "",
	"Atlantis no Nazo":                                    "",
	"Attack of the Killer Tomatoes":                       "aKBRZKlsqBY",
	"AV Soccer":                                           "",
	"Babel no Tou":                                        "",
	"Back to the Future Part II & III":                    "",
	"Back to the Future":                                  "Ed_qGl34kV0",
	"Bad Dudes vs. Dragon Ninja":                          "kn10_ZZBQa4",
	"Bad Dudes":                                           "GcrVMS83-3U",
	"Bad News Baseball":                                   "Gvw27FvxtE8",
	"Bad Street Brawler":                                  "lTvEQU5Z4Qk",
	"Baken Hisshou Gaku - Gate In":                        "OjSXb-sYj9o",
	"Balloon Fight":                                       "mtrW_WcO0_8",
	"Baltron":                                             "b-B7wnwUyTI",
	"Banana":                                              "",
	"Bandai Golf - Challenge Pebble Beach":                "m2usf2t5yx4",
	"Bandit Kings of Ancient China":                       "",
	"Barbie":                                              "AJ8PfrWNymI",
	"Bard's Tale, The":                                    "",
	"Barker Bill's Trick Shooting":                        "",
	"Baseball Simulator 1.000":                            "",
	"Baseball Stars II":                                   "",
	"Baseball Stars":                                      "",
	"Baseball":                                            "Abv3xQ6-mVk",
	"Bases Loaded 3":                                      "",
	"Bases Loaded 4":                                      "",
	"Bases Loaded II - Second Season":                     "",
	"Bases Loaded":                                        "",
	"Bashi Bazook - Morphoid Masher":                      "",
	"Batman - Return of the Joker":                        "p1Ivxnpbd5Y",
	"Batman - The Video Game":                             "",
	"Batman Returns":                                      "v0IcqoI0d78",
	"Batman":                                              "Qr0RSz-HPIw",
	"Battle Chess":                                        "",
	"Battle City":                                         "DfixqYPonHw",
	"Battle Formula":                                      "_GcLjrlAz5M",
	"Battle of Olympus, The":                              "Tosc0LAeR18",
	"Battleship":                                          "",
	"Battletank":                                          "",
	"Battletoads-Double Dragon":                           "",
	"Battletoads":                                         "QLxXmnqaJtw",
	"Beetlejuice":                                         "CSOAR9NhqlU",
	"Best of the Best - Championship Karate":              "K-hlPkbrV8M",
	"Bible Buffet":                                        "d8xAy3RBbdo",
	"Bigfoot":                                             "dS5uPWqX7R0",
	"Bill & Ted's Excellent Video Game Adventure":         "NFH4QUxxoGw",
	"Bill Elliott's NASCAR Challenge":                     "",
	"Binary Land":                                         "0GQM8KBIN_8",
	"Bio Miracle Bokutte Upa":                             "BC3FyEYaAUQ",
	"Bio Senshi Dan - Increaser Tono Tatakai":             "VSGnn_w69H0",
	"Bionic Commando":                                     "0DdCulJ5uc4",
	"Black Bass, The":                                     "",
	"Blades of Steel":                                     "j7EWeC2Mk6c",
	"Blaster Master":                                      "2STUx_9bkB4",
	"Blue Marlin, The":                                    "eW8HD2Q1czs",
	"Blue Shadow":                                         "BVrcX6Zpg7I",
	"Blues Brothers, The":                                 "",
	"Bo Jackson Baseball":                                 "",
	"Bomberman II":                                        "",
	"Bomberman":                                           "",
	"Bonk's Adventure":                                    "yu7U-74ZfOg",
	"Booby Kids":                                          "vBRKZR79ngA",
	"Boulder Dash":                                        "mLQzL8vsNVM",
	"Boy and His Blob, A - Trouble on Blobolonia":         "",
	"Bram Stoker's Dracula":                               "B5blfI0BXv0",
	"Break Time - The National Pool Tour":                 "pOVEOSkDSPQ",
	"BreakThru":                                           "RK0PLx2Ucrc",
	"Bubble Bobble 2":                                     "",
	"Bubble Bobble Part 2":                                "rJhOtKJ-S_U",
	"Bubble Bobble":                                       "ij3f4_APEow",
	"Bucky O'Hare":                                        "dWHPNnrTmKs",
	"Bugs Bunny Birthday Bash":                            "",
	"Bugs Bunny Birthday Blowout, The":                    "M-fNNpt0oAk",
	"Bugs Bunny Crazy Castle, The":                        "lC7FFkgtKkQ",
	"Bugs Bunny Fun House":                                "",
	"Bump'n'Jump":                                         "IAPXIJhyevM",
	"Burai Fighter":                                       "mCC1_pEPf14",
	"BurgerTime":                                          "TcPXTwXKkSE",
	"Cabal":                                               "0Hnf2D9Aelg",
	"Caesars Palace":                                      "xtQowKzRjOA",
	"California Games":                                    "ZyNsXWJBB2k",
	"California Raisins - The Grape Escape":               "",
	"Capcom's Gold Medal Challenge '92":                   "iwfKWIfg_Ho",
	"Captain America and the Avengers":                    "",
	"Captain Comic - The Adventure":                       "utj-2bnbv_s",
	"Captain Planet and the Planeteers":                   "efxMbwL9z4I",
	"Captain Saver":                                       "HFXkxgp1DOg",
	"Captain Silver":                                      "_ZeZQqgXSNw",
	"Captain Skyhawk":                                     "W92dgGrm2zs",
	"Casino Kid II":                                       "JZRsF_Ddo7o",
	"Casino Kid":                                          "yqxfwV_At84",
	"Castelian":                                           "YWN7znU09O4",
	"Castle of Dragon":                                    "cOAVmOMXl0g",
	"Castle Quest":                                        "",
	"Castlequest":                                         "",
	"Castlevania II - Simon's Quest":                      "CYf1fJIWYuY",
	"Castlevania III - Dracula's Curse":                   "hFFKAl2A898",
	"Castlevania":                                         "lRcHk8ixyKE",
	"Caveman Games":                                       "jxJ1Uw38Hss",
	"Chack'n Pop":                                         "qOUWA3W3EFA",
	"Challenger":                                          "Ec_-q4Kyme4",
	"Championship Bowling":                                "CsfH84qinNc",
	"Championship Pool":                                   "sKhtIJyQZrg",
	"Chaos World":                                         "",
	"Chessmaster, The":                                    "",
	"Chiki Chiki Machine Mou Race":                        "iMC3kcrynw0",
	"Chip 'n Dale Rescue Rangers 2":                       "XGwGoKAvvxo",
	"Chip 'n Dale Rescue Rangers":                         "oGd82QUon8M",
	"Chip to Dale no Daisakusen 2":                        "z7EAg0ErSGg",
	"Chip to Dale no Daisakusen":                          "oGqTIRsEDl8",
	"Chiyonofuji no Ooichou":                              "zUW3tYs7Nbg",
	"Choplifter":                                          "CxI5tom2xCA",
	"Chou-Wakusei Senki - MetaFight":                      "2HlxFZMEvl4",
	"Choujikuu Yousai - Macross":                          "XZoQ7eEatnc",
	"Choujin Ookami Senki - Warwolf":                      "tmeA12zfbEo",
	"Choujin Sentai - Jetman":                             "hlwq8CPut04",
	"Chris Evert & Ivan Lendl in Top Players' Tennis": "",
	"Chubby Cherub":                         "bbPUycxOUXo",
	"Chuuka Taisen":                         "jSC7OwMsaUU",
	"Circus Caper":                          "ABhiSHe5ayg",
	"City Connection":                       "",
	"Clash at Demonhead":                    "d8DcGDVn8jM",
	"Classic Concentration":                 "XKaunu6OXfE",
	"Cliffhanger":                           "00-8WnZLejA",
	"Clu Clu Land":                          "",
	"Cobra Command":                         "oywk1yf1Tm0",
	"Cobra Triangle":                        "grKL3u4-F0w",
	"Cocoron":                               "I548U59HoTc",
	"Code Name - Viper":                     "-puOsVwsSkY",
	"Color a Dinosaur":                      "",
	"Commando":                              "KNkcmePZ3d0",
	"Conan":                                 "",
	"Conflict":                              "",
	"Conquest of the Crystal Palace":        "sLYhJlolrOM",
	"Contra Force":                          "_UrECk3PoLY",
	"Contra":                                "qXcVojj2GXk",
	"Cool World":                            "hiEEFMSCaIE",
	"Corvette ZR-1 Challenge":               "xykvROTZJNk",
	"Cosmo Police Galivan":                  "zK6j-S4o9to",
	"Cowboy Kid":                            "VjK1NeWOhMc",
	"Crackout":                              "",
	"Crash 'n' the Boys - Street Challenge": "-NDOU9pc3B4",
	"Crayon Shin-chan - Ora to Poi Poi":     "vkLCYgTy8KQ",
	"Crazy Climber":                         "",
	"Creatom":                               "",
	"Crisis Force":                          "3cl2yizTrgQ",
	"Cross Fire":                            "j6fYFsn8cgA",
	"Crystalis":                             "LF9HeIsELLs",
	"Cyber Stadium Series - Base Wars":      "",
	"Cyberball":                             "",
	"Cybernoid - The Fighting Machine":      "pHTTkARdF6U",
	"Cycle Race - Road Man":                 "",
	"Daiku no Gen-san 2 - Akage no Dan no Gyakushuu": "K1Sz2-umBIQ",
	"Daiku no Gen-san":                      "ENUu_6s_mQ8",
	"Dance Aerobics":                        "",
	"Danny Sullivan's Indy Heat":            "NvEORvQD87c",
	"Darkman":                               "CJwqckuCn8M",
	"Darkwing Duck":                         "0NEZxg0ylwY",
	"Dash Galaxy in the Alien Asylum":       "IQUX7kBUjYU",
	"Dash Yarou":                            "",
	"Datsugoku":                             "ux_kIal8Dj8",
	"Day Dreamin' Davey":                    "",
	"Days of Thunder":                       "XxNf4nlQzSU",
	"Deadly Towers":                         "Q10_Qgm8TiQ",
	"Deblock":                               "IaWxjrlne3w",
	"Defender II":                           "yvvAlr-jhBY",
	"Defender of the Crown":                 "z5fLV9u2tCM",
	"Defenders of Dynatron City":            "",
	"Deja Vu":                               "OwGVtYwWZs8",
	"Demon Sword - Release the Power":       "",
	"Desert Commander":                      "",
	"Destination Earthstar":                 "",
	"Destiny of an Emperor":                 "HMEDr7Wo9vE",
	"Devil World":                           "pvxiXETDTyg",
	"Dick Tracy":                            "OlrSTgkLQh0",
	"Die Hard":                              "7ftIeAw9iak",
	"Dig Dug II - Trouble in Paradise":      "",
	"Dig Dug II":                            "RoRoivL0fyw",
	"Dig Dug":                               "edE61iy1SJQ",
	"Digger - The Legend of the Lost City":  "",
	"Dirty Harry":                           "ugg-7Fd9yT4",
	"Don Doko Don 2":                        "",
	"Don Doko Don":                          "",
	"Donkey Kong 3":                         "sVJE4czZF0I",
	"Donkey Kong Classics":                  "",
	"Donkey Kong Jr. Math":                  "D6cE50TdP48",
	"Donkey Kong Jr.":                       "mpO562WRLCg",
	"Donkey Kong":                           "C_PrG8P5W8o",
	"Door Door":                             "",
	"Double Dare":                           "U2eEweQhKbM",
	"Double Dragon II - The Revenge":        "",
	"Double Dragon III - The Sacred Stones": "",
	"Double Dragon":                         "VMJXZm21faY",
	"Double Dribble":                        "gw7poSD0adg",
	"Dough Boy":                             "",
	"Dr. Chaos":                             "",
	"Dr. Jekyll and Mr. Hyde":               "BrX_r68VUzQ",
	"Dr. Mario":                             "IHXdtKEHDNU",
	"Drac's Night Out":                      "",
	"Dragon Fighter":                        "_Hxx5IDtUyU",
	"Dragon Ninja":                          "NQeXPHYYktQ",
	"Dragon Power":                          "",
	"Dragon Spirit - The New Legend":        "",
	"Dragon Warrior II":                     "d4NsE4tpb6k",
	"Dragon Warrior III":                    "g3he_rH_JQo",
	"Dragon Warrior IV":                     "I2iWoXNK5VQ",
	"Dragon Warrior":                        "jmzHrNVelL0",
	"Dragon Wars":                           "",
	"Dragon's Lair":                         "Z1GOgdJbJcs",
	"Duck Hunt":                             "jBDNsaWiT8Q",
	"Duck Maze":                             "",
	"DuckTales 2":                           "duVLzMBYh_s",
	"DuckTales":                             "zYuqB2BPkz4",
	"Dungeon Magic - Sword of the Elements": "",
	"Dusty Diamond's All-Star Softball":     "qdBGRLARqTI",
	"Dynowarz - Destruction of Spondylus":   "k8c3O-7ruHc",
	"Earth Bound":                           "",
	"Elevator Action":                       "MdFBiauF7w4",
	"Eliminator Boat Duel":                  "NM7ZNX0GUBI",
	"Elysion":                               "",
	"Empereur, L'":                          "",
	"Excitebike":                            "fRgMCtaWoSU",
	"Exed Exes":                             "",
	"Exerion":                               "YPRiwD11-OU",
	"F-1 Race":                              "kh5kOT5gcU0",
	"F-117A - Stealth Fighter":              "",
	"F-15 Strike Eagle":                     "",
	"Famicom Igo Nyuumon":                   "2gnl-VNUDuc",
	"Family Circuit '91":                    "",
	"Family Circuit":                        "",
	"Family Feud":                           "OM_6tY7Hhfk",
	"Family Jockey":                         "I5yZ_k2aDZQ",
	"Faria - A World of Mystery & Danger!":  "-S4WyyNtKW0",
	"Faria":                                 "",
	"Faxanadu":                              "HutD8ZXZucY",
	"Felix the Cat":                         "jNv9-beLNGU",
	"Ferrari Grand Prix Challenge":          "",
	"Fester's Quest":                        "SrElD5f3GCE",
	"Final Combat":                          "hBt3U56C4xg",
	"Final Fantasy II":                      "",
	"Final Fantasy III":                     "",
	"Final Fantasy":                         "fTdlzqhSdt8",
	"Final Mission":                         "9mBexyEiuLs",
	"Fire 'n Ice":                           "r7zvp9qRY0M",
	"Fire Hawk":                             "Lga_5wU8jsk",
	"Fisher-Price - Firehouse Rescue":       "wkgdymVwf7U",
	"Fisher-Price - I Can Remember":         "zBVBEGr1PRs",
	"Fisher-Price - Perfect Fit":            "",
	"Fist of the North Star":                "HxRvfe0wOWo",
	"Flight of the Intruder":                "",
	"Flintstones, The - The Rescue of Dino & Hoppy":               "nFcbSjmzm5M",
	"Flintstones, The - The Surprise at Dinosaur Peak!":           "lDATMqD9XZ8",
	"Flipull - An Exciting Cube Game":                             "6nZCd7OeSnA",
	"Flying Dragon - The Secret Scroll":                           "ByY88RLUBDY",
	"Flying Hero":                                                 "",
	"Flying Warriors":                                             "",
	"Formation Z":                                                 "LCWBrzERxj8",
	"Formula One - Built to Win":                                  "",
	"Fox's Peter Pan & the Pirates - The Revenge of Captain Hook": "",
	"Frankenstein - The Monster Returns":                          "",
	"Free Fall":                                                   "-x5jfdK71Cw",
	"Freedom Force":                                               "kD9oYi7kT9g",
	"Friday the 13th":                                             "qIK0-ndNpdw",
	"Front Line":                                                  "nq0bdhxrcjo",
	"Fun House":                                                   "HskqyKzrT-g",
	"G.I. Joe - A Real American Hero - The Atlantis Factor":       "FUtcMc5nH34",
	"G.I. Joe - A Real American Hero":                             "n9LbzPEyitA",
	"G.I. Joe - The Atlantis Factor":                              "",
	"Galaga - Demons of Death":                                    "UPcO0HvIhkA",
	"Galaga":                                                      "",
	"Galaxy 5000":                                                 "",
	"Ganso Saiyuuki - Super Monkey Daibouken":                     "7ox9KtuWG_w",
	"Garfield - A Week of Garfield":                               "",
	"Gargoyle's Quest II":                                         "chUNONy84y8",
	"Gauntlet II":                                                 "",
	"Gauntlet":                                                    "",
	"Gegege no Kitarou - Youkai Daimakyou":                        "",
	"Geimos":                                                      "0VkT639__Tk",
	"Gekitou Pro Wrestling!! - Toukon Densetsu":                   "waghhwQ0Wxw",
	"Gemfire":                                                     "Q5euIIg8A_E",
	"Genghis Khan":                                                "",
	"George Foreman's KO Boxing":                                  "",
	"Ghost'n Goblins":                                             "5ZgqugtReso",
	"Ghostbusters II":                                             "tmDyswPlWE0",
	"Ghostbusters":                                                "Yy4yKNqKVos",
	"Ghosts'n Goblins":                                            "5ZgqugtReso",
	"Ghoul School":                                                "pDOz3kyAbTc",
	"Goal! Two":                                                   "",
	"Goal!!":                                                      "",
	"Goal!":                                                       "BmWjZbHjUgg",
	"Godzilla - Monster of Monsters!":                             "",
	"Godzilla 2 - War of the Monsters":                            "",
	"Golf Grand Slam":                                             "8zSe9wwd544",
	"Golf Ko Open":                                                "e4F_zfIoqMw",
	"Golf":                                                        "BmWjZbHjUgg",
	"Golgo 13 - Top Secret Episode":                               "qMuDiI9X8q4",
	"Goonies II, The":                                             "Ck_k7UixOFg",
	"Gotcha! - The Sport!":                                        "L9EFEOrTLFs",
	"Gradius II":                                                  "Dwxi83a7luQ",
	"Gradius":                                                     "xKnT_XQsFyU",
	"Great Battle Cyber":                                          "c4DS-8IRLls",
	"Great Deal":                                                  "FJA5dZ0TLpU",
	"Great Tank":                                                  "FORzI-fLYWY",
	"Great Waldo Search, The":                                     "DJKXQthaVz8",
	"Greg Norman's Golf Power":                                    "",
	"Gremlin 2 - Shinshu Tanjou":                                  "LirVuSb31QQ",
	"Gremlins 2 - The New Batch":                                  "icENfY8fHQQ",
	"Guardian Legend, The":                                        "ImwZBSo8Rvo",
	"Guerrilla War":                                               "s5CtC5Tg4bc",
	"Guevara":                                                     "nMEYgNXSvgE",
	"Gumshoe":                                                     "",
	"Gun Hed":                                                     "",
	"Gun Nac":                                                     "KYF22YbDEZM",
	"Gun-Dec":                                                     "9EQ-qVCjq40",
	"Gun.Smoke":                                                   "Rx9APVvCdZg",
	"Gyrodine":                                                    "N8fEi-fxTMQ",
	"Gyromite":                                                    "",
	"Gyruss":                                                      "bNqmS2MHKsw",
	"Hammerin' Harry":                                             "7yXwyJR0zCM",
	"Harlem Globetrotters":                                        "KoypV1N8SRQ",
	"Hatris":                                                      "4A8OLEjFW_o",
	"Heavy Barrel":                                                "V5T6HW-BKQ0",
	"Heavy Shreddin'":                                             "zAx5QDEJth0",
	"Hector 87":                                                   "9CYTF6uO_6Q",
	"Hello Kitty no Ohanabatake":                                  "vmkhOaCCu3c",
	"Hello Kitty World":                                           "nMBaRF2NpzE",
	"Hero Quest":                                                  "",
	"High Speed":                                                  "_r9tvhuVqLk",
	"Hirake! Ponkikki":                                            "Llbeeltf9Gg",
	"Hiryuu no Ken Special - Fighting Wars":                       "O4SLD-ZX40c",
	"Hit the Ice - VHL the Video Hockey League": "",
	"Hogan's Alley":                    "3RZdbIvW3LI",
	"Hollywood Squares":                "_TU0mUu14kU",
	"Holy Diver":                       "_qs3e9k3dWc",
	"Home Alone 2 - Lost in New York":  "cqsCqG-uako",
	"Home Alone":                       "w5wK3VbAv6c",
	"Hook":                             "oZ2cIsqAk_o",
	"Hoops":                            "",
	"Hottarman no Chitei Tanken":       "ecLxVVTyNRM",
	"Houma ga Toki":                    "aj5traANuFc",
	"Hudson Hawk":                      "lmNbebgxc9k",
	"Hudson's Adventure Island":        "Ly734lgeIAs",
	"Hunt for Red October, The":        "RF4a3zeL4Xo",
	"Hydlide":                          "LgFtO1FCSko",
	"Ice Climber":                      "3YGJLbasFDg",
	"Ice Hockey":                       "cteXv68JXd4",
	"Idol Hakkenden":                   "-rCRQZU-q7c",
	"Ikari III - The Rescue":           "GIAZhwxIJKs",
	"Ikari Warriors II - Victory Road": "",
	"Ikari Warriors":                   "",
	"Ikari":                            "DN_YfjtzFC8",
	"Ike Ike! Nekketsu Hockey-bu - Subette Koronde Dairantou": "XYWFKc0H6ps",
	"Ikki":                                    "DN_YfjtzFC8",
	"Image Fight":                             "fOc665FGVu8",
	"Immortal, The":                           "QY3QEyyc23k",
	"Incredible Crash Dummies, The":           "Uf9neTsUjrI",
	"Indiana Jones and the Last Crusade":      "",
	"Indiana Jones and the Temple of Doom":    "",
	"Infiltrator":                             "",
	"Insector X":                              "E_EDgM_4Zj",
	"Iron Tank - The Invasion of Normandy":    "",
	"IronSword - Wizards & Warriors II":       "p80BHp3qfAs",
	"Isolated Warrior":                        "1tv1BFHpi_M",
	"Ivan 'Ironman' Stewart's Super Off Road": "nMEg-xMxCXk",
	"Jack Nicklaus' Greatest 18 Holes of Major Championship Golf": "",
	"Jackal":                             "cgGwem324Iw",
	"Jackie Chan's Action Kung Fu":       "2vK9C5nQcGU",
	"James Bond Jr":                      "",
	"Jaws":                               "BpfmzUNS2xM",
	"Jeopardy! 25th Anniversary Edition": "i36pNWlWptM",
	"Jeopardy! Junior Edition":           "RBG6AxVNbzE",
	"Jeopardy!":                          "gUCuyyTKZzU",
	"Jetsons, The - Cogswell's Caper":    "qyu-u8ZhUYM",
	"Jimmy Connors Tennis":               "",
	"Joe & Mac":                          "ll8AmxhIhRY",
	"John Elway's Quarterback":           "",
	"Jordan vs Bird - One On One":        "",
	"Journey to Silius":                  "5_Ztsa5mzA0",
	"Joust":                              "7nj8NqsPEec",
	"JuJu Densetsu":                      "",
	"Jumpin' Kid - Jack to Mame no Ki Monogatari": "lDdCP6xaxFE",
	"Jungle Book, The":                            "ff3fjUCCVac",
	"Jurassic Park":                               "-M8u9iKYlLA",
	"Juuouki":                                     "uTFT9ANksm4",
	"Kabuki - Quantum Fighter":                    "SopEVWVkGkg",
	"Kage no Densetsu":                            "oWEmi8fGUWY",
	"Kage":                                        "gNORRP5J2DI",
	"Kagerou Densetsu":                            "oWEmi8fGUWY",
	"Kaiketsu Yancha Maru":                        "Wk5w5zjHT5Y",
	"Kame no Ongaeshi - Urashima Densetsu":        "",
	"Karate Champ":                                "",
	"Karate Kid, The":                             "ym8XIP4jUgI",
	"Karateka":                                    "RJoHgELbO5s",
	"Karnov":                                      "rsaIJOH89-c",
	"Kick Master":                                 "-Ihf-9FrRyU",
	"Kickle Cubicle":                              "XEI1TMrX0cY",
	"Kid Icarus":                                  "dz8L-_MpzSM",
	"Kid Klown in Night Mayor World":              "ejmfHzyGBHE",
	"Kid Kool and the Quest for the Seven Wonder Herbs":  "ihYzm5GywJk",
	"Kid Niki - Radical Ninja":                           "",
	"King's Knight":                                      "",
	"King's Quest V":                                     "PxuFAw7Sp4g",
	"Kings of the Beach - Professional Beach Volleyball": "",
	"Kirby's Adventure":                                  "rJXM4EPbPe0",
	"Kiwi Kraze - A Bird-Brained Adventure!":             "EQjXPt8VZGE",
	"Klash Ball":                                         "",
	"Klax":                                               "",
	"Knight Rider":                                       "Omx1Yhqm0l0",
	"Konamic Sports in Seoul":                            "",
	"Krion Conquest, The":                                "5fVfqjHkwog",
	"Krusty's Fun House":                                 "",
	"Kung Fu":                                            "B-gyVEqS1Ts",
	"Kung-Fu Heroes":                                     "O9fRJT61i7c",
	"Kyoro-chan Land":                                    "EZLBpMMlTiM",
	"Kyuukyoku Tiger":                                    "pqaleMnK9ik",
	"Laser Invasion":                                     "bGVB2-HNgys",
	"Last Action Hero":                                   "QxxHG5FFZd4",
	"Last Ninja, The":                                    "uVVXU5TrWrU",
	"Last Starfighter, The":                              "",
	"Law of the West":                                    "hFMcvOpPuy8",
	"Layla":                                              "Lyk66JUjZVA",
	"Lee Trevino's Fighting Golf":                        "",
	"Legacy of the Wizard":                               "",
	"Legend of Kage, The":                                "znQzUQ-dwqw",
	"Legend of Prince Valiant, The":                      "bAnd3hYjL-g",
	"Legend of Robin Hood, The":                          "",
	"Legend of the Ghost Lion":                           "",
	"Legend of Zelda, The":                               "",
	"Legendary Wings":                                    "NK5bgoafKzc",
	"Legends of the Diamond - The Baseball Championship Game": "",
	"Lemmings":       "ogCdw8be4ms",
	"Lethal Weapon":  "qJ6OHxglS10",
	"Life Force":     "lgfTC3UVCVs",
	"Lion King, The": "cXHwyjcNVR0",
	"Little League Baseball - Championship Series": "",
	"Little Mermaid, The":                          "TARFkP6eVUM",
	"Little Nemo - The Dream Master":               "wI9yf0NM61Q",
	"Little Ninja Brothers":                        "",
	"Little Samson":                                "V1FRUkrXOzI",
	"Lode Runner":                                  "",
	"Lone Ranger, The":                             "dLojAsy41wM",
	"Loopz":                                        "",
	"Lord of King, The":                            "r53LM0QVbdM",
	"Low G Man - The Low Gravity Man":              "",
	"Lunar Pool":                                   "2o-KQIfRuD0",
	"M.C. Kids":                                    "",
	"M.U.L.E.":                                     "O7TDXJmS0hE",
	"M.U.S.C.L.E. - Tag Team Match":                "",
	"Mach Rider":                                   "",
	"Mad City":                                     "3MQyFNGrs5w",
	"Mad Max":                                      "2t_tyv4g-2M",
	"Mafat Conspiracy, The":                        "",
	"Magic Darts":                                  "VC3VdEiyu_E",
	"Magic John":                                   "FuLexyJsHkk",
	"Magic Johnson's Fast Break":                   "",
	"Magic of Scheherazade, The":                   "SvBRURRas58",
	"Magical Doropie":                              "BM70xBk0Nlg",
	"Magician":                                     "",
	"Magmax":                                       "F4c5Dvg5jyw",
	"Mahjong":                                      "",
	"Mahou no Princess Minky Momo - Remember Dream": "",
	"Major League Baseball":                         "",
	"Makai Island":                                  "",
	"Maniac Mansion":                                "9EU0Ml28keg",
	"Mappy-Land":                                    "",
	"Mappy":                                         "vcxSf1cEL6M",
	"Marble Madness":                                "CvlbZwoWMgA",
	"Mario Bros.":                                   "WFptXdODy7k",
	"Mario Is Missing!":                             "FsT1blcKXIw",
	"Mario's Time Machine":                          "UHgAoTzsF0g",
	"Master Chu and the Drunkard Hu":                "QV-JWnlPMhk",
	"Max Warrior - Wakusei Kaigenrei":               "2hY4UmaAq7U",
	"Mechanized Attack":                             "",
	"Mega Man 2":                                    "KvkHhpz2FrY",
	"Mega Man 3":                                    "3apcIT1rGzE",
	"Mega Man 4":                                    "Z8v_aLnf9Iw",
	"Mega Man 5":                                    "tO6ZBTpxxCs",
	"Mega Man 6":                                    "STlxjFnKh-o",
	"Mega Man":                                      "2sKcjUjbPr4",
	"Mendel Palace":                                 "9lZinQ9940M",
	"Metal Gear":                                    "NJPVTylzt80",
	"Metal Max":                                     "",
	"Metal Mech - Man & Machine":                    "",
	"Metal Storm":                                   "D_xGOAnpCqQ",
	"Metroid":                                       "JuNygTLHlm0",
	"Michael Andretti's World GP":                   "",
	"Mickey Mouse - Dream Balloon":                  "",
	"Mickey Mousecapade":                            "VQcIYr8LaYc",
	"Mickey's Adventure in Numberland":              "hgC8DQ-oR3s",
	"Mickey's Safari in Letterland":                 "fbOPAe6Y9Nk",
	"Might & Magic - Secret of the Inner Sanctum":    "",
	"Mighty Bomb Jack":                               "",
	"Mighty Final Fight":                             "hoUPvwCcUo8",
	"Mike Tyson's Punch-Out!!":                       "rcJneBFV9cI",
	"Millipede":                                      "5JdTOo4FGOw",
	"Milon's Secret Castle":                          "CeG5i95291A",
	"Mindseeker":                                     "PzmuE_g8rNA",
	"Miracle Piano Teaching System, The":             "",
	"Mission Impossible":                             "uiWoqvYi6rk",
	"Mississippi Satsujin Jiken":                     "LBs_hx0XKwE",
	"Moero TwinBee - Cinnamon Hakase o Sukue!":       "4nJWxdsOMT0",
	"Monopoly":                                       "uoOALJ493CE",
	"Monster in My Pocket":                           "4nxBLapcvgw",
	"Monster Party":                                  "RFkTCoeJNMs",
	"Monster Truck Rally":                            "bb-H_37od4g",
	"Moon Crystal":                                   "G0Hkpc0h_gw",
	"Mother":                                         "",
	"Motor City Patrol":                              "",
	"Mr. Gimmick":                                    "O71__ki3rYw",
	"Ms. Pac-Man":                                    "807P-DT7AZ4",
	"Muppet Adventure - Chaos at the Carnival":       "",
	"Musashi no Ken - Tadaima Shugyou Chuu":          "UBLezoJrtQM",
	"Mutant Virus, The - Crisis in a Computer World": "",
	"Mystery Quest":                                  "",
	"NARC":                                           "x71fBAyd24g",
	"Nekketsu Kouha Kunio-kun":                       "J3nJI_oFuqY",
	"Nekketsu! Street Basket - Ganbare Dunk Heroes":  "P1JMdEG87Wk",
	"NES Open Tournament Golf":                       "",
	"NES Play Action Football":                       "",
	"New Ghostbusters II":                            "d-cUerYSkyg",
	"New York Nyankies":                              "S4tVIN0hDMk",
	"NFL":                                            "KhguepuCjH8",
	"Nigel Mansell's World Championship Challenge":   "",
	"Nightmare on Elm Street, A":                     "O_N7Q4R4crw",
	"Nightshade":                                     "IjyKk4lQC3k",
	"Ningen Heiki - Dead Fox":                        "OTL0goPBwyA",
	"Ninja Cop Saizou":                               "AvYs3ubttkE",
	"Ninja Crusaders - Ryuuga":                       "0AuH983XaJo",
	"Ninja Crusaders":                                "UGbVUiVzpPE",
	"Ninja Gaiden - Episode II - The Dark Sword of Chaos": "",
	"Ninja Gaiden II - The Dark Sword of Chaos":           "Rzb4Tonx0WI",
	"Ninja Gaiden III - The Ancient Ship of Doom":         "8--QVBfkY-s",
	"Ninja Gaiden":                      "DIcOjUaf5P8",
	"Ninja Jajamaru-kun":                "9dPhNd2oevs",
	"Ninja Kid":                         "",
	"Ninja Ryuuken Den":                 "ulG9YWzSlio",
	"Nintendo World Championships 1990": "RSGYz08Fzgw",
	"Nintendo World Class Service - Control Deck Test Cartridge": "",
	"Nintendo World Class Service - Joystick Test Cartridge":     "",
	"Nintendo World Class Service - Port Test Cartridge":         "",
	"Nintendo World Class Service - Power Pad Test Cartridge":    "",
	"Nintendo World Cup":                       "mPKoHVO5g3o",
	"Noah's Ark":                               "",
	"Nobunaga's Ambition II":                   "",
	"Nobunaga's Ambition":                      "",
	"North & South":                            "UJ_a6evZ-ZQ",
	"North and South":                          "UJ_a6evZ-ZQ",
	"Nuts & Milk":                              "SosPvc-U7Eg",
	"Oeka Kids - Anpanman no Hiragana Daisuki": "",
	"Oeka Kids - Anpanman to Oekaki Shiyou!!":  "",
	"Onyanko Town":                             "",
	"Operation Wolf":                           "H-0WGRf1gEw",
	"Orb 3D":                                   "",
	"Othello":                                  "",
	"Over Horizon":                             "5Q9cNdHDuY0",
	"Overlord":                                 "",
	"P.O.W. - Prisoners of War":                "gBkLPgP89O0",
	"Pac-Man":                                  "DxFjFS-idYk",
	"Pac-Mania":                                "rBIXFFBGGVM",
	"Pachicom":                                 "Km9h-OOgP_Y",
	"Palamedes":                                "",
	"Panic Restaurant":                         "zJOpWh9s9l4",
	"Paperboy 2":                               "LNyGzP9bXqQ",
	"Paperboy":                                 "DAKnKCVrs7c",
	"Paris-Dakar Rally Special":                "Xc5uB5GzV8I",
	"Parodius da!":                             "DKVxqzDQ-Qk",
	"Parodius":                                 "",
	"Peepar Time":                              "",
	"Penguin-kun Wars":                         "",
	"Perfect Bowling":                          "",
	"Perman":                                   "",
	"Phantom Fighter":                          "",
	"Pictionary - The Game of Video Quick Draw": "",
	"Pin-Bot":                                "XEWflJqPMiM",
	"Pinball Quest":                          "z4MJiAthjTc",
	"Pinball":                                "786yrUhXVrk",
	"Pipe Dream":                             "",
	"Pirates!":                               "",
	"Pizza Pop!":                             "7WCpApjIhCY",
	"Platoon":                                "Un9Wy-iKmp8",
	"Pooyan":                                 "idOTkCh3jbc",
	"Popeye":                                 "MYNFWm4sJO8",
	"Power Blade 2":                          "Y33gNed17ug",
	"Power Blade":                            "O2q-W5PgS1g",
	"Power Blazer":                           "",
	"Power Punch II":                         "dlKAAeRATKw",
	"Power Soccer":                           "KwqTdt0VmWc",
	"Predator":                               "c2zq0t46Wmw",
	"Prince of Persia":                       "QtM7x8ATBfA",
	"Princess Tomato in Salad Kingdom":       "",
	"Pro Sport Hockey":                       "",
	"Pro Wrestling":                          "EqZ9d0cPACc",
	"Probotector":                            "WcAjDFvVvaY",
	"Punch-Out!!":                            "81u1tkeA7EI",
	"Punisher, The":                          "x0dniXPDQAg",
	"Puss n Boots - Pero's Great Adventure":  "gW0dSvriJ9A",
	"Puyo Puyo":                              "",
	"Puzzle":                                 "",
	"Puzznic":                                "AHhrcfCni_U",
	"Pyokotan no Daimeiro":                   "",
	"Q-bert":                                 "",
	"Qix":                                    "jWS99rDdqZ4",
	"Quarth":                                 "rmN5aQlUtaQ",
	"Quinty":                                 "",
	"R.B.I. Baseball 2":                      "6vEeaIzAynU",
	"R.B.I. Baseball 3":                      "iuxKJUAE1bw",
	"R.B.I. Baseball":                        "BU6Rp1FSZDo",
	"R.C. Pro-Am II":                         "",
	"R.C. Pro-Am":                            "",
	"Race America":                           "",
	"Racket Attack":                          "",
	"Rad Racer II":                           "WqaWdGDScIc",
	"Rad Racer":                              "V6ngD3ZC1z8",
	"Raf World":                              "bBWcm499IXI",
	"Raid on Bungeling Bay":                  "YZudVNf7hN0",
	"Rainbow Islands":                        "",
	"Rally Bike":                             "xNwrvbe8NXA",
	"Rambo":                                  "LykyRgCZpAE",
	"Rampage":                                "",
	"Rampart":                                "",
	"Remote Control":                         "8gCvBmiP-aQ",
	"Ren & Stimpy Show, The - Buckeroo$!":    "",
	"Renegade":                               "flfni9wyytI",
	"Rescue - The Embassy Mission":           "FejRZydxfmU",
	"Ring King":                              "",
	"River City Ransom":                      "G_gEtc4rAqU",
	"Road Fighter":                           "5Q5-QNfmsbQ",
	"RoadBlasters":                           "J2HAOJCZnBI",
	"Robin Hood - Prince of Thieves":         "",
	"Robo Warrior":                           "fWYK0Vzv654",
	"Robocco Wars":                           "",
	"RoboCop 2":                              "TYerSLXmjQU",
	"RoboCop 3":                              "7FILe8utwVU",
	"RoboCop versus The Terminator":          "",
	"RoboCop":                                "jt2hg1hlRb4",
	"Rock 'n' Ball":                          "7CcX29SHlbY",
	"Rockball":                               "",
	"Rocket Ranger":                          "FLEI5-LgGZw",
	"Rocketeer, The":                         "NEwemGriRMo",
	"Rockin' Kats":                           "xSbViwipIFI",
	"Rockman 2 - Dr. Wily no Nazo":           "jagUMYfdDes",
	"Rockman 3 - Dr. Wily no Saigo!":         "6PjDrWuZZMg",
	"Rockman 4 - Aratanaru Yabou!!":          "Xhq-dQL906g",
	"Rockman 5 - Blues no Wana!":             "I1veM2blrec",
	"Rockman 6 - Shijou Saidai no Tatakai!!": "Bvdn4JY6dyQ",
	"Rockman":                                "P9GVQwMv2E0",
	"Rocman X":                               "",
	"Rod Land":                               "977O-aBdbUI",
	"Roger Clemens' MVP Baseball":            "",
	"Rollerball":                             "bOHjit01rJw",
	"Rollerblade Racer":                      "qsxrmfn5-Ag",
	"Rollergames":                            "r50jJoimpR4",
	"Rolling Thunder":                        "btfRSbSqyhs",
	"Romance of the Three Kingdoms II":       "",
	"Romance of the Three Kingdoms":          "",
	"Roundball - 2-on-2 Challenge":           "",
	"Route-16 Turbo":                         "",
	"Rush'n Attack":                          "Iv4Nm3MejF0",
	"Rygar":                                  "_DmaMbJfIaQ",
	"S.C.A.T. - Special Cybernetic Attack Team":      "toF1fWVv8_c",
	"Saiyuuki World 2 - Tenjoukai no Majin":          "ohTfbrDV0jE",
	"Salamander":                                     "wBXx6DlD_8k",
	"Scarabeus":                                      "",
	"SD Battle Oozumou - Heisei Hero Basho":          "p8JePYoMIZ8",
	"SD Hero Soukessen - Taose! Aku no Gundan":       "pNwv4etCTEk",
	"Secret Ties":                                    "",
	"Section-Z":                                      "WScye1xayu4",
	"Seicross":                                       "5H5q6hWa0Go",
	"Seikima II - Akuma no Gyakushuu":                "",
	"Senjou no Ookami":                               "ennDywhgb64",
	"Sesame Street - Big Bird's Hide & Speak":        "",
	"Sesame Street 123":                              "lpKS-IL5u4M",
	"Sesame Street ABC & 123":                        "",
	"Sesame Street ABC":                              "PyhFIX-crDE",
	"Sesame Street Countdown":                        "q9Ri0iVo53k",
	"Shadow of the Ninja":                            "KYzg8TO2WLk",
	"Shadow Warriors":                                "3c_8J5BHkiQ",
	"Shadowgate":                                     "mrP90v5N5u4",
	"Shanghai II":                                    "viiiumfeXeE",
	"Shanghai":                                       "T6F91i71VIA",
	"Shatterhand":                                    "R1VCf_pDSKY",
	"Shingen the Ruler":                              "",
	"Shooting Range":                                 "eiH4tup7Mhg",
	"Short Order + Egg-Splode!":                      "",
	"Side Pocket":                                    "erE_nCRdV7I",
	"Silent Service":                                 "",
	"Silk Worm":                                      "NS3MACq4ppY",
	"Silver Surfer":                                  "ZGGCYpggiDM",
	"Simpsons, The - Bart vs. the Space Mutants":     "-qjVGJAIdpQ",
	"Simpsons, The - Bart vs. the World":             "gO4IQ0wmwUM",
	"Simpsons, The - Bartman Meets Radioactive Man":  "",
	"Skate or Die 2 - The Search for Double Trouble": "hf0GhRZeEmY",
	"Skate or Die":                                   "xBsLV6R8mkc",
	"Ski or Die":                                     "IhbEInJeYb8",
	"Sky Destroyer":                                  "eyfK6jkvBh4",
	"Sky Kid":                                        "JNCGoG6n4vs",
	"Sky Shark":                                      "KCH44NdMOp8",
	"Slalom":                                         "UDDeOS9DfFk",
	"Smash T.V.":                                     "",
	"Smurfs, The":                                    "mZ_2Ck1gBjQ",
	"Snake Rattle n Roll":                            "r1aFoGEWHFA",
	"Snake's Revenge":                                "",
	"Snoopy's Silly Sports Spectacular!":             "y2HepXbNO9M",
	"Snow Bros.":                                     "a9yb5FLWThg",
	"Snow Brothers":                                  "a9yb5FLWThg",
	"Soccer League - Winner's Cup":                   "Az-ton90Kcw",
	"Soccer":                                         "",
	"Solar Jetman - Hunt for the Golden Warpship":    "",
	"Solomon's Key 2":                                "FDXxFwkjJ74",
	"Solomon's Key":                                  "eMFg_BKZMzQ",
	"Solstice - The Quest for the Staff of Demnos":   "ScW77tAMOgE",
	"Son Son":                                        "UCtm21B-OI4",
	"Soreike! Anpanman - Minna de Hiking Game!":      "",
	"Space Harrier":                                  "XAvsVEiwVhg",
	"Space Hunter":                                   "PAxRfd-cH2s",
	"Space Invaders":                                 "K6HXEfNl3WE",
	"Space Shuttle Project":                          "7JqjJKl5Wdk",
	"Spelunker":                                      "mxsfDNxqSKM",
	"Spider-Man - Return of the Sinister Six":        "HIn5Gg-wt4Y",
	"Spot - The Video Game":                          "UXXMVtRZ5ik",
	"Spy Hunter":                                     "-gdAWPH8v28",
	"Spy vs Spy":                                     "",
	"Sqoon":                                          "OMBda3R8tTI",
	"Squashed":                                       "",
	"Stadium Events":                                 "JTgS0jXzv70",
	"Stanley - The Search for Dr. Livingston":        "",
	"Star Force":                                     "tf4rxB2QjuY",
	"Star Gate":                                      "",
	"Star Soldier":                                   "JHeL1xoZfPI",
	"Star Trek - 25th Anniversary":                   "a_xHinVMzQQ",
	"Star Trek - The Next Generation":                "gLzh4V6xq8c",
	"Star Voyager":                                   "",
	"Star Wars - The Empire Strikes Back":            "",
	"Star Wars":                                      "",
	"Starship Hector":                                "6gKYUSVJz8M",
	"StarTropics":                                    "eAMJXN7zeyI",
	"Stealth ATF":                                    "",
	"Stinger":                                        "UHufyvzRhiU",
	"Street Cop":                                     "",
	"Street Fighter 2010 - The Final Fight":          "zyqeCXZCSGw",
	"Strider":                                        "rs2Q-_8zuAU",
	"Summer Carnival '92 - Recca":                    "nfY79-3AdGY",
	"Sunman":                                         "",
	"Super Arabian":                                  "",
	"Super C":                                        "Tiv9hl_vxfk",
	"Super Cars":                                     "vUzXFiBCfjU",
	"Super Chinese 3":                                "",
	"Super Chinese":                                  "RhyyftbnEaE",
	"Super Contra":                                   "iKEzk3dsF9w",
	"Super Dodge Ball":                               "nXp92WEPzas",
	"Super Glove Ball":                               "",
	"Super Jeopardy!":                                "vCFK9_g1ts4",
	"Super Mario Bros. + Duck Hunt + World Class Track Meet": "",
	"Super Mario Bros. + Duck Hunt":                          "",
	"Super Mario Bros. 2":                                    "Izc1yLUxPIw",
	"Super Mario Bros. 3":                                    "7i9omPUt9iQ",
	"Super Mario Bros.":                                      "rc62hFksKo4",
	"Super Mario USA":                                        "",
	"Super Pang II":                                          "",
	"Super Pang":                                             "",
	"Super Pinball":                                          "",
	"Super Pitfall":                                          "",
	"Super Spike V'Ball + Nintendo World Cup":                "",
	"Super Spike V'Ball":                                     "Fh5aQ0v5ooI",
	"Super Spy Hunter":                                       "qqZKLNaYIiw",
	"Super Team Games":                                       "OWlyGEyHhAM",
	"Super Turrican":                                         "etLUjXpgJp0",
	"Super Xevious - Gump no Nazo":                           "BgIUHdLnR50",
	"Superman":                                               "",
	"Swamp Thing":                                            "",
	"Sword Master":                                           "_GSfLqJUcOM",
	"Swords and Serpents":                                    "JXlt0XY1tOY",
	"Taboo - The Sixth Sense":                                "vOiaYTA82us",
	"Tag Team Wrestling":                                     "",
	"Taito Chase H.Q.":                                       "lpjv3qQJAIg",
	"Takahashi Meijin no Bugutte Honey":                      "",
	"TaleSpin":                                               "gO4gECW4Vsc",
	"Tao":                                                    "",
	"Target Renegade":                                        "7ok7no6TLPk",
	"Taro's Quest":                                           "",
	"Tasac":                                                  "",
	"Tatakai no Banka":                                       "Bzf6SFJNuv8",
	"Tecmo Baseball":                                         "",
	"Tecmo Bowl":                                             "_9vp9TkSSWw",
	"Tecmo Cup - Soccer Game":                                "",
	"Tecmo NBA Basketball":                                   "",
	"Tecmo Super Bowl":                                       "",
	"Tecmo World Wrestling":                                  "4ow9cadI_DM",
	"Teenage Mutant Ninja Turtles - Tournament Fighters":       "cxlzZrNjrCg",
	"Teenage Mutant Ninja Turtles II - The Arcade Game":        "VOByN1F71tI",
	"Teenage Mutant Ninja Turtles II - The Manhattan Project":  "GRbNSNnZWF4",
	"Teenage Mutant Ninja Turtles III - The Manhattan Project": "03tHi3kINjM",
	"Teenage Mutant Ninja Turtles":                             "",
	"Tennis":                                                   "jtO34yEbNvo",
	"Terminator 2 - Judgment Day":                              "DfDVvHHfcMw",
	"Terminator, The":                                          "UGqon5tzWqU",
	"Terra Cresta":                                             "iOPsrZnB4h4",
	"Tetris 2":                                                 "YyVbCC5B3tA",
	"Tetris":                                                   "",
	"Tetsuwan Atom":                                            "EDE2_aCkswY",
	"Thomas the Tank Engine and Friends":                       "",
	"Three Stooges, The":                                       "vm0dZ2wXNuU",
	"Thunder & Lightning":                                      "",
	"Thunderbirds":                                             "XRyxAzPlRAQ",
	"Thundercade":                                              "cOhLtfPA0M8",
	"Tiger-Heli":                                               "0ZhplpaK2vU",
	"Time Diver Eon Man":                                       "",
	"Time Lord":                                                "",
	"Time Zone":                                                "",
	"Times of Lore":                                            "",
	"Tiny Toon Adventures 2 - Trouble in Wackyland":            "yCFHPSv2T5A",
	"Tiny Toon Adventures Cartoon Workshop":                    "",
	"Tiny Toon Adventures":                                     "jqnjXaRIq9Y",
	"Titan Warriors":                                           "",
	"Titan":                                                    "",
	"To the Earth":                                             "6qbPBfdxPuo",
	"Toki":                                                     "eysZq0uOsOE",
	"Tokkyuu Shirei - Solbrain":                                "tDetm8Etozk",
	"Tokoro-san no Mamoru mo Semeru mo":                        "",
	"Tom & Jerry - The Ultimate Game of Cat and Mouse!": "",
	"Tom & Jerry":                  "TwsVhA-Uh_g",
	"Tom Sawyer no Bouken":         "DNFmSCxxS4s",
	"Tombs & Treasure":             "",
	"Top Gun - The Second Mission": "EsPWzAbGn04",
	"Top Gun":                      "5QJiI6LSZeE",
	"Top Striker":                  "aggS8IXcXuU",
	"Total Recall":                 "bhf_kAL14l4",
	"Totally Rad":                  "E4zfEVP4zAc",
	"Totsuzen! Macchoman":          "EjOlvZHnY6Y",
	"Touch Down Fever":             "",
	"Town & Country Surf Designs - Thrilla's Surfari": "",
	"Town & Country Surf Designs - Wood & Water Rage": "0zwTEYnmKLg",
	"Toxic Crusaders":                       "2gxN_5kDhc0",
	"Track & Field II":                      "c2FotM_Ellw",
	"Track & Field":                         "onbpJMqSSw4",
	"Transformers - Convoy no Nazo":         "uWjmkk5H9PE",
	"Treasure Master":                       "",
	"Triathron, The":                        "kwpl7LFj5l4",
	"Trog!":                                 "yR8_32dQyXU",
	"Trojan":                                "F4QPTkRgBfc",
	"Trolls in Crazyland, The":              "",
	"Twin Cobra":                            "wAefVLJWlPQ",
	"Twin Eagle":                            "91ECBHzuLYQ",
	"TwinBee":                               "AUM4yuR0DEw",
	"U-Force Test":                          "",
	"Uchuu Keibitai SDF":                    "2TnsfGmqcLU",
	"Ultima - Exodus":                       "",
	"Ultima - Quest of the Avatar":          "",
	"Ultima - Warriors of Destiny":          "",
	"Ultimate Air Combat":                   "",
	"Ultimate Basketball":                   "j-kJ9Ct0_zI",
	"Uncanny X-Men, The":                    "RhoGc-eNgYA",
	"Uncharted Waters":                      "",
	"Uninvited":                             "xjl3yLYePmE",
	"Untouchables, The":                     "YzRGwZiJxCI",
	"Urban Champion":                        "RPixc4qzg50",
	"Urusei Yatsura - Lum no Wedding Bell":  "",
	"USA Ice Hockey in FC":                  "",
	"Vegas Dream":                           "OE6WGj9pySA",
	"Vice - Project Doom":                   "o84PiCvcgdU",
	"Videomation":                           "",
	"Volguard II":                           "",
	"Volleyball":                            "",
	"Wacky Races":                           "7RXoPTP2i1o",
	"Wagyan Land 2":                         "",
	"Wagyan Land 3":                         "",
	"Wagyan Land":                           "",
	"Wai Wai World":                         "nxhwIPPCQeY",
	"Wall Street Kid":                       "",
	"Wanpaku Duck Yume Bouken":              "",
	"Wanpaku Kokkun no Gourmet World":       "ip354O9GhEA",
	"Wario's Woods":                         "",
	"Wayne Gretzky Hockey":                  "",
	"Wayne's World":                         "OkVb8HcWTGk",
	"WCW World Championship Wrestling":      "E9XGMMMu1AU",
	"Werewolf - The Last Warrior":           "_QWvek04ep0",
	"Wheel of Fortune - Family Edition":     "k419Ak3h2qg",
	"Wheel of Fortune - Junior Edition":     "7roZtUghlPY",
	"Wheel of Fortune Starring Vanna White": "",
	"Wheel of Fortune":                      "4olbEPjwzzY",
	"Where in Time Is Carmen Sandiego":      "",
	"Where's Waldo":                         "YJPGE9iy4-o",
	"Who Framed Roger Rabbit":               "z51SOcslQlw",
	"Whomp 'Em":                             "DbBEAJfaJfo",
	"Widget":                                "giWeTdBPOF8",
	"Wild Gunman":                           "UDuFDlAZpZY",
	"Willow":                                "qO1tJ_B9UUw",
	"Wily & Light no Rockboard - That's Paradise": "",
	"Win, Lose or Draw":                           "xgEYeLndTBU",
	"Winter Games":                                "rFmENcBiKNw",
	"Wit's":                                       "",
	"Wizardry - Knight of Diamonds - The Second Scenario": "",
	"Wizardry - Proving Grounds of the Mad Overlord":      "",
	"Wizards & Warriors III - Kuros...Visions of Power":   "",
	"Wizards & Warriors":                         "DS7Cm9Rdymw",
	"Wolverine":                                  "38p1c8jPYY8",
	"World Boxing":                               "_lOs-327Jvo",
	"World Champ - Super Boxing Great Fight":     "3J1GJEGVTV4",
	"World Class Track Meet":                     "",
	"World Games":                                "ztYh-SfIuRM",
	"Wrath of the Black Manta":                   "",
	"Wrecking Crew":                              "vCF40ee11JQ",
	"Wurm - Journey to the Center of the Earth!": "leyboAs01pU",
	"WWF King of the Ring":                       "Mr6DF42cuRg",
	"WWF Wrestlemania Challenge":                 "hO3g3Co4y9g",
	"WWF Wrestlemania Steel Cage Challenge":      "fwhTOSXzOnE",
	"WWF Wrestlemania":                           "qoFX6Cwgiow",
	"Xenophobe":                                  "",
	"Xevious - The Avenger":                      "",
	"Xevious":                                    "Io2AADdwATY",
	"Xexyz":                                      "-A9l8Qgj_SU",
	"Yie Ar Kung-Fu":                             "2n3ZzHTGBzI",
	"Yo! Noid":                                   "",
	"Yoshi no Cookie":                            "P-DQ-bZmzBA",
	"Yoshi's Cookie":                             "P-DQ-bZmzBA",
	"Yoshi":                                      "",
	"Youkai Douchuuki":                           "UHuf1QDxb24",
	"Young Indiana Jones Chronicles, The":        "JQ3CUU6FV8A",
	"Ys III - Wanderers From Ys":                 "97XMk6z80b0",
	"Ys":                                         "",
	"Zanac":                                      "JOtv4qN1rh8",
	"Zelda II - The Adventure of Link":           "LY-YryVEXZQ",
	"Zen - Intergalactic Ninja":                  "f7BBiaVwgUo",
	"Zippy Race":                                 "0OUQMS099cM",
	"Zoda's Revenge - StarTropics II":            "37q0VybbpFA",
	"Zombie Nation":                              "",
}
