package main

import (
	"fmt"
	"strconv"
	"strings"
)

func generateMisterSMSGames(generate bool) {
	smsTitleAdded := make(map[string]bool)
	smsImages := make(map[string]string)
	smsGameList := []string{}
	compileMisterConsoleData(smsTitleAdded, &smsGameList, smsImages, smsVideos, "sms")
	// smsVideoReport(&smsGameList)
	if generate {
		generateMisterConsoleHTML("Sega Master System Games", &smsGameList, smsImages, smsVideos, "sms")
	}

}

var smsVideos = map[string]string{
	"20 em 1":                        "zQ0cXGTmL3g",
	"3D Gunner":                      "",
	"4 PAK All Action":               "UytLO5G_y4A",
	"94 Super World Cup Soccer":      "OLPEsCFdBwg",
	"Ace of Aces":                    "W_rawisrZ6o",
	"Action Fighter":                 "Lo6pteCRE_I",
	"Aerial Assault":                 "RUEejEU1vgQ",
	"After Burner":                   "6wGQP8lyXq0",
	"Air Rescue":                     "S20J0YCgUQ8",
	"Aladdin":                        "XWwgY2CVKTE",
	"Alex Kidd - High-Tech World":    "UDMNEBv-4Hw",
	"Alex Kidd - The Lost Stars":     "sU226PphCxk",
	"Alex Kidd in Miracle World":     "Rb9haoWT5js",
	"Alex Kidd in Shinobi World":     "MClVUHg5qis",
	"Alf":                            "2ruBuzQ2yuI",
	"Alibaba and 40 Thieves":         "07_sLw8wv34",
	"Alien 3":                        "NhM8twrIKz8",
	"Alien Storm":                    "FwA2i2ObCVY",
	"Alien Syndrome":                 "E8V7VyULpoA",
	"Altered Beast":                  "Tv0_qMA4Cj8",
	"American Baseball":              "YD_O1KzAhUE",
	"American Pro Football":          "SQz8CKE_TZU",
	"Andre Agassi Tennis":            "CdiiSaXBbLw",
	"Anmitsu Hime":                   "_geL3Jw-ieI",
	"Arcade Smash Hits":              "_-JsQWPKJAM",
	"Argos no Juujiken":              "WvyviAhdY-4",
	"Ariel - The Little Mermaid":     "q0ILprSwKk4",
	"Ashura":                         "iBLoJz5l_vk",
	"Assault City":                   "I9vfT7CEJZc",
	"Astérix and the Great Rescue":   "LpT-rQTNCyg",
	"Astérix and the Secret Mission": "xUgVSneSt8I",
	"Astérix":                        "ksXbLsyUDGM",
	"Astro Warrior":                  "yY8QsVJ82QM",
	"Aztec Adventure":                "TnX7YhZLJ74",
	"Back to the Future Part II":     "YJ71Qw90ABQ",
	"Back to the Future Part III":    "zkRmG4jBNh0",
	"Baku Baku":                      "0XRi7zJfaW8",
	"Bank Panic":                     "Y1dOtpk5IWA",
	"Basketball Nightmare":           "l8-rkwriz78",
	"Batman Returns":                 "lDnv5DolpFw",
	"Battle Out Run":                 "NAJsVAPMd8s",
	"Battlemaniacs":                  "g8CUMTXdycY",
	"Black Belt":                     "N4LyIKU2qmM",
	"Blade Eagle 3-D":                "B49RLEo9A_k",
	"Block Hole":                     "VtoyJbVxVms",
	"BMX Trial Alex Kidd":            "qOW56IGReB0",
	"Bomber Raid":                    "fItPiRtajJ8",
	"Bonanza Bros.":                  "467Rap5CyJc",
	"Bonkers Wax Up!":                "io-otuw4sG4",
	"Bram Stoker's Dracula":          "ldz9uI4fUFY",
	"Bubble Bobble":                  "-7Wlyc22B4M",
	"Buggy Run":                      "KSjsOVfM6OQ",
	"C_So!":                          "NmInZOL3x-Q",
	"California Games II":            "1uQAJFv83uM",
	"California Games":               "B1huFDwAd4s",
	"Captain Silver":                 "bhYgaD9Qrg4",
	"Casino Games":                   "nK5BHaQfndo",
	"Castle of Illusion - Starring Mickey Mouse": "BE-rFtBnvjY",
	"Champions of Europe":                        "Z5gRvWwHf6E",
	"Championship Hockey":                        "NHd-lQ1kmFM",
	"Chapolim x Drácula - Um Duelo Assustador":   "lMM6w2gNzXU",
	"Chase H.Q.":                   "b68_wGrosX0",
	"Cheese Cat-Astrophe":          "0e1CUpgJJ4Q",
	"Choplifter":                   "fJmsywfSCrI",
	"Chuck Rock II - Son of Chuck": "Q4mZF4l4hII",
	"Chuck Rock":                   "Ng0HxM93FPw",
	"Cloud Master":                 "VYj2w0vzRHU",
	"Color & Switch Test":          "",
	"Columns":                      "3LUqzbfMWbc",
	"Comic Bakery":                 "9Z2BR916G7s",
	"Comical Machine Gun Joe":      "OCcdXbsTZts",
	"Cool Spot":                    "9aPqggkZQv4",
	"Cosmic Spacehead":             "ObGcfE_dEZM",
	"Cyborg Hunter":                "j7bKrnRu0Cw",
	"Cyborg Z":                     "72zugJBxw3g",
	"Daffy Duck in Hollywood":      "x8zWsUBioOI",
	"Dallyeora Pigu Wang":          "hxzinjYJ_6Y",
	"Danan - The Jungle Fighter":   "jluyTaO2JmA",
	"Dead Angle":                   "dOQnEZV2xw8",
	"Deep Duck Trouble":            "R4HsAsMy1D8",
	"Desert Speedtrap - Starring Road Runner and Wile E. Coyote": "0CY0yTKqNVo",
	"Desert Strike": "kPwM_d0XCVs",
	"Dick Tracy":    "yyaNg9H9-9I",
	"Dinobasher - Starring Bignose the Caveman": "PSR5sIJ_nY0",
	"Double Dragon":                          "sdwWu-i4WyE",
	"Double Hawk":                            "1GycH6ajEKE",
	"Dr. HELLO":                              "OfWUhtAknzk",
	"Dragon - The Bruce Lee Story":           "97WUygnuFTw",
	"Dragon Crystal":                         "Uxmd1wqkx6o",
	"Dynamite Duke":                          "qSdGAlT8ndo",
	"Dynamite Dux":                           "YbXySdBknUk",
	"Dynamite Headdy":                        "b3IzaMhR05E",
	"E-SWAT":                                 "9d5xob0iEG4",
	"E.I. - Exa Innova":                      "NPItYkP3cjo",
	"Eagles 5":                               "nEYPngchAL8",
	"Earthworm Jim":                          "vMzsh-83afA",
	"Ecco - The Tides of Time":               "laEwGki8w0I",
	"Ecco the Dolphin":                       "9SjAFpvifZA",
	"Enduro Racer":                           "OQN5E9OfHrM",
	"F-1 Spirit - The way to Formula-1":      "hI56yATDyU4",
	"F-16 Fighting Falcon":                   "63SxW13RqVk",
	"F1":                                     "Ri5PeknYn_w",
	"FA Tetris":                              "qOXT4L8iTOU",
	"Fantastic Dizzy":                        "UbuZYOt-A9Q",
	"Fantasy Zone - The Maze":                "hvDORyoOR3M",
	"Fantasy Zone II - The tears of OPA-OPA": "c7PRFSDDQ7c",
	"Fantasy Zone":                           "L7WQYjC26SU",
	"Férias Frustradas do Pica Pau":          "XYXgGjCO20g",
	"FIFA International Soccer":              "tw3K2Kl90jo",
	"Fire & Forget II":                       "wO3Nak9QmEk",
	"Fire & Ice":                             "cWIiANXTzi4",
	"Flashpoint":                             "GDnAuwBp_Ds",
	"Forgotten Worlds":                       "9tdDF85_qi4",
	"Fushigi no Oshiro Pit Pot":              "vaPaRuoe9nE",
	"G-LOC - Air Battle":                     "nEImLdp_GSw",
	"Gaegujangi Kkachi":                      "JABnkJWSTfs",
	"Gain Ground":                            "Kw0Q830uKXQ",
	"Galactic Protector":                     "Xb1Y_T1pDLE",
	"Galaxian":                               "W93EMME_EPQ",
	"Galaxy Force":                           "Jpz0m0jo29w",
	"Game Box Série Esportes Radicais":       "nzjW1SpvJMc",
	"Game de check! Koutsuu Anzen":           "ooMhDqLyXGs",
	"Gangcheol RoboCop":                      "JANOQjEH_FY",
	"Gangster Town":                          "30pBy1cQWaM",
	"Gauntlet":                               "o6cnZ_a41Hs",
	"Geraldinho":                             "m8r31XfVJ70",
	"Ghost House":                            "ZXwlgcfOx-w",
	"Ghostbusters":                           "anDvwNllVbo",
	"Ghouls'n Ghosts":                        "LFHcsEiFOH4",
	"Global Defense":                         "RPn_SUzV92Y",
	"Global Gladiators":                      "sWE5K8OQE3E",
	"Golden Axe Warrior":                     "ttD1ei0ND14",
	"Golden Axe":                             "OHbJLhumzUs",
	"Golfamania":                             "HdniuHD7X0E",
	"Golvellius - Valley of Doom":            "NOLWIrQshE8",
	"GP Rider":                               "Fh5BXydK9NE",
	"Great Baseball":                         "1ncE09ntIlE",
	"Great Basketball":                       "utxC6pOuLb8",
	"Great Golf":                             "jcoKXmh0iNY",
	"Great Ice Hockey":                       "xkeSWjPF8vI",
	"Great Soccer":                           "TJ6ReHNjlxQ",
	"Great Volleyball":                       "tU_89FKuxKk",
	"Gun.Smoke":                              "gCIr4MkOfFk",
	"Hang On":                                "czvFRvCLxqI",
	"Heavyweight Champ":                      "QzBDfcqqz_c",
	"Heroes of the Lance":                    "",
	"Hi-Com The Best Game Collection":        "",
	"High School! Kimengumi":                 "",
	"Hokuto no Ken":                          "hIiMz_NUDEw",
	"Home Alone":                             "",
	"Hong Kil Dong":                          "",
	"Hook":                                   "2GEnEzN7V6E",
	"Hoshi wo Sagashite...":                  "",
	"Impossible Mission":                     "",
	"Indiana Jones and the Last Crusade - The Action Game": "",
	"James Bond 007 - The Duel":                            "t2BPCxutoJk",
	"James Pond II - Codename RoboCod":                     "dl1qt5QfmSM",
	"Jang Pung 3":                                          "",
	"Jang Pung II":                                         "",
	"Janggun-ui Adeul":                                     "",
	"Joe Montana Football":                                 "9yCxMFhWdEY",
	"Jungle Book, The":                                     "",
	"Jurassic Park":                                        "39DPFa-djqU",
	"Kenseiden":                                            "iEp-eODfYcA",
	"King & Balloon":                                       "",
	"King's Quest - Quest for the Crown":                   "ddPTymAiN2Y",
	"KLAX":                                                 "",
	"Knightmare II - The Maze of Galious":                  "",
	"Krisalis Development System":                          "",
	"Krusty's Fun House":                                   "w1frK3XFPdo",
	"Kung Fu Kid":                                          "42zR5eVYfUA",
	"Land of Illusion - Starring Mickey Mouse":             "XP4VuReh0p0",
	"Laser Ghost":                                          "WZh9Tv7a61c",
	"Legend of Illusion - Starring Mickey Mouse":           "aNEGVYBpzDs",
	"Lemmings 2 - The Tribes":                              "",
	"Lemmings":                                             "KzqWdNFK490",
	"Line of Fire":                                         "mw2uSKcgkgw",
	"Lion King, The":                                       "",
	"Lord of the Sword":                                    "LIacuCv8Ym4",
	"Mahjong Sengoku Jidai":                                "",
	"Marble Madness":                                       "hAsMBJbITyM",
	"Marksman Shooting & Trap Shooting":                    "",
	"Marksman Shooting":                                    "",
	"Master of Darkness":                                   "CqcvVAsJG-A",
	"Masters of Combat":                                    "-_SfMwzbTbg",
	"Maze Hunter 3-D":                                      "",
	"Megumi Rescue":                                        "",
	"Mercs":                                                "DWBfc_D7ApY",
	"Michael Jackson's Moonwalker":                         "eDc_--eBdVo",
	"Mickey's Ultimate Challenge":                          "",
	"Micro Machines":                                       "171BoL5TNbU",
	"Miracle Warriors - Seal of The Dark Lord":             "",
	"Missile Defense 3-D":                                  "",
	"Mônica no Castelo do Dragão":                          "pI-GkbUnn_w",
	"Monopoly":                                             "",
	"Montezuma's Revenge - Featuring Panama Joe":           "",
	"Mopiranger":                                           "",
	"Mortal Kombat 3":                                      "",
	"Mortal Kombat II":                                     "SrJb8cxWz-I",
	"Mortal Kombat":                                        "ReiSJYQM88k",
	"Ms. Pac-Man":                                          "_VpIh6N9aCw",
	"My Hero":                                              "PGi7yHlXBmM",
	"NBA Jam":                                              "",
	"Nekkyuu Koushien":                                     "",
	"Nemesis 2":                                            "",
	"Nemesis":                                              "",
	"New Boggle Boggle 2":                                  "",
	"Ninja Gaiden":                                         "gWo-Lm0FQZo",
	"Olympic Gold":                                         "",
	"Operation Wolf":                                       "dp4xWbPKJI8",
	"Out Run 3-D":                                          "",
	"Out Run Europa":                                       "uzrfvPKnWAw",
	"Out Run":                                              "pxw4X6WvKAk",
	"Pac-Mania":                                            "6uETASX8LuY",
	"Paperboy":                                             "Vc3VtQ7B5ZM",
	"Parlour Games":                                        "",
	"Pat Riley Basketball":                                 "",
	"Penguin Adventure":                                    "",
	"Penguin Land":                                         "",
	"PGA TOUR Golf":                                        "YmnWX21PxU0",
	"Phantasy Star":                                        "n3P-3GsiRIw",
	"Pit-Fighter":                                          "",
	"Pooyan":                                               "",
	"Populous":                                             "",
	"Poseidon Wars 3-D":                                    "",
	"Power Boggle Boggle":                                  "",
	"Power Strike II":                                      "vk1yqYfbTQs",
	"Power Strike":                                         "",
	"Predator 2":                                           "K_yv2OcOGZk",
	"Prince of Persia":                                     "Sr-bH19FfjA",
	"Pro Wrestling":                                        "",
	"Promocao Especial M.System III Compact":               "",
	"Psychic World":                                        "Uhl7Vxe5xkA",
	"Psycho Fox":                                           "",
	"Putt & Putter":                                        "",
	"Puznic":                                               "",
	"Quartet":                                              "OBPwfwMiP20",
	"Quest for the Shaven Yak Starring Ren Hoëk & Stimpy": "",
	"R-Type":                                "Y7BgS78b4t0",
	"R.C. Grand Prix":                       "KbxownZB4Ko",
	"Rainbow Islands":                       "",
	"Rambo III":                             "vof5cjlwT4Y",
	"Rampage":                               "",
	"Rampart":                               "",
	"Rastan":                                "",
	"Renegade":                              "TGtcdIxCXy8",
	"Rescue Mission":                        "K-cVKU8DbNk",
	"Road Fighter":                          "",
	"Road Rash":                             "",
	"RoboCop 3":                             "WQ6kZxaPsMs",
	"RoboCop versus The Terminator":         "",
	"Rocky":                                 "HYHxY18qay8",
	"Running Battle":                        "ncRUbg92jhE",
	"Sagaia":                                "",
	"Samgukji III":                          "",
	"Sapo Xulé O Mestre do Kung Fu":         "",
	"Sapo Xulé S.O.S. Lagoa Poluída":        "",
	"Satellite 7":                           "yJ2IE6RcS1E",
	"Scramble Spirits":                      "",
	"Sega Chess":                            "",
	"Sega World Tournament Golf":            "",
	"Shadow Dancer - The Secret Of Shinobi": "",
	"Shadow of the Beast":                   "2KmyfWn2SO8",
	"Shanghai":                              "64XONtO047M",
	"Shinobi":                               "aWcZMYPcjgs",
	"Shooting Gallery":                      "",
	"Simpsons - Bart vs. The World, The":    "XHmTc-9jp9g",
	"Sítio do Picapau Amarelo":              "_QlBr-m1LIk",
	"Sky Fighter":                           "",
	"Sky Jaguar":                            "",
	"Slap Shot":                             "",
	"Solomon no Kagi - Oujo Rihita no Namida": "",
	"Sonic Blast":                    "",
	"Sonic Chaos":                    "-59vNc4EWm0",
	"Sonic Spinball":                 "",
	"Sonic The Hedgehog 2":           "B6RtXmMN9Og",
	"Sonic The Hedgehog":             "3WWgUUyyesg",
	"Sonic's Edusoft":                "",
	"Space Gun":                      "sdwtUTcDIEg",
	"Space Harrier 3-D":              "",
	"Space Harrier":                  "usiaujwjv4M",
	"Special Criminal Investigation": "FNGmB4J3gac",
	"Speedball 2":                    "glkaHAZVhXc",
	"Speedball":                      "glkaHAZVhXc",
	"SpellCaster":                    "-832upAbYxg",
	"Spider-Man - Return of the Sinister Six": "2LTSlfnhx2w",
	"Sports Pad Football":                     "",
	"Spy vs Spy":                              "",
	"Star Wars":                               "8UJMY2PZMmE",
	"Street Fighter II'":                      "5H7bR7wzBo4",
	"Street Master":                           "",
	"Streets of Rage II":                      "RWThYuHTg4k",
	"Streets of Rage":                         "hHby7-Kah7w",
	"Strider II":                              "YPNdoH_1iHc",
	"Strider":                                 "Ej5SH3iCmwk",
	"Submarine Attack":                        "lZPTgsIQK34",
	"Suho Jeonsa":                             "",
	"Sukeban Deka II - Shoujo Tekkamen Densetsu": "",
	"Summer Games":                 "",
	"Super Basketball":             "",
	"Super Bioman I":               "",
	"Super Boy 4":                  "",
	"Super Boy I":                  "",
	"Super Boy II":                 "",
	"Super Boy III":                "",
	"Super Bubble Bobble":          "",
	"Super Columns":                "",
	"Super Kick Off":               "",
	"Super Monaco GP II":           "",
	"Super Monaco GP":              "",
	"Super Off Road":               "",
	"Super Racing":                 "",
	"Super Smash T.V.":             "AdomU3RFEOc",
	"Super Space Invaders":         "G64-1T-29Fg",
	"Super Tennis":                 "",
	"Superman - The Man of Steel":  "",
	"T2 - The Arcade Game":         "LpMV0G4LpIk",
	"Taz in Escape from Mars":      "",
	"Taz-Mania":                    "P5tYJm10u4c",
	"Tecmo World Cup '93":          "",
	"Teddy Boy":                    "blN_3elwK1I",
	"Tennis Ace":                   "",
	"Tensai Bakabon":               "qV8dFCuGZng",
	"Terminator 2 - Judgment Day":  "",
	"Terminator, The":              "",
	"The Addams Family":            "RNjolXBmxx8",
	"The Cyber Shinobi":            "",
	"The Dinosaur Dooley":          "",
	"The Flash":                    "",
	"The Flintstones":              "",
	"The Incredible Crash Dummies": "zDJ8qNjDsT8",
	"The Incredible Hulk":          "",
	"The Lucky Dime Caper - Starring Donald Duck": "",
	"The Micro Xevious":                           "",
	"The NewZealand Story":                        "o39KTDiMqdM",
	"The Ninja":                                   "P_eY4RzCMLI",
	"The Ottifants":                               "ZaH-bfxhyok",
	"The Pro Yakyuu - Pennant Race":               "",
	"The Smurfs Travel the World":                 "",
	"The Smurfs":                                  "uADcyDI2N7I",
	"Three Dragon Story, The":                     "",
	"Thunder Blade":                               "uS9z2nU4dcE",
	"Time Soldiers":                               "Tqpp6lpduj8",
	"Tom and Jerry - The Movie":                   "shPVJges_Lk",
	"Toto World 3":                                "",
	"TransBot":                                    "TXJBRAd7Bwg",
	"Trivial Pursuit - Genus Edition":             "",
	"Turma da Mônica em - O Resgate":              "",
	"TV Colosso":                                  "",
	"Ultima IV - Quest of the Avatar":             "",
	"Ultimate Soccer":                             "44Tvo8A6Z24",
	"Vigilante":                                   "dAkTZ12XB8c",
	"Virtua Fighter Animation":                    "YQhO2lWJoTU",
	"Wanted":                                      "wp2PsDcQWrs",
	"Where in the World is Carmen Sandiego?":      "",
	"Wimbledon II":                                "",
	"Wimbledon":                                   "",
	"Winter Olympics":                             "",
	"Wolfchild":                                   "mqFPj1lvBdI",
	"Wonder Boy III - The Dragon's Trap":          "OBdu19yBNkQ",
	"Wonder Boy in Monster Land":                  "",
	"Wonder Boy in Monster World":                 "",
	"Wonder Boy":                                  "Rj3cyTBTkSg",
	"Wonsiin":                                     "",
	"Woody Pop - Shinjinrui no Block Kuzugi":      "",
	"World Class Leader Board":                    "",
	"World Cup Italia '90":                        "IXE7rtzOIGw",
	"World Cup USA 94":                            "",
	"World Games":                                 "",
	"World Grand Prix":                            "bn4c-kMtDXY",
	"World Soccer":                                "",
	"WWF WrestleMania Steel Cage Challenge":       "",
	"X-Men - Mojo World":                          "",
	"Xenon 2 - Megablast":                         "9LorXSnTFbA",
	"Xyzolog":                                     "",
	"Y's - The Vanished Omens":                    "",
	"Zaxxon 3-D":                                  "",
	"Zillion II - The Tri Formation":              "",
	"Zillion":                                     "tKhwO571-1U",
	"Zool - Ninja of the 'Nth' Dimension":         "",
}

func smsVideoReport(gameList *[]string) {
	// Calculate Best Video Matches
	var distZero = 0
	var distOne = 0
	var distTwo = 0
	var distThree = 0
	var distFour = 0
	var distFive = 0
	var distMoreThanFive = 0
	for _, v := range *gameList {
		// Only do this process for titles with no video
		if smsVideos[v] == "" {

			tempName := v

			if idx := strings.IndexByte(tempName, '('); idx >= 0 {
				tempName = strings.TrimRight(tempName[:idx], " ")
			}
			if strings.Contains(tempName, ", The") {
				tempName = strings.Replace(tempName, ", The", "", 1)
				tempName = "The " + tempName
			}

			var str1 = []rune(tempName)
			var lowestDistance = 99
			var lowestName = ""
			for _, n := range smsLongplays {
				temptemp := n[:strings.IndexByte(n, '|')]
				var str2 = []rune(temptemp)
				var tempDistance = levenshtein(str1, str2)
				if tempDistance < lowestDistance {
					lowestDistance = tempDistance
					lowestName = n //temptemp
				}
			}
			if lowestDistance == 0 {
				distZero = distZero + 1
			}
			if lowestDistance == 1 {
				distOne = distOne + 1
			}
			if lowestDistance == 2 {
				distTwo = distTwo + 1
			}
			if lowestDistance == 3 {
				distThree = distThree + 1
			}
			if lowestDistance == 4 {
				distFour = distFour + 1
			}
			if lowestDistance == 5 {
				distFive = distFive + 1
			}
			if lowestDistance > 5 {
				distMoreThanFive = distMoreThanFive + 1
			}

			// Cycle through: <= 2, == 3, == 4, == 5, > 5
			// 0, 1, 2 are correct
			if lowestDistance >= 0 {

				//lowestName = lowestName[strings.IndexByte(lowestName, '|')+1:] // for final
				//fmt.Println("\"" + v + "\": \"" + lowestName + "\",") // for testing

				// For the rest without matches
				fmt.Println("\"" + v + "\": \"\",")
				if false {
					fmt.Println(lowestName)
				}
			}
		}
	}
	// Reporting
	fmt.Println("Distance 0: " + strconv.Itoa(distZero))
	fmt.Println("Distance 1: " + strconv.Itoa(distOne))
	fmt.Println("Distance 2: " + strconv.Itoa(distTwo))
	fmt.Println("Distance 3: " + strconv.Itoa(distThree))
	fmt.Println("Distance 4: " + strconv.Itoa(distFour))
	fmt.Println("Distance 5: " + strconv.Itoa(distFive))
	fmt.Println("Distance 5+: " + strconv.Itoa(distMoreThanFive))
}

var smsLongplays = []string{
	"'94 Super World Cup Soccer|OLPEsCFdBwg",
	"20 em 1|zQ0cXGTmL3g",
	"4 Pak All Action - Toto World 3 (Unlicensed)|PsdVVZkf70M",
	"Action Fighter|Lo6pteCRE_I",
	"Aerial Assault|RUEejEU1vgQ",
	"Afterburner (a)|6wGQP8lyXq0",
	"AfterBurner (FM)|ExzchhbgqQE",
	"Agigongnyong Dooly (Unlicensed)|uKuuoR0cT0w",
	"Air Rescue|S20J0YCgUQ8",
	"Aladdin|XWwgY2CVKTE",
	"Aleste|UXGTtUkJVPc",
	"Alex Kidd BMX Trial|qOW56IGReB0",
	"Alex Kidd in Miracle World|Rb9haoWT5js",
	"Alex Kidd in Shinobi World|MClVUHg5qis",
	"Alex Kidd in Shinobi World (a)|5-f1UfA_B5o",
	"Alex Kidd: High-Tech World|UDMNEBv-4Hw",
	"Alex Kidd: The Lost Stars|sU226PphCxk",
	"ALF|2ruBuzQ2yuI",
	"Alien 3|NhM8twrIKz8",
	"Alien Storm|FwA2i2ObCVY",
	"Alien Syndrome (FM)|E8V7VyULpoA",
	"Altered Beast|Tv0_qMA4Cj8",
	"Argos no Juujiken|WvyviAhdY-4",
	"Ashura|iBLoJz5l_vk",
	"Assault City|I9vfT7CEJZc",
	"Asterix|ksXbLsyUDGM",
	"Astro Flash|t1Vykr7p1mE",
	"Astro Warrior|yY8QsVJ82QM",
	"Back to the Future Part II|YJ71Qw90ABQ",
	"Back to the Future Part III|zkRmG4jBNh0",
	"Baluba Balok (Homebrew)|",
	"Bank Panic|Y1dOtpk5IWA",
	"Bara Burū (Homebrew)|",
	"Basketball Nightmare|l8-rkwriz78",
	"Batman Returns|lDnv5DolpFw",
	"Battle Outrun|NAJsVAPMd8s",
	"Battlemaniacs|g8CUMTXdycY",
	"Black Belt|N4LyIKU2qmM",
	"Blade Eagle 3-D (a) (3D)|oo95CvD7wdM",
	"Blade Eagle 3-D (FM) (3D)|oVYNqT-BwMI",
	"Bomber Raid (FM)|fItPiRtajJ8",
	"Bonanza Bros|467Rap5CyJc",
	"Bram Stoker's Dracula|ldz9uI4fUFY",
	"Bruce Lee (Homebrew)|",
	"Buggy Run|",
	"California Games (FM)|LXUSOGwIfmk",
	"Captain Silver|bhYgaD9Qrg4",
	"Casino Games|nK5BHaQfndo",
	"Castelo Ra-Tim-Bum|wQDRess59c8",
	"Castle of Illusion starring Mickey Mouse|BE-rFtBnvjY",
	"Champions of Europe|Z5gRvWwHf6E",
	"Chapolim x Dracula - Um Duelo Assustador|lMM6w2gNzXU",
	"Choplifter|fJmsywfSCrI&feature=feedu",
	"Chuck Rock|Ng0HxM93FPw",
	"Chuck Rock II - Son of Chuck|Q4mZF4l4hII",
	"Cloud Master (FM)|VYj2w0vzRHU",
	"Columns|3LUqzbfMWbc",
	"Comical Machinegun Joe|OCcdXbsTZts",
	"Cosmic Spacehead|ObGcfE_dEZM",
	"Cyber Shinobi|geODYog8lLo",
	"Daffy Duck in Hollywood|x8zWsUBioOI",
	"Danan: The Jungle Fighter|jluyTaO2JmA",
	"Dick Tracy|yyaNg9H9-9I",
	"Disney's Ariel: The Little Mermaid|",
	"Donald Duck: Deep Duck Trouble|R4HsAsMy1D8",
	"Donald Duck: The Lucky Dime Caper|bzD1-XVUXFQ",
	"Double Dragon|sdwWu-i4WyE",
	"Double Dragon (FM) (a)|fWlnsW3ywsI",
	"Double Hawk|1GycH6ajEKE",
	"Dr.Hello (Unlicensed)|8Ut16JNQNv0",
	"Dr.Robotnik's Mean Bean Machine|7Vm_EZJvzok",
	"Dragon Crystal|Uxmd1wqkx6o",
	"Dynamite Duke|qSdGAlT8ndo",
	"Dynamite Dux|YbXySdBknUk",
	"Dynamite Headdy|b3IzaMhR05E",
	"E-SWAT: City Under Siege|9d5xob0iEG4",
	"Earthworm Jim|",
	"Enduro Racer|OQN5E9OfHrM&feature=youtu.be",
	"F-16 Fighting Falcon|63SxW13RqVk",
	"F1 Championship|Ri5PeknYn_w",
	"Fantastic Dizzy|UbuZYOt-A9Q",
	"Fantasy Zone|L7WQYjC26SU",
	"Fantasy Zone II (FM)|H2RUody7rNM",
	"Final Bubble Bobble|YA5c3UHN8Z4",
	"Fire & Forget II|wO3Nak9QmEk",
	"Fire & ice|cWIiANXTzi4",
	"Flight of Pigarus (Homebrew)|",
	"Forgotten Worlds|9tdDF85_qi4",
	"G-Loc: Air Battle|nEImLdp_GSw",
	"Gain Ground|Kw0Q830uKXQ",
	"Galactic Protector|Xb1Y_T1pDLE",
	"Galaxy Force (FM)|NcZt-5dBD_4",
	"Ghost House|ZXwlgcfOx-w",
	"Ghostbusters|anDvwNllVbo",
	"Ghouls n Ghosts|LFHcsEiFOH4",
	"Golden Axe|OHbJLhumzUs",
	"Golden Axe Warrior|ttD1ei0ND14",
	"Golvellius|NOLWIrQshE8",
	"Hang-On|czvFRvCLxqI",
	"Heavyweight Champ|QzBDfcqqz_c",
	"High School! Kimengumi (Fan Translation)|mjLHOOutd24",
	"Hokuto no Ken|hIiMz_NUDEw",
	"Hong Kil Dong (Unlicensed)|",
	"Hook|2GEnEzN7V6E",
	"Hoshi wo Sagashite... (Fan Translation)|JR0DyjXDb6E",
	"Hwarang-ui Geom (FM) (Unlicensed)|NPuSteGhnVg",
	"James Bond 007: The Duel|t2BPCxutoJk",
	"James Pond 2 - Codename Robocod|dl1qt5QfmSM",
	"Jang Pung 3 (Unlicensed)|mYiNdRpELps",
	"Joe Montana Football|9yCxMFhWdEY",
	"Jungle Book|1RfpkqfmchQ",
	"Jurassic Park|39DPFa-djqU",
	"Kenseiden|iEp-eODfYcA",
	"King's Quest: Quest for the Crown|ddPTymAiN2Y",
	"Krusty's Fun House|w1frK3XFPdo",
	"Kung Fu Kid|42zR5eVYfUA",
	"Land of Illusion starring Mickey Mouse|XP4VuReh0p0",
	"Laser Ghost|WZh9Tv7a61c",
	"Legend of Illusion Starring Mickey Mouse|aNEGVYBpzDs",
	"Lemmings|KzqWdNFK490",
	"Lemmings 2: The Tribes (Prototype)|7JOkDUSA5k0",
	"Line of Fire|mw2uSKcgkgw",
	"Line of Fire (3D)|2WqvAqUGOMs",
	"Lord of the Sword|LIacuCv8Ym4",
	"Marble Madness|hAsMBJbITyM",
	"Master of Darkness|CqcvVAsJG-A",
	"Masters of Combat|-_SfMwzbTbg",
	"Maze Hunter 3-D (FM) (3D)|4XZVYm_HoLc",
	"Mercs|DWBfc_D7ApY",
	"Michael Jacksons Moonwalker|eDc_--eBdVo",
	"Mick & Mack as the Global Gladiators|QWNZreMBI48",
	"Micro Machines|171BoL5TNbU",
	"Missile Defense 3-D (3D)|00D2v_gtKD8",
	"Monica no Castelo do Dragao|pI-GkbUnn_w",
	"Monopoly|",
	"Mortal Kombat|ReiSJYQM88k",
	"Mortal Kombat 3|",
	"Mortal Kombat II|SrJb8cxWz-I",
	"Ms. Pac-man|_VpIh6N9aCw",
	"My Hero|PGi7yHlXBmM",
	"Nazca '88: The Golden Road to Paradise (FM) (Aztec Adventure)|bcU8fxmZrEk",
	"Ninja Gaiden|gWo-Lm0FQZo",
	"Operation Wolf|dp4xWbPKJI8",
	"Out Run|pxw4X6WvKAk",
	"Out Run (FM) (a)|vEfX4rsPM5o",
	"Out Run 3-D (a) (3D)|vf_aUcm0J2c",
	"Out Run 3-D (FM) (3D)|WNYiQHqh9Mc",
	"Outrun Europa|uzrfvPKnWAw",
	"Pacmania|6uETASX8LuY",
	"Paperboy|Vc3VtQ7B5ZM",
	"PGA Tour Golf|YmnWX21PxU0",
	"Phantasy Star|n3P-3GsiRIw",
	"Pit-Fighter|",
	"Poseidon Wars 3-D (3D)|XoiGKg2iBEI",
	"Poseidon Wars 3-D (a) (FM) (3D)|tCYC7mv0k5Y",
	"Power Strike (FM)|KMbzGmVyzJ8&feature=youtu.be",
	"Power Strike II|vk1yqYfbTQs",
	"Predator 2|K_yv2OcOGZk",
	"Prince of Persia|Sr-bH19FfjA",
	"Psychic World|Uhl7Vxe5xkA",
	"Psycho Fox|",
	"Quartet|OBPwfwMiP20",
	"Quest for the Shaven Yak Starring Ren Hoek and Stimpy|fcXK_yBJcnc",
	"R-Type|Y7BgS78b4t0",
	"R-Type (FM) (a)|dQc_hkTEb4s",
	"R.C. Grand Prix|KbxownZB4Ko",
	"Rainbow Islands - The Story of Bubble Bobble 2|iy7yz0L92vM",
	"Rambo - First Blood Part 2|WITYnVFbroI",
	"Rambo III|vof5cjlwT4Y",
	"Rampage (FM)|KDL9FSXlhIA",
	"Rastan (a)|yRH4Xl9Q5Yk",
	"Rastan (FM)|7WgecudccEM",
	"Renegade|TGtcdIxCXy8",
	"Rescue Mission|K-cVKU8DbNk",
	"Robocop 3|WQ6kZxaPsMs",
	"Rocky|HYHxY18qay8",
	"Running Battle|ncRUbg92jhE",
	"Sagaia (Darius II)|tlL6VcvaWjc",
	"Sangokushi III (Unlicensed)|holpbG0GQ54",
	"Sapo Xule SOS:  Lagoa Poluida|XSZG7u9vyYg",
	"Satellite 7|yJ2IE6RcS1E",
	"Scramble Spirits (FM)|",
	"SDI - Strategic Defense Initiative|xbUSzWPf9uo",
	"Secret Commando|nO-rccChHd0",
	"Shadow Dancer|b790wPx5HmQ",
	"Shadow of the Beast|2KmyfWn2SO8",
	"Shanghai|64XONtO047M",
	"Shinobi|aWcZMYPcjgs",
	"Silver Valley (Homebrew)|",
	"Sitio do Picapau Amarelo|_QlBr-m1LIk",
	"Snail Maze|-rb9pyRdaH0",
	"Sonic Blast|",
	"Sonic Chaos|-59vNc4EWm0",
	"Sonic the Hedgehog|3WWgUUyyesg",
	"Sonic the Hedgehog (a)|SQPvA0OvR24",
	"Sonic the Hedgehog 2|B6RtXmMN9Og",
	"Space Gun|sdwtUTcDIEg",
	"Space Harrier|usiaujwjv4M",
	"Space Harrier 3-D (a) (3D)|RdCZOEiMMJw",
	"Space Harrier 3-D (FM) (3D)|UoPJQYFK66Y",
	"Special Criminal Investigation|FNGmB4J3gac",
	"Speedball 2|glkaHAZVhXc",
	"SpellCaster|-832upAbYxg",
	"Spider-Man: Return of the Sinister Six|2LTSlfnhx2w",
	"Star Wars|8UJMY2PZMmE",
	"Street Fighter II|5H7bR7wzBo4",
	"Streets of Rage|hHby7-Kah7w",
	"Streets of Rage II|RWThYuHTg4k",
	"Strider|Ej5SH3iCmwk",
	"Strider II|YPNdoH_1iHc",
	"Submarine Attack|lZPTgsIQK34",
	"Sukeban Deka II: Shoujo Tekkamen Densetsu (Fan Translation)|OwVikuc5Rnw",
	"Super BiOman 1 (Unlicensed)|IwJpqfNaCU8",
	"Super Boy 3 (Unlicensed)|Az9sbnyjsAQ",
	"Super Boy 4 (Unlicensed)|ylHOhRv2Xzw",
	"Super Boy I. (Unlicensed)|gFIFp8nsGOc",
	"Super Boy II. (Unlicensed)|emcuGLf_Xy8",
	"Super Racing|",
	"Super Smash TV|AdomU3RFEOc",
	"Super Space Invaders|G64-1T-29Fg",
	"T2 - The Arcade Game|LpMV0G4LpIk",
	"Taz in Escape from Mars|",
	"Taz-Mania|P5tYJm10u4c",
	"Teddy Boy|blN_3elwK1I",
	"Tensai Bakabon|qV8dFCuGZng",
	"The Addams Family|RNjolXBmxx8",
	"The Dinosaur Dooley (Unlicensed)|",
	"The Flintstones|",
	"The Incredible Crash Dummies|zDJ8qNjDsT8",
	"The Lion King|",
	"The New Zealand Story|o39KTDiMqdM",
	"The Ninja|P_eY4RzCMLI",
	"The Ottifants|ZaH-bfxhyok",
	"The Simpsons - Bart vs the world|XHmTc-9jp9g",
	"The Simpsons: Bart vs. the Space Mutants|-6sZXmo50K0",
	"The Smurfs|uADcyDI2N7I",
	"The Smurfs 2|okOglPqecac",
	"Thunder Blade|uS9z2nU4dcE",
	"Thunder Blade (FM) (a)|za4OAELdMJI",
	"Time Soldiers|Tqpp6lpduj8",
	"Tom and Jerry: The Movie|shPVJges_Lk",
	"TransBot|TXJBRAd7Bwg",
	"Ultimate Soccer|44Tvo8A6Z24",
	"Vigilante|dAkTZ12XB8c",
	"Virtua Fighter Animation|YQhO2lWJoTU",
	"Wanted|wp2PsDcQWrs",
	"Wing Warriors (Homebrew)|",
	"Wolfchild|mqFPj1lvBdI",
	"Wonder Boy|Rj3cyTBTkSg",
	"Wonder Boy II: Wonder Boy in Monster Land|saWdMP5BYS0",
	"Wonder Boy III: The Dragons Trap|OBdu19yBNkQ",
	"Wonder Boy V: In Monster World III|c_gWam9QlSM",
	"Wonsiin (Unlicensed)|",
	"World Cup Italia '90|IXE7rtzOIGw",
	"World Games|",
	"World Grand Prix|bn4c-kMtDXY",
	"X-Men: Mojo World|",
	"Xenon II - Megablast|9LorXSnTFbA",
	"Zaxxon (a) (3D)|jx4mdEZ6GW8",
	"Zaxxon 3-D (FM) (3D)|YPcpb69sTGA",
	"Zillion|tKhwO571-1U",
	"Zillion II - The Tri Formation (FM)|VGnkhcmZvRw",
	"Zool|zXFxMjYRZa0",
}

var smsGameInfo = map[string]string{
	"20 em 1":                            "https://www.smspower.org/Games/20Em1-SMS",
	"3D Gunner":                          "https://www.smspower.org/Games/3DGunner-SMS",
	"4 PAK All Action":                   "https://www.smspower.org/Games/4PakAllAction-SMS",
	"94 Super World Cup Soccer":          "https://www.smspower.org/Games/94SuperWorldCupSoccer-SMS",
	"Ace of Aces":                        "https://www.smspower.org/Games/AceOfAces-SMS",
	"Action Fighter":                     "https://www.smspower.org/Games/ActionFighter-SMS",
	"The Addams Family":                  "https://www.smspower.org/Games/AddamsFamily-SMS",
	"Aerial Assault":                     "https://www.smspower.org/Games/AerialAssault-SMS",
	"After Burner":                       "https://www.smspower.org/Games/AfterBurner-SMS",
	"Air Rescue":                         "https://www.smspower.org/Games/AirRescue-SMS",
	"Aladdin":                            "https://www.smspower.org/Games/Aladdin-SMS",
	"Alex Kidd - High-Tech World":        "https://www.smspower.org/Games/AlexKiddHighTechWorld-SMS",
	"Alex Kidd in Miracle World":         "https://www.smspower.org/Games/AlexKiddInMiracleWorld-SMS",
	"Alex Kidd in Shinobi World":         "https://www.smspower.org/Games/AlexKiddInShinobiWorld-SMS",
	"Alex Kidd - The Lost Stars":         "https://www.smspower.org/Games/AlexKiddTheLostStars-SMS",
	"Alf":                                "https://www.smspower.org/Games/Alf-SMS",
	"Alibaba and 40 Thieves":             "https://www.smspower.org/Games/AlibabaAnd40Thieves-SMS",
	"Alien 3":                            "https://www.smspower.org/Games/Alien3-SMS",
	"Alien Storm":                        "https://www.smspower.org/Games/AlienStorm-SMS",
	"Alien Syndrome":                     "https://www.smspower.org/Games/AlienSyndrome-SMS",
	"Altered Beast":                      "https://www.smspower.org/Games/AlteredBeast-SMS",
	"American Baseball":                  "https://www.smspower.org/Games/AmericanBaseball-SMS",
	"American Pro Football":              "https://www.smspower.org/Games/AmericanProFootball-SMS",
	"Andre Agassi Tennis":                "https://www.smspower.org/Games/AndreAgassiTennis-SMS",
	"Anmitsu Hime":                       "https://www.smspower.org/Games/AnmitsuHime-SMS",
	"Arcade Smash Hits":                  "https://www.smspower.org/Games/ArcadeSmashHits-SMS",
	"Argos no Juujiken":                  "https://www.smspower.org/Games/ArgosNoJuujiken-SMS",
	"Ariel - The Little Mermaid":         "https://www.smspower.org/Games/ArielTheLittleMermaid-SMS",
	"Ashura":                             "https://www.smspower.org/Games/Ashura-SMS",
	"Assault City":                       "https://www.smspower.org/Games/AssaultCity-SMS",
	"Astérix":                            "https://www.smspower.org/Games/Asterix-SMS",
	"Astérix and the Great Rescue":       "https://www.smspower.org/Games/AsterixAndTheGreatRescue-SMS",
	"Astérix and the Secret Mission":     "https://www.smspower.org/Games/AsterixAndTheSecretMission-SMS",
	"Astro Warrior":                      "https://www.smspower.org/Games/AstroWarrior-SMS",
	"The A-Team":                         "https://www.smspower.org/Games/ATeam-SMS",
	"Aztec Adventure":                    "https://www.smspower.org/Games/AztecAdventure-SMS",
	"Back to the Future Part II":         "https://www.smspower.org/Games/BackToTheFuturePartII-SMS",
	"Back to the Future Part III":        "https://www.smspower.org/Games/BackToTheFuturePartIII-SMS",
	"Baku Baku":                          "https://www.smspower.org/Games/BakuBaku-SMS",
	"Bank Panic":                         "https://www.smspower.org/Games/BankPanic-SMS",
	"Simpsons - Bart vs. The World, The": "https://www.smspower.org/Games/BartVsTheWorld-SMS",
	"Basketball Nightmare":               "https://www.smspower.org/Games/BasketballNightmare-SMS",
	"Batman Returns":                     "https://www.smspower.org/Games/BatmanReturns-SMS",
	"Battlemaniacs":                      "https://www.smspower.org/Games/Battlemaniacs-SMS",
	"Battle Out Run":                     "https://www.smspower.org/Games/BattleOutRun-SMS",
	"Black Belt":                         "https://www.smspower.org/Games/BlackBelt-SMS",
	"Blade Eagle 3-D":                    "https://www.smspower.org/Games/BladeEagle3D-SMS",
	"Block Hole":                         "https://www.smspower.org/Games/BlockHole-SMS",
	"BMX Trial Alex Kidd":                "https://www.smspower.org/Games/BMXTrialAlexKidd-SMS",
	"Bomber Raid":                        "https://www.smspower.org/Games/BomberRaid-SMS",
	"Bonanza Bros.":                      "https://www.smspower.org/Games/BonanzaBros-SMS",
	"Bonkers Wax Up!":                    "https://www.smspower.org/Games/BonkersWaxUp-SMS",
	"Bubble Bobble":                      "https://www.smspower.org/Games/BubbleBobble-SMS",
	"Buggy Run":                          "https://www.smspower.org/Games/BuggyRun-SMS",
	"California Games":                   "https://www.smspower.org/Games/CaliforniaGames-SMS",
	"California Games II":                "https://www.smspower.org/Games/CaliforniaGamesII-SMS",
	"Captain Silver":                     "https://www.smspower.org/Games/CaptainSilver-SMS",
	"Casino Games":                       "https://www.smspower.org/Games/CasinoGames-SMS",
	"Castle of Illusion - Starring Mickey Mouse": "https://www.smspower.org/Games/CastleOfIllusion-SMS",
	"Championship Hockey":                        "https://www.smspower.org/Games/ChampionshipHockey-SMS",
	"Champions of Europe":                        "https://www.smspower.org/Games/ChampionsOfEurope-SMS",
	"Chapolim x Drácula - Um Duelo Assustador":   "https://www.smspower.org/Games/ChapolimXDracula-SMS",
	"Chase H.Q.":                   "https://www.smspower.org/Games/ChaseHQ-SMS",
	"Cheese Cat-Astrophe":          "https://www.smspower.org/Games/CheeseCatastrophe-SMS",
	"Choplifter":                   "https://www.smspower.org/Games/Choplifter-SMS",
	"Chuck Rock":                   "https://www.smspower.org/Games/ChuckRock-SMS",
	"Chuck Rock II - Son of Chuck": "https://www.smspower.org/Games/ChuckRockII-SMS",
	"Cloud Master":                 "https://www.smspower.org/Games/CloudMaster-SMS",
	"Color & Switch Test":          "https://www.smspower.org/Games/ColorAndSwitchTest-SMS",
	"Columns":                      "https://www.smspower.org/Games/Columns-SMS",
	"Comical Machine Gun Joe":      "https://www.smspower.org/Games/ComicalMachineGunJoe-SMS",
	"Comic Bakery":                 "https://www.smspower.org/Games/ComicBakery-SMS",
	"Cool Spot":                    "https://www.smspower.org/Games/CoolSpot-SMS",
	"Cosmic Spacehead":             "https://www.smspower.org/Games/CosmicSpacehead-SMS",
	"C_So!":                        "https://www.smspower.org/Games/CSoMsx-SMS",
	"The Cyber Shinobi":            "https://www.smspower.org/Games/CyberShinobi-SMS",
	"Cyborg Hunter":                "https://www.smspower.org/Games/CyborgHunter-SMS",
	"Cyborg Z":                     "https://www.smspower.org/Games/CyborgZ-SMS",
	"Daffy Duck in Hollywood":      "https://www.smspower.org/Games/DaffyDuckInHollywood-SMS",
	"Dallyeora Pigu Wang":          "https://www.smspower.org/Games/DallyeoraPiguWang-SMS",
	"Danan - The Jungle Fighter":   "https://www.smspower.org/Games/DananTheJungleFighter-SMS",
	"Dead Angle":                   "https://www.smspower.org/Games/DeadAngle-SMS",
	"Deep Duck Trouble":            "https://www.smspower.org/Games/DeepDuckTrouble-SMS",
	"Desert Speedtrap - Starring Road Runner and Wile E. Coyote": "https://www.smspower.org/Games/DesertSpeedtrap-SMS",
	"Desert Strike": "https://www.smspower.org/Games/DesertStrike-SMS",
	"Dick Tracy":    "https://www.smspower.org/Games/DickTracy-SMS",
	"Dinobasher - Starring Bignose the Caveman": "https://www.smspower.org/Games/Dinobasher-SMS",
	"The Dinosaur Dooley":                       "https://www.smspower.org/Games/DinosaurDooley-SMS",
	"Double Dragon":                             "https://www.smspower.org/Games/DoubleDragon-SMS",
	"Double Hawk":                               "https://www.smspower.org/Games/DoubleHawk-SMS",
	"Bram Stoker's Dracula":                     "https://www.smspower.org/Games/Dracula-SMS",
	"Dragon - The Bruce Lee Story":              "https://www.smspower.org/Games/Dragon-SMS",
	"Dragon Crystal":                            "https://www.smspower.org/Games/DragonCrystal-SMS",
	"Dr. HELLO":                                 "https://www.smspower.org/Games/DrHello-SMS",
	"Dynamite Duke":                             "https://www.smspower.org/Games/DynamiteDuke-SMS",
	"Dynamite Dux":                              "https://www.smspower.org/Games/DynamiteDux-SMS",
	"Dynamite Headdy":                           "https://www.smspower.org/Games/DynamiteHeaddy-SMS",
	"Eagles 5":                                  "https://www.smspower.org/Games/Eagles5-SMS",
	"Earthworm Jim":                             "https://www.smspower.org/Games/EarthwormJim-SMS",
	"Ecco the Dolphin":                          "https://www.smspower.org/Games/EccoTheDolphin-SMS",
	"Ecco - The Tides of Time":                  "https://www.smspower.org/Games/EccoTheTidesOfTime-SMS",
	"E.I. - Exa Innova":                         "https://www.smspower.org/Games/EIExaInnova-SMS",
	"Enduro Racer":                              "https://www.smspower.org/Games/EnduroRacer-SMS",
	"E-SWAT":                                    "https://www.smspower.org/Games/ESWAT-SMS",
	"F1":                                        "https://www.smspower.org/Games/F1-SMS",
	"F-16 Fighting Falcon":                      "https://www.smspower.org/Games/F16FightingFalcon-SMS",
	"F-1 Spirit - The way to Formula-1":         "https://www.smspower.org/Games/F1Spirit-SMS",
	"Fantastic Dizzy":                           "https://www.smspower.org/Games/FantasticDizzy-SMS",
	"Fantasy Zone":                              "https://www.smspower.org/Games/FantasyZone-SMS",
	"Fantasy Zone II - The tears of OPA-OPA":    "https://www.smspower.org/Games/FantasyZoneII-SMS",
	"Fantasy Zone - The Maze":                   "https://www.smspower.org/Games/FantasyZoneTheMaze-SMS",
	"FA Tetris":                                 "https://www.smspower.org/Games/FATetris-SMS",
	"Férias Frustradas do Pica Pau":             "https://www.smspower.org/Games/FeriasFrustradasDoPicaPau-SMS",
	"FIFA International Soccer":                 "https://www.smspower.org/Games/FIFAInternationalSoccer-SMS",
	"Fire & Forget II":                          "https://www.smspower.org/Games/FireAndForgetII-SMS",
	"Fire & Ice":                                "https://www.smspower.org/Games/FireAndIce-SMS",
	"The Flash":                                 "https://www.smspower.org/Games/Flash-SMS",
	"Flashpoint":                                "https://www.smspower.org/Games/Flashpoint-SMS",
	"The Flintstones":                           "https://www.smspower.org/Games/Flintstones-SMS",
	"Forgotten Worlds":                          "https://www.smspower.org/Games/ForgottenWorlds-SMS",
	"Fushigi no Oshiro Pit Pot":                 "https://www.smspower.org/Games/FushigiNoOshiroPitPot-SMS",
	"Gaegujangi Kkachi":                         "https://www.smspower.org/Games/GaegujangiKkachi-SMS",
	"Gain Ground":                               "https://www.smspower.org/Games/GainGround-SMS",
	"Galactic Protector":                        "https://www.smspower.org/Games/GalacticProtector-SMS",
	"Galaxian":                                  "https://www.smspower.org/Games/Galaxian-SMS",
	"Galaxy Force":                              "https://www.smspower.org/Games/GalaxyForce-SMS",
	"Game Box Série Esportes Radicais":          "https://www.smspower.org/Games/GameBoxSerieEsportesRadicais-SMS",
	"Game de check! Koutsuu Anzen":              "https://www.smspower.org/Games/GameDeCheckKoutsuuAnzen-SMS",
	"Gangcheol RoboCop":                         "https://www.smspower.org/Games/GangcheolRobocop-SMS",
	"Gangster Town":                             "https://www.smspower.org/Games/GangsterTown-SMS",
	"Gauntlet":                                  "https://www.smspower.org/Games/Gauntlet-SMS",
	"Geraldinho":                                "https://www.smspower.org/Games/Geraldinho-SMS",
	"Ghostbusters":                              "https://www.smspower.org/Games/Ghostbusters-SMS",
	"Ghost House":                               "https://www.smspower.org/Games/GhostHouse-SMS",
	"Ghouls'n Ghosts":                           "https://www.smspower.org/Games/GhoulsNGhosts-SMS",
	"Global Defense":                            "https://www.smspower.org/Games/GlobalDefense-SMS",
	"Global Gladiators":                         "https://www.smspower.org/Games/GlobalGladiators-SMS",
	"G-LOC - Air Battle":                        "https://www.smspower.org/Games/GLOCAirBattle-SMS",
	"Golden Axe":                                "https://www.smspower.org/Games/GoldenAxe-SMS",
	"Golden Axe Warrior":                        "https://www.smspower.org/Games/GoldenAxeWarrior-SMS",
	"Golfamania":                                "https://www.smspower.org/Games/Golfamania-SMS",
	"Golvellius - Valley of Doom":               "https://www.smspower.org/Games/Golvellius-SMS",
	"GP Rider":                                  "https://www.smspower.org/Games/GPRider-SMS",
	"Great Baseball":                            "https://www.smspower.org/Games/GreatBaseball-SMS",
	"Great Basketball":                          "https://www.smspower.org/Games/GreatBasketball-SMS",
	"Great Golf":                                "https://www.smspower.org/Games/GreatGolf-SMS",
	"Great Golf [Japan]":                        "https://www.smspower.org/Games/GreatGolfJP-SMS",
	"Great Ice Hockey":                          "https://www.smspower.org/Games/GreatIceHockey-SMS",
	"Great Soccer":                              "https://www.smspower.org/Games/GreatSoccerCard-SMS",
	"Great Volleyball":                          "https://www.smspower.org/Games/GreatVolleyball-SMS",
	"Gun.Smoke":                                 "https://www.smspower.org/Games/GunSmoke-SMS",
	"Hang On":                                   "https://www.smspower.org/Games/HangOn-SMS",
	"Heavyweight Champ":                         "https://www.smspower.org/Games/HeavyweightChamp-SMS",
	"Heroes of the Lance":                       "https://www.smspower.org/Games/HeroesOfTheLance-SMS",
	"Hi-Com The Best Game Collection [Series]": "https://www.smspower.org/Games/HiComTheBestGameCollection-SMS",
	"High School! Kimengumi":                   "https://www.smspower.org/Games/HighSchoolKimengumi-SMS",
	"Hokuto no Ken":                            "https://www.smspower.org/Games/HokutoNoKen-SMS",
	"Home Alone":                               "https://www.smspower.org/Games/HomeAlone-SMS",
	"Hong Kil Dong":                            "https://www.smspower.org/Games/HongKilDong-SMS",
	"Hook":                                     "https://www.smspower.org/Games/Hook-SMS",
	"Hoshi wo Sagashite...":                    "https://www.smspower.org/Games/HoshiWoSagashite-SMS",
	"Impossible Mission":                       "https://www.smspower.org/Games/ImpossibleMission-SMS",
	"The Incredible Crash Dummies":             "https://www.smspower.org/Games/IncredibleCrashDummies-SMS",
	"The Incredible Hulk":                      "https://www.smspower.org/Games/IncredibleHulk-SMS",
	"Indiana Jones and the Last Crusade - The Action Game": "https://www.smspower.org/Games/IndianaJonesAndTheLastCrusade-SMS",
	"James Bond 007 - The Duel":                            "https://www.smspower.org/Games/JamesBond007TheDuel-SMS",
	"James Pond II - Codename RoboCod":                     "https://www.smspower.org/Games/JamesPondII-SMS",
	"Janggun-ui Adeul":                                     "https://www.smspower.org/Games/JanggunuiAdeul-SMS",
	"Jang Pung 3":                                          "https://www.smspower.org/Games/JangPung3-SMS",
	"Jang Pung II":                                         "https://www.smspower.org/Games/JangPungII-SMS",
	"Joe Montana Football":                                 "https://www.smspower.org/Games/JoeMontanaFootball-SMS",
	"Jungle Book, The":                                     "https://www.smspower.org/Games/JungleBook-SMS",
	"Jurassic Park":                                        "https://www.smspower.org/Games/JurassicPark-SMS",
	"Kenseiden":                                            "https://www.smspower.org/Games/Kenseiden-SMS",
	"King & Balloon":                                       "https://www.smspower.org/Games/KingAndBalloon-SMS",
	"King's Quest - Quest for the Crown":                   "https://www.smspower.org/Games/KingsQuest-SMS",
	"KLAX":                                                 "https://www.smspower.org/Games/KLAX-SMS",
	"Krisalis Development System":                          "https://www.smspower.org/Games/KrisalisDevelopmentSystem-SMS",
	"Krusty's Fun House":                                   "https://www.smspower.org/Games/KrustysFunHouse-SMS",
	"Kung Fu Kid":                                          "https://www.smspower.org/Games/KungFuKid-SMS",
	"Land of Illusion - Starring Mickey Mouse":             "https://www.smspower.org/Games/LandOfIllusion-SMS",
	"Laser Ghost":                                          "https://www.smspower.org/Games/LaserGhost-SMS",
	"Legend of Illusion - Starring Mickey Mouse":           "https://www.smspower.org/Games/LegendOfIllusion-SMS",
	"Lemmings":                                             "https://www.smspower.org/Games/Lemmings-SMS",
	"Lemmings 2 - The Tribes":                              "https://www.smspower.org/Games/Lemmings2-SMS",
	"Lethal Weapon 3":                                      "https://www.smspower.org/Games/LethalWeapon3-SMS",
	"Line of Fire":                                         "https://www.smspower.org/Games/LineOfFire-SMS",
	"Lion King, The":                                       "https://www.smspower.org/Games/LionKing-SMS",
	"Lord of the Sword":                                    "https://www.smspower.org/Games/LordOfTheSword-SMS",
	"The Lucky Dime Caper - Starring Donald Duck":          "https://www.smspower.org/Games/LuckyDimeCaper-SMS",
	"Mahjong Sengoku Jidai":                                "https://www.smspower.org/Games/MahjongSengokuJidai-SMS",
	"Marble Madness":                                       "https://www.smspower.org/Games/MarbleMadness-SMS",
	"Marksman Shooting & Trap Shooting":                    "https://www.smspower.org/Games/MarksmanShootingAndTrapShooting-SMS",
	"Marksman Shooting":                                    "https://www.smspower.org/Games/MarksmanShootingTrapShootingSafariHunt-SMS",
	"Master of Darkness":                                   "https://www.smspower.org/Games/MasterOfDarkness-SMS",
	"Masters of Combat":                                    "https://www.smspower.org/Games/MastersOfCombat-SMS",
	"Maze Hunter 3-D":                                      "https://www.smspower.org/Games/MazeHunter3D-SMS",
	"Knightmare II - The Maze of Galious":                  "https://www.smspower.org/Games/MazeOfGalious-SMS",
	"Megumi Rescue":                                        "https://www.smspower.org/Games/MegumiRescue-SMS",
	"Mercs":                                                "https://www.smspower.org/Games/Mercs-SMS",
	"Mickey's Ultimate Challenge":                          "https://www.smspower.org/Games/MickeysUltimateChallenge-SMS",
	"Micro Machines":                                       "https://www.smspower.org/Games/MicroMachines-SMS",
	"The Micro Xevious":                                    "https://www.smspower.org/Games/MicroXevious-SMS",
	"Miracle Warriors - Seal of The Dark Lord":             "https://www.smspower.org/Games/MiracleWarriors-SMS",
	"Missile Defense 3-D":                                  "https://www.smspower.org/Games/MissileDefense3D-SMS",
	"Mônica no Castelo do Dragão":                          "https://www.smspower.org/Games/MonicaNoCasteloDoDragao-SMS",
	"Monopoly":                                             "https://www.smspower.org/Games/Monopoly-SMS",
	"Montezuma's Revenge - Featuring Panama Joe":           "https://www.smspower.org/Games/MontezumasRevenge-SMS",
	"Michael Jackson's Moonwalker":                         "https://www.smspower.org/Games/Moonwalker-SMS",
	"Mopiranger":                                           "https://www.smspower.org/Games/Mopiranger-SMS",
	"Mortal Kombat":                                        "https://www.smspower.org/Games/MortalKombat-SMS",
	"Mortal Kombat 3":                                      "https://www.smspower.org/Games/MortalKombat3-SMS",
	"Mortal Kombat II":                                     "https://www.smspower.org/Games/MortalKombatII-SMS",
	"Ms. Pac-Man":                                          "https://www.smspower.org/Games/MsPacMan-SMS",
	"My Hero":                                              "https://www.smspower.org/Games/MyHero-SMS",
	"NBA Jam":                                              "https://www.smspower.org/Games/NBAJam-SMS",
	"Nekkyuu Koushien":                                     "https://www.smspower.org/Games/NekkyuuKoushien-SMS",
	"Nemesis":                                              "https://www.smspower.org/Games/Nemesis-SMS",
	"Nemesis 2":                                            "https://www.smspower.org/Games/Nemesis2-SMS",
	"New Boggle Boggle 2":                                  "https://www.smspower.org/Games/NewBoggleBoggle2-SMS",
	"The NewZealand Story":                                 "https://www.smspower.org/Games/NewZealandStory-SMS",
	"The Ninja":                                            "https://www.smspower.org/Games/Ninja-SMS",
	"Ninja Gaiden":                                         "https://www.smspower.org/Games/NinjaGaiden-SMS",
	"Olympic Gold":                                         "https://www.smspower.org/Games/OlympicGold-SMS",
	"Operation Wolf":                                       "https://www.smspower.org/Games/OperationWolf-SMS",
	"The Ottifants":                                        "https://www.smspower.org/Games/Ottifants-SMS",
	"Out Run":                                              "https://www.smspower.org/Games/OutRun-SMS",
	"Out Run 3-D":                                          "https://www.smspower.org/Games/OutRun3D-SMS",
	"Out Run Europa":                                       "https://www.smspower.org/Games/OutRunEuropa-SMS",
	"Pac-Mania":                                            "https://www.smspower.org/Games/PacMania-SMS",
	"Paperboy":                                             "https://www.smspower.org/Games/Paperboy-SMS",
	"Parlour Games":                                        "https://www.smspower.org/Games/ParlourGames-SMS",
	"Pat Riley Basketball":                                 "https://www.smspower.org/Games/PatRileyBasketball-SMS",
	"Penguin Adventure":                                    "https://www.smspower.org/Games/PenguinAdventure-SMS",
	"Penguin Land":                                         "https://www.smspower.org/Games/PenguinLand-SMS",
	"PGA TOUR Golf":                                        "https://www.smspower.org/Games/PGATourGolf-SMS",
	"Phantasy Star":                                        "https://www.smspower.org/Games/PhantasyStar-SMS",
	"Pit-Fighter":                                          "https://www.smspower.org/Games/PitFighter-SMS",
	"Pooyan":                                               "https://www.smspower.org/Games/Pooyan-SMS",
	"Populous":                                             "https://www.smspower.org/Games/Populous-SMS",
	"Poseidon Wars 3-D":                                    "https://www.smspower.org/Games/PoseidonWars3D-SMS",
	"Power Boggle Boggle":                                  "https://www.smspower.org/Games/PowerBoggleBoggle-SMS",
	"Power Strike":                                         "https://www.smspower.org/Games/PowerStrike-SMS",
	"Power Strike II":                                      "https://www.smspower.org/Games/PowerStrikeII-SMS",
	"Predator 2":                                           "https://www.smspower.org/Games/Predator2-SMS",
	"Prince of Persia":                                     "https://www.smspower.org/Games/PrinceOfPersia-SMS",
	"Promocao Especial M.System III Compact":               "https://www.smspower.org/Games/PromocaoEspecialMSystemIIICompact-SMS",
	"Pro Wrestling":                                        "https://www.smspower.org/Games/ProWrestling-SMS",
	"The Pro Yakyuu - Pennant Race":                        "https://www.smspower.org/Games/ProYakyuu-SMS",
	"Psychic World":                                        "https://www.smspower.org/Games/PsychicWorld-SMS",
	"Psycho Fox":                                           "https://www.smspower.org/Games/PsychoFox-SMS",
	"Putt & Putter":                                        "https://www.smspower.org/Games/PuttAndPutter-SMS",
	"Puznic":                                               "https://www.smspower.org/Games/Puznic-SMS",
	"Quartet":                                              "https://www.smspower.org/Games/Quartet-SMS",
	"Quest for the Shaven Yak Starring Ren Hoëk & Stimpy": "https://www.smspower.org/Games/QuestForTheShavenYak-SMS",
	"Rainbow Islands":                       "https://www.smspower.org/Games/RainbowIslands-SMS",
	"Rambo III":                             "https://www.smspower.org/Games/RamboIII-SMS",
	"Rampage":                               "https://www.smspower.org/Games/Rampage-SMS",
	"Rampart":                               "https://www.smspower.org/Games/Rampart-SMS",
	"Rastan":                                "https://www.smspower.org/Games/Rastan-SMS",
	"R.C. Grand Prix":                       "https://www.smspower.org/Games/RCGrandPrix-SMS",
	"Renegade":                              "https://www.smspower.org/Games/Renegade-SMS",
	"Rescue Mission":                        "https://www.smspower.org/Games/RescueMission-SMS",
	"Road Fighter":                          "https://www.smspower.org/Games/RoadFighter-SMS",
	"Road Rash":                             "https://www.smspower.org/Games/RoadRash-SMS",
	"RoboCop 3":                             "https://www.smspower.org/Games/RoboCop3-SMS",
	"RoboCop versus The Terminator":         "https://www.smspower.org/Games/RoboCopVersusTheTerminator-SMS",
	"Rocky":                                 "https://www.smspower.org/Games/Rocky-SMS",
	"R-Type":                                "https://www.smspower.org/Games/RType-SMS",
	"Running Battle":                        "https://www.smspower.org/Games/RunningBattle-SMS",
	"Sagaia":                                "https://www.smspower.org/Games/Sagaia-SMS",
	"Samgukji III":                          "https://www.smspower.org/Games/SamgukjiIII-SMS",
	"Sapo Xulé O Mestre do Kung Fu":         "https://www.smspower.org/Games/SapoXuleOMestreDoKungFu-SMS",
	"Sapo Xulé S.O.S. Lagoa Poluída":        "https://www.smspower.org/Games/SapoXuleSOSLagoaPoluida-SMS",
	"Satellite 7":                           "https://www.smspower.org/Games/Satellite7-SMS",
	"Scramble Spirits":                      "https://www.smspower.org/Games/ScrambleSpirits-SMS",
	"Sega Chess":                            "https://www.smspower.org/Games/SegaChess-SMS",
	"Sega Graphic Board":                    "https://www.smspower.org/Games/SegaGraphicBoard-SMS",
	"Sega Master System [System ROM]":       "https://www.smspower.org/Games/SegaMasterSystemRom-SMS",
	"Sega World Tournament Golf":            "https://www.smspower.org/Games/SegaWorldTournamentGolf-SMS",
	"Shadow Dancer - The Secret Of Shinobi": "https://www.smspower.org/Games/ShadowDancer-SMS",
	"Shadow of the Beast":                   "https://www.smspower.org/Games/ShadowOfTheBeast-SMS",
	"Shanghai":                              "https://www.smspower.org/Games/Shanghai-SMS",
	"Shinobi":                               "https://www.smspower.org/Games/Shinobi-SMS",
	"Shooting Gallery":                      "https://www.smspower.org/Games/ShootingGallery-SMS",
	"Sítio do Picapau Amarelo":              "https://www.smspower.org/Games/SitioDoPicapauAmarelo-SMS",
	"Sky Fighter":                           "https://www.smspower.org/Games/SkyFighter-SMS",
	"Sky Jaguar":                            "https://www.smspower.org/Games/SkyJaguar-SMS",
	"Slap Shot":                             "https://www.smspower.org/Games/SlapShot-SMS",
	"The Smurfs":                            "https://www.smspower.org/Games/Smurfs-SMS",
	"The Smurfs Travel the World":           "https://www.smspower.org/Games/SmurfsTravelTheWorld-SMS",
	"Solomon no Kagi - Oujo Rihita no Namida": "https://www.smspower.org/Games/SolomonNoKagi-SMS",
	"Sonic Blast":                    "https://www.smspower.org/Games/SonicBlast-SMS",
	"Sonic Chaos":                    "https://www.smspower.org/Games/SonicChaos-SMS",
	"Sonic's Edusoft":                "https://www.smspower.org/Games/SonicsEdusoft-SMS",
	"Sonic Spinball":                 "https://www.smspower.org/Games/SonicSpinball-SMS",
	"Sonic The Hedgehog":             "https://www.smspower.org/Games/SonicTheHedgehog-SMS",
	"Sonic The Hedgehog 2":           "https://www.smspower.org/Games/SonicTheHedgehog2-SMS",
	"Space Gun":                      "https://www.smspower.org/Games/SpaceGun-SMS",
	"Space Harrier":                  "https://www.smspower.org/Games/SpaceHarrier-SMS",
	"Space Harrier 3-D":              "https://www.smspower.org/Games/SpaceHarrier3D-SMS",
	"Special Criminal Investigation": "https://www.smspower.org/Games/SpecialCriminalInvestigation-SMS",
	"Speedball":                      "https://www.smspower.org/Games/Speedball-SMS",
	"Speedball 2":                    "https://www.smspower.org/Games/Speedball2-SMS",
	"SpellCaster":                    "https://www.smspower.org/Games/SpellCaster-SMS",
	"Spider-Man - Return of the Sinister Six": "https://www.smspower.org/Games/SpiderManReturnOfTheSinisterSix-SMS",
	"Sports Pad Football":                     "https://www.smspower.org/Games/SportsPadFootball-SMS",
	"Spy vs Spy":                              "https://www.smspower.org/Games/SpyVsSpy-SMS",
	"Star Wars":                               "https://www.smspower.org/Games/StarWars-SMS",
	"Street Fighter II'":                      "https://www.smspower.org/Games/StreetFighterII-SMS",
	"Street Master":                           "https://www.smspower.org/Games/StreetMaster-SMS",
	"Streets of Rage":                         "https://www.smspower.org/Games/StreetsOfRage-SMS",
	"Streets of Rage II":                      "https://www.smspower.org/Games/StreetsOfRageII-SMS",
	"Strider":                                 "https://www.smspower.org/Games/Strider-SMS",
	"Strider II":                              "https://www.smspower.org/Games/StriderII-SMS",
	"Submarine Attack":                        "https://www.smspower.org/Games/SubmarineAttack-SMS",
	"Suho Jeonsa":                             "https://www.smspower.org/Games/SuhoJeonsa-SMS",
	"Sukeban Deka II - Shoujo Tekkamen Densetsu": "https://www.smspower.org/Games/SukebanDekaII-SMS",
	"Summer Games":                           "https://www.smspower.org/Games/SummerGames-SMS",
	"Super Basketball":                       "https://www.smspower.org/Games/SuperBasketball-SMS",
	"Super Bioman I":                         "https://www.smspower.org/Games/SuperBiomanI-SMS",
	"Super Boy 4":                            "https://www.smspower.org/Games/SuperBoy4-SMS",
	"Super Boy I":                            "https://www.smspower.org/Games/SuperBoyI-SMS",
	"Super Boy II":                           "https://www.smspower.org/Games/SuperBoyII-SMS",
	"Super Boy III":                          "https://www.smspower.org/Games/SuperBoyIII-SMS",
	"Super Bubble Bobble":                    "https://www.smspower.org/Games/SuperBubbleBobble-SMS",
	"Super Columns":                          "https://www.smspower.org/Games/SuperColumns-SMS",
	"Super Kick Off":                         "https://www.smspower.org/Games/SuperKickOff-SMS",
	"Superman - The Man of Steel":            "https://www.smspower.org/Games/Superman-SMS",
	"Super Monaco GP":                        "https://www.smspower.org/Games/SuperMonacoGP-SMS",
	"Super Monaco GP II":                     "https://www.smspower.org/Games/SuperMonacoGPII-SMS",
	"Super Off Road":                         "https://www.smspower.org/Games/SuperOffRoad-SMS",
	"Super Racing":                           "https://www.smspower.org/Games/SuperRacing-SMS",
	"Super Smash T.V.":                       "https://www.smspower.org/Games/SuperSmashTV-SMS",
	"Super Space Invaders":                   "https://www.smspower.org/Games/SuperSpaceInvaders-SMS",
	"Super Tennis":                           "https://www.smspower.org/Games/SuperTennis-SMS",
	"T2 - The Arcade Game":                   "https://www.smspower.org/Games/T2TheArcadeGame-SMS",
	"Taz in Escape from Mars":                "https://www.smspower.org/Games/TazInEscapeFromMars-SMS",
	"Taz-Mania":                              "https://www.smspower.org/Games/TazMania-SMS",
	"Tecmo World Cup '93":                    "https://www.smspower.org/Games/TecmoWorldCup93-SMS",
	"Teddy Boy":                              "https://www.smspower.org/Games/TeddyBoy-SMS",
	"Tennis Ace":                             "https://www.smspower.org/Games/TennisAce-SMS",
	"Tensai Bakabon":                         "https://www.smspower.org/Games/TensaiBakabon-SMS",
	"Terminator, The":                        "https://www.smspower.org/Games/Terminator-SMS",
	"Terminator 2 - Judgment Day":            "https://www.smspower.org/Games/Terminator2JudgmentDay-SMS",
	"Three Dragon Story, The":                "https://www.smspower.org/Games/ThreeDragonStory-SMS",
	"Thunder Blade":                          "https://www.smspower.org/Games/ThunderBlade-SMS",
	"Time Soldiers":                          "https://www.smspower.org/Games/TimeSoldiers-SMS",
	"Tom and Jerry - The Movie":              "https://www.smspower.org/Games/TomAndJerryTheMovie-SMS",
	"Toto World 3":                           "https://www.smspower.org/Games/TotoWorld3-SMS",
	"TransBot":                               "https://www.smspower.org/Games/TransBot-SMS",
	"Trivial Pursuit - Genus Edition":        "https://www.smspower.org/Games/TrivialPursuit-SMS",
	"Turma da Mônica em - O Resgate":         "https://www.smspower.org/Games/TurmaDaMonica-SMS",
	"TV Colosso":                             "https://www.smspower.org/Games/TVColosso-SMS",
	"Ultima IV - Quest of the Avatar":        "https://www.smspower.org/Games/UltimaIV-SMS",
	"Ultimate Soccer":                        "https://www.smspower.org/Games/UltimateSoccer-SMS",
	"Vigilante":                              "https://www.smspower.org/Games/Vigilante-SMS",
	"Virtua Fighter Animation":               "https://www.smspower.org/Games/VirtuaFighterAnimation-SMS",
	"Wanted":                                 "https://www.smspower.org/Games/Wanted-SMS",
	"Where in the World is Carmen Sandiego?": "https://www.smspower.org/Games/WhereInTheWorldIsCarmenSandiego-SMS",
	"Wimbledon":                              "https://www.smspower.org/Games/Wimbledon-SMS",
	"Wimbledon II":                           "https://www.smspower.org/Games/WimbledonII-SMS",
	"Winter Olympics":                        "https://www.smspower.org/Games/WinterOlympics-SMS",
	"Wolfchild":                              "https://www.smspower.org/Games/Wolfchild-SMS",
	"Wonder Boy":                             "https://www.smspower.org/Games/WonderBoy-SMS",
	"Wonder Boy III - The Dragon's Trap":     "https://www.smspower.org/Games/WonderBoyIII-SMS",
	"Wonder Boy in Monster Land":             "https://www.smspower.org/Games/WonderBoyInMonsterLand-SMS",
	"Wonder Boy in Monster World":            "https://www.smspower.org/Games/WonderBoyInMonsterWorld-SMS",
	"Wonsiin":                                "https://www.smspower.org/Games/Wonsiin-SMS",
	"Woody Pop - Shinjinrui no Block Kuzugi": "https://www.smspower.org/Games/WoodyPop-SMS",
	"World Class Leader Board":               "https://www.smspower.org/Games/WorldClassLeaderBoard-SMS",
	"World Cup Italia '90":                   "https://www.smspower.org/Games/WorldCupItalia90-SMS",
	"World Cup USA 94":                       "https://www.smspower.org/Games/WorldCupUSA94-SMS",
	"World Games":                            "https://www.smspower.org/Games/WorldGames-SMS",
	"World Grand Prix":                       "https://www.smspower.org/Games/WorldGrandPrix-SMS",
	"World Soccer":                           "https://www.smspower.org/Games/WorldSoccer-SMS",
	"WWF WrestleMania Steel Cage Challenge":  "https://www.smspower.org/Games/WWFWrestleManiaSteelCageChallenge-SMS",
	"Xenon 2 - Megablast":                    "https://www.smspower.org/Games/Xenon2-SMS",
	"X-Men - Mojo World":                     "https://www.smspower.org/Games/XMenMojoWorld-SMS",
	"Xyzolog":                                "https://www.smspower.org/Games/Xyzolog-SMS",
	"Y's - The Vanished Omens":               "https://www.smspower.org/Games/Ys-SMS",
	"Zaxxon 3-D":                             "https://www.smspower.org/Games/Zaxxon3D-SMS",
	"Zillion":                                "https://www.smspower.org/Games/Zillion-SMS",
	"Zillion II - The Tri Formation":         "https://www.smspower.org/Games/ZillionII-SMS",
	"Zool - Ninja of the 'Nth' Dimension":    "https://www.smspower.org/Games/Zool-SMS",
}
