package main

func generateMisterSMSGames() {
	smsTitleAdded := make(map[string]bool)
	smsImages := make(map[string]string)
	smsGameList := []string{}
	compileMisterConsoleData(smsTitleAdded, &smsGameList, smsImages, "sms")
	generateMisterConsoleHTML("SMS", &smsGameList, smsImages, smsVideos, "sms")

}

var smsVideos = map[string]string{}

var smsGameInfo = map[string]string{
	"20 em 1":                            "https://www.smspower.org/Games/20Em1-SMS",
	"3D Gunner":                          "https://www.smspower.org/Games/3DGunner-SMS",
	"4 PAK All Action":                   "https://www.smspower.org/Games/4PakAllAction-SMS",
	"94 Super World Cup Soccer":          "https://www.smspower.org/Games/94SuperWorldCupSoccer-SMS",
	"Ace of Aces":                        "https://www.smspower.org/Games/AceOfAces-SMS",
	"Action Fighter":                     "https://www.smspower.org/Games/ActionFighter-SMS",
	"The Addams Family":                  "https://www.smspower.org/Games/AddamsFamily-SMS",
	"Aerial Assault":                     "https://www.smspower.org/Games/AerialAssault-SMS",
	"After Burner":                       "https://www.smspower.org/Games/AfterBurner-SMS",
	"Air Rescue":                         "https://www.smspower.org/Games/AirRescue-SMS",
	"Aladdin":                            "https://www.smspower.org/Games/Aladdin-SMS",
	"Alex Kidd - High-Tech World":        "https://www.smspower.org/Games/AlexKiddHighTechWorld-SMS",
	"Alex Kidd in Miracle World":         "https://www.smspower.org/Games/AlexKiddInMiracleWorld-SMS",
	"Alex Kidd in Shinobi World":         "https://www.smspower.org/Games/AlexKiddInShinobiWorld-SMS",
	"Alex Kidd - The Lost Stars":         "https://www.smspower.org/Games/AlexKiddTheLostStars-SMS",
	"Alf":                                "https://www.smspower.org/Games/Alf-SMS",
	"Alibaba and 40 Thieves":             "https://www.smspower.org/Games/AlibabaAnd40Thieves-SMS",
	"Alien 3":                            "https://www.smspower.org/Games/Alien3-SMS",
	"Alien Storm":                        "https://www.smspower.org/Games/AlienStorm-SMS",
	"Alien Syndrome":                     "https://www.smspower.org/Games/AlienSyndrome-SMS",
	"Altered Beast":                      "https://www.smspower.org/Games/AlteredBeast-SMS",
	"American Baseball":                  "https://www.smspower.org/Games/AmericanBaseball-SMS",
	"American Pro Football":              "https://www.smspower.org/Games/AmericanProFootball-SMS",
	"Andre Agassi Tennis":                "https://www.smspower.org/Games/AndreAgassiTennis-SMS",
	"Anmitsu Hime":                       "https://www.smspower.org/Games/AnmitsuHime-SMS",
	"Arcade Smash Hits":                  "https://www.smspower.org/Games/ArcadeSmashHits-SMS",
	"Argos no Juujiken":                  "https://www.smspower.org/Games/ArgosNoJuujiken-SMS",
	"Ariel - The Little Mermaid":         "https://www.smspower.org/Games/ArielTheLittleMermaid-SMS",
	"Ashura":                             "https://www.smspower.org/Games/Ashura-SMS",
	"Assault City":                       "https://www.smspower.org/Games/AssaultCity-SMS",
	"Astérix":                            "https://www.smspower.org/Games/Asterix-SMS",
	"Astérix and the Great Rescue":       "https://www.smspower.org/Games/AsterixAndTheGreatRescue-SMS",
	"Astérix and the Secret Mission":     "https://www.smspower.org/Games/AsterixAndTheSecretMission-SMS",
	"Astro Warrior":                      "https://www.smspower.org/Games/AstroWarrior-SMS",
	"The A-Team":                         "https://www.smspower.org/Games/ATeam-SMS",
	"Aztec Adventure":                    "https://www.smspower.org/Games/AztecAdventure-SMS",
	"Back to the Future Part II":         "https://www.smspower.org/Games/BackToTheFuturePartII-SMS",
	"Back to the Future Part III":        "https://www.smspower.org/Games/BackToTheFuturePartIII-SMS",
	"Baku Baku":                          "https://www.smspower.org/Games/BakuBaku-SMS",
	"Bank Panic":                         "https://www.smspower.org/Games/BankPanic-SMS",
	"Simpsons - Bart vs. The World, The": "https://www.smspower.org/Games/BartVsTheWorld-SMS",
	"Basketball Nightmare":               "https://www.smspower.org/Games/BasketballNightmare-SMS",
	"Batman Returns":                     "https://www.smspower.org/Games/BatmanReturns-SMS",
	"Battlemaniacs":                      "https://www.smspower.org/Games/Battlemaniacs-SMS",
	"Battle Out Run":                     "https://www.smspower.org/Games/BattleOutRun-SMS",
	"Black Belt":                         "https://www.smspower.org/Games/BlackBelt-SMS",
	"Blade Eagle 3-D":                    "https://www.smspower.org/Games/BladeEagle3D-SMS",
	"Block Hole":                         "https://www.smspower.org/Games/BlockHole-SMS",
	"BMX Trial Alex Kidd":                "https://www.smspower.org/Games/BMXTrialAlexKidd-SMS",
	"Bomber Raid":                        "https://www.smspower.org/Games/BomberRaid-SMS",
	"Bonanza Bros.":                      "https://www.smspower.org/Games/BonanzaBros-SMS",
	"Bonkers Wax Up!":                    "https://www.smspower.org/Games/BonkersWaxUp-SMS",
	"Bubble Bobble":                      "https://www.smspower.org/Games/BubbleBobble-SMS",
	"Buggy Run":                          "https://www.smspower.org/Games/BuggyRun-SMS",
	"California Games":                   "https://www.smspower.org/Games/CaliforniaGames-SMS",
	"California Games II":                "https://www.smspower.org/Games/CaliforniaGamesII-SMS",
	"Captain Silver":                     "https://www.smspower.org/Games/CaptainSilver-SMS",
	"Casino Games":                       "https://www.smspower.org/Games/CasinoGames-SMS",
	"Castle of Illusion - Starring Mickey Mouse": "https://www.smspower.org/Games/CastleOfIllusion-SMS",
	"Championship Hockey":                        "https://www.smspower.org/Games/ChampionshipHockey-SMS",
	"Champions of Europe":                        "https://www.smspower.org/Games/ChampionsOfEurope-SMS",
	"Chapolim x Drácula - Um Duelo Assustador":   "https://www.smspower.org/Games/ChapolimXDracula-SMS",
	"Chase H.Q.":                   "https://www.smspower.org/Games/ChaseHQ-SMS",
	"Cheese Cat-Astrophe":          "https://www.smspower.org/Games/CheeseCatastrophe-SMS",
	"Choplifter":                   "https://www.smspower.org/Games/Choplifter-SMS",
	"Chuck Rock":                   "https://www.smspower.org/Games/ChuckRock-SMS",
	"Chuck Rock II - Son of Chuck": "https://www.smspower.org/Games/ChuckRockII-SMS",
	"Cloud Master":                 "https://www.smspower.org/Games/CloudMaster-SMS",
	"Color & Switch Test":          "https://www.smspower.org/Games/ColorAndSwitchTest-SMS",
	"Columns":                      "https://www.smspower.org/Games/Columns-SMS",
	"Comical Machine Gun Joe":      "https://www.smspower.org/Games/ComicalMachineGunJoe-SMS",
	"Comic Bakery":                 "https://www.smspower.org/Games/ComicBakery-SMS",
	"Cool Spot":                    "https://www.smspower.org/Games/CoolSpot-SMS",
	"Cosmic Spacehead":             "https://www.smspower.org/Games/CosmicSpacehead-SMS",
	"C_So!":                        "https://www.smspower.org/Games/CSoMsx-SMS",
	"The Cyber Shinobi":            "https://www.smspower.org/Games/CyberShinobi-SMS",
	"Cyborg Hunter":                "https://www.smspower.org/Games/CyborgHunter-SMS",
	"Cyborg Z":                     "https://www.smspower.org/Games/CyborgZ-SMS",
	"Daffy Duck in Hollywood":      "https://www.smspower.org/Games/DaffyDuckInHollywood-SMS",
	"Dallyeora Pigu Wang":          "https://www.smspower.org/Games/DallyeoraPiguWang-SMS",
	"Danan - The Jungle Fighter":   "https://www.smspower.org/Games/DananTheJungleFighter-SMS",
	"Dead Angle":                   "https://www.smspower.org/Games/DeadAngle-SMS",
	"Deep Duck Trouble":            "https://www.smspower.org/Games/DeepDuckTrouble-SMS",
	"Desert Speedtrap - Starring Road Runner and Wile E. Coyote": "https://www.smspower.org/Games/DesertSpeedtrap-SMS",
	"Desert Strike": "https://www.smspower.org/Games/DesertStrike-SMS",
	"Dick Tracy":    "https://www.smspower.org/Games/DickTracy-SMS",
	"Dinobasher - Starring Bignose the Caveman": "https://www.smspower.org/Games/Dinobasher-SMS",
	"The Dinosaur Dooley":                       "https://www.smspower.org/Games/DinosaurDooley-SMS",
	"Double Dragon":                             "https://www.smspower.org/Games/DoubleDragon-SMS",
	"Double Hawk":                               "https://www.smspower.org/Games/DoubleHawk-SMS",
	"Bram Stoker's Dracula":                     "https://www.smspower.org/Games/Dracula-SMS",
	"Dragon - The Bruce Lee Story":              "https://www.smspower.org/Games/Dragon-SMS",
	"Dragon Crystal":                            "https://www.smspower.org/Games/DragonCrystal-SMS",
	"Dr. HELLO":                                 "https://www.smspower.org/Games/DrHello-SMS",
	"Dynamite Duke":                             "https://www.smspower.org/Games/DynamiteDuke-SMS",
	"Dynamite Dux":                              "https://www.smspower.org/Games/DynamiteDux-SMS",
	"Dynamite Headdy":                           "https://www.smspower.org/Games/DynamiteHeaddy-SMS",
	"Eagles 5":                                  "https://www.smspower.org/Games/Eagles5-SMS",
	"Earthworm Jim":                             "https://www.smspower.org/Games/EarthwormJim-SMS",
	"Ecco the Dolphin":                          "https://www.smspower.org/Games/EccoTheDolphin-SMS",
	"Ecco - The Tides of Time":                  "https://www.smspower.org/Games/EccoTheTidesOfTime-SMS",
	"E.I. - Exa Innova":                         "https://www.smspower.org/Games/EIExaInnova-SMS",
	"Enduro Racer":                              "https://www.smspower.org/Games/EnduroRacer-SMS",
	"E-SWAT":                                    "https://www.smspower.org/Games/ESWAT-SMS",
	"F1":                                        "https://www.smspower.org/Games/F1-SMS",
	"F-16 Fighting Falcon":                      "https://www.smspower.org/Games/F16FightingFalcon-SMS",
	"F-1 Spirit - The way to Formula-1":         "https://www.smspower.org/Games/F1Spirit-SMS",
	"Fantastic Dizzy":                           "https://www.smspower.org/Games/FantasticDizzy-SMS",
	"Fantasy Zone":                              "https://www.smspower.org/Games/FantasyZone-SMS",
	"Fantasy Zone II - The tears of OPA-OPA":    "https://www.smspower.org/Games/FantasyZoneII-SMS",
	"Fantasy Zone - The Maze":                   "https://www.smspower.org/Games/FantasyZoneTheMaze-SMS",
	"FA Tetris":                                 "https://www.smspower.org/Games/FATetris-SMS",
	"Férias Frustradas do Pica Pau":             "https://www.smspower.org/Games/FeriasFrustradasDoPicaPau-SMS",
	"FIFA International Soccer":                 "https://www.smspower.org/Games/FIFAInternationalSoccer-SMS",
	"Fire & Forget II":                          "https://www.smspower.org/Games/FireAndForgetII-SMS",
	"Fire & Ice":                                "https://www.smspower.org/Games/FireAndIce-SMS",
	"The Flash":                                 "https://www.smspower.org/Games/Flash-SMS",
	"Flashpoint":                                "https://www.smspower.org/Games/Flashpoint-SMS",
	"The Flintstones":                           "https://www.smspower.org/Games/Flintstones-SMS",
	"Forgotten Worlds":                          "https://www.smspower.org/Games/ForgottenWorlds-SMS",
	"Fushigi no Oshiro Pit Pot":                 "https://www.smspower.org/Games/FushigiNoOshiroPitPot-SMS",
	"Gaegujangi Kkachi":                         "https://www.smspower.org/Games/GaegujangiKkachi-SMS",
	"Gain Ground":                               "https://www.smspower.org/Games/GainGround-SMS",
	"Galactic Protector":                        "https://www.smspower.org/Games/GalacticProtector-SMS",
	"Galaxian":                                  "https://www.smspower.org/Games/Galaxian-SMS",
	"Galaxy Force":                              "https://www.smspower.org/Games/GalaxyForce-SMS",
	"Game Box Série Esportes Radicais":          "https://www.smspower.org/Games/GameBoxSerieEsportesRadicais-SMS",
	"Game de check! Koutsuu Anzen":              "https://www.smspower.org/Games/GameDeCheckKoutsuuAnzen-SMS",
	"Gangcheol RoboCop":                         "https://www.smspower.org/Games/GangcheolRobocop-SMS",
	"Gangster Town":                             "https://www.smspower.org/Games/GangsterTown-SMS",
	"Gauntlet":                                  "https://www.smspower.org/Games/Gauntlet-SMS",
	"Geraldinho":                                "https://www.smspower.org/Games/Geraldinho-SMS",
	"Ghostbusters":                              "https://www.smspower.org/Games/Ghostbusters-SMS",
	"Ghost House":                               "https://www.smspower.org/Games/GhostHouse-SMS",
	"Ghouls'n Ghosts":                           "https://www.smspower.org/Games/GhoulsNGhosts-SMS",
	"Global Defense":                            "https://www.smspower.org/Games/GlobalDefense-SMS",
	"Global Gladiators":                         "https://www.smspower.org/Games/GlobalGladiators-SMS",
	"G-LOC - Air Battle":                        "https://www.smspower.org/Games/GLOCAirBattle-SMS",
	"Golden Axe":                                "https://www.smspower.org/Games/GoldenAxe-SMS",
	"Golden Axe Warrior":                        "https://www.smspower.org/Games/GoldenAxeWarrior-SMS",
	"Golfamania":                                "https://www.smspower.org/Games/Golfamania-SMS",
	"Golvellius - Valley of Doom":               "https://www.smspower.org/Games/Golvellius-SMS",
	"GP Rider":                                  "https://www.smspower.org/Games/GPRider-SMS",
	"Great Baseball":                            "https://www.smspower.org/Games/GreatBaseball-SMS",
	"Great Basketball":                          "https://www.smspower.org/Games/GreatBasketball-SMS",
	"Great Golf":                                "https://www.smspower.org/Games/GreatGolf-SMS",
	"Great Golf [Japan]":                        "https://www.smspower.org/Games/GreatGolfJP-SMS",
	"Great Ice Hockey":                          "https://www.smspower.org/Games/GreatIceHockey-SMS",
	"Great Soccer":                              "https://www.smspower.org/Games/GreatSoccerCard-SMS",
	"Great Volleyball":                          "https://www.smspower.org/Games/GreatVolleyball-SMS",
	"Gun.Smoke":                                 "https://www.smspower.org/Games/GunSmoke-SMS",
	"Hang On":                                   "https://www.smspower.org/Games/HangOn-SMS",
	"Heavyweight Champ":                         "https://www.smspower.org/Games/HeavyweightChamp-SMS",
	"Heroes of the Lance":                       "https://www.smspower.org/Games/HeroesOfTheLance-SMS",
	"Hi-Com The Best Game Collection [Series]": "https://www.smspower.org/Games/HiComTheBestGameCollection-SMS",
	"High School! Kimengumi":                   "https://www.smspower.org/Games/HighSchoolKimengumi-SMS",
	"Hokuto no Ken":                            "https://www.smspower.org/Games/HokutoNoKen-SMS",
	"Home Alone":                               "https://www.smspower.org/Games/HomeAlone-SMS",
	"Hong Kil Dong":                            "https://www.smspower.org/Games/HongKilDong-SMS",
	"Hook":                                     "https://www.smspower.org/Games/Hook-SMS",
	"Hoshi wo Sagashite...":                    "https://www.smspower.org/Games/HoshiWoSagashite-SMS",
	"Impossible Mission":                       "https://www.smspower.org/Games/ImpossibleMission-SMS",
	"The Incredible Crash Dummies":             "https://www.smspower.org/Games/IncredibleCrashDummies-SMS",
	"The Incredible Hulk":                      "https://www.smspower.org/Games/IncredibleHulk-SMS",
	"Indiana Jones and the Last Crusade - The Action Game": "https://www.smspower.org/Games/IndianaJonesAndTheLastCrusade-SMS",
	"James Bond 007 - The Duel":                            "https://www.smspower.org/Games/JamesBond007TheDuel-SMS",
	"James Pond II - Codename RoboCod":                     "https://www.smspower.org/Games/JamesPondII-SMS",
	"Janggun-ui Adeul":                                     "https://www.smspower.org/Games/JanggunuiAdeul-SMS",
	"Jang Pung 3":                                          "https://www.smspower.org/Games/JangPung3-SMS",
	"Jang Pung II":                                         "https://www.smspower.org/Games/JangPungII-SMS",
	"Joe Montana Football":                                 "https://www.smspower.org/Games/JoeMontanaFootball-SMS",
	"Jungle Book, The":                                     "https://www.smspower.org/Games/JungleBook-SMS",
	"Jurassic Park":                                        "https://www.smspower.org/Games/JurassicPark-SMS",
	"Kenseiden":                                            "https://www.smspower.org/Games/Kenseiden-SMS",
	"King & Balloon":                                       "https://www.smspower.org/Games/KingAndBalloon-SMS",
	"King's Quest - Quest for the Crown":                   "https://www.smspower.org/Games/KingsQuest-SMS",
	"KLAX":                                                 "https://www.smspower.org/Games/KLAX-SMS",
	"Krisalis Development System":                          "https://www.smspower.org/Games/KrisalisDevelopmentSystem-SMS",
	"Krusty's Fun House":                                   "https://www.smspower.org/Games/KrustysFunHouse-SMS",
	"Kung Fu Kid":                                          "https://www.smspower.org/Games/KungFuKid-SMS",
	"Land of Illusion - Starring Mickey Mouse":             "https://www.smspower.org/Games/LandOfIllusion-SMS",
	"Laser Ghost":                                          "https://www.smspower.org/Games/LaserGhost-SMS",
	"Legend of Illusion - Starring Mickey Mouse":           "https://www.smspower.org/Games/LegendOfIllusion-SMS",
	"Lemmings":                                             "https://www.smspower.org/Games/Lemmings-SMS",
	"Lemmings 2 - The Tribes":                              "https://www.smspower.org/Games/Lemmings2-SMS",
	"Lethal Weapon 3":                                      "https://www.smspower.org/Games/LethalWeapon3-SMS",
	"Line of Fire":                                         "https://www.smspower.org/Games/LineOfFire-SMS",
	"Lion King, The":                                       "https://www.smspower.org/Games/LionKing-SMS",
	"Lord of the Sword":                                    "https://www.smspower.org/Games/LordOfTheSword-SMS",
	"The Lucky Dime Caper - Starring Donald Duck":          "https://www.smspower.org/Games/LuckyDimeCaper-SMS",
	"Mahjong Sengoku Jidai":                                "https://www.smspower.org/Games/MahjongSengokuJidai-SMS",
	"Marble Madness":                                       "https://www.smspower.org/Games/MarbleMadness-SMS",
	"Marksman Shooting & Trap Shooting":                    "https://www.smspower.org/Games/MarksmanShootingAndTrapShooting-SMS",
	"Marksman Shooting":                                    "https://www.smspower.org/Games/MarksmanShootingTrapShootingSafariHunt-SMS",
	"Master of Darkness":                                   "https://www.smspower.org/Games/MasterOfDarkness-SMS",
	"Masters of Combat":                                    "https://www.smspower.org/Games/MastersOfCombat-SMS",
	"Maze Hunter 3-D":                                      "https://www.smspower.org/Games/MazeHunter3D-SMS",
	"Knightmare II - The Maze of Galious":                  "https://www.smspower.org/Games/MazeOfGalious-SMS",
	"Megumi Rescue":                                        "https://www.smspower.org/Games/MegumiRescue-SMS",
	"Mercs":                                                "https://www.smspower.org/Games/Mercs-SMS",
	"Mickey's Ultimate Challenge":                          "https://www.smspower.org/Games/MickeysUltimateChallenge-SMS",
	"Micro Machines":                                       "https://www.smspower.org/Games/MicroMachines-SMS",
	"The Micro Xevious":                                    "https://www.smspower.org/Games/MicroXevious-SMS",
	"Miracle Warriors - Seal of The Dark Lord":             "https://www.smspower.org/Games/MiracleWarriors-SMS",
	"Missile Defense 3-D":                                  "https://www.smspower.org/Games/MissileDefense3D-SMS",
	"Mônica no Castelo do Dragão":                          "https://www.smspower.org/Games/MonicaNoCasteloDoDragao-SMS",
	"Monopoly":                                             "https://www.smspower.org/Games/Monopoly-SMS",
	"Montezuma's Revenge - Featuring Panama Joe":           "https://www.smspower.org/Games/MontezumasRevenge-SMS",
	"Michael Jackson's Moonwalker":                         "https://www.smspower.org/Games/Moonwalker-SMS",
	"Mopiranger":                                           "https://www.smspower.org/Games/Mopiranger-SMS",
	"Mortal Kombat":                                        "https://www.smspower.org/Games/MortalKombat-SMS",
	"Mortal Kombat 3":                                      "https://www.smspower.org/Games/MortalKombat3-SMS",
	"Mortal Kombat II":                                     "https://www.smspower.org/Games/MortalKombatII-SMS",
	"Ms. Pac-Man":                                          "https://www.smspower.org/Games/MsPacMan-SMS",
	"My Hero":                                              "https://www.smspower.org/Games/MyHero-SMS",
	"NBA Jam":                                              "https://www.smspower.org/Games/NBAJam-SMS",
	"Nekkyuu Koushien":                                     "https://www.smspower.org/Games/NekkyuuKoushien-SMS",
	"Nemesis":                                              "https://www.smspower.org/Games/Nemesis-SMS",
	"Nemesis 2":                                            "https://www.smspower.org/Games/Nemesis2-SMS",
	"New Boggle Boggle 2":                                  "https://www.smspower.org/Games/NewBoggleBoggle2-SMS",
	"The NewZealand Story":                                 "https://www.smspower.org/Games/NewZealandStory-SMS",
	"The Ninja":                                            "https://www.smspower.org/Games/Ninja-SMS",
	"Ninja Gaiden":                                         "https://www.smspower.org/Games/NinjaGaiden-SMS",
	"Olympic Gold":                                         "https://www.smspower.org/Games/OlympicGold-SMS",
	"Operation Wolf":                                       "https://www.smspower.org/Games/OperationWolf-SMS",
	"The Ottifants":                                        "https://www.smspower.org/Games/Ottifants-SMS",
	"Out Run":                                              "https://www.smspower.org/Games/OutRun-SMS",
	"Out Run 3-D":                                          "https://www.smspower.org/Games/OutRun3D-SMS",
	"Out Run Europa":                                       "https://www.smspower.org/Games/OutRunEuropa-SMS",
	"Pac-Mania":                                            "https://www.smspower.org/Games/PacMania-SMS",
	"Paperboy":                                             "https://www.smspower.org/Games/Paperboy-SMS",
	"Parlour Games":                                        "https://www.smspower.org/Games/ParlourGames-SMS",
	"Pat Riley Basketball":                                 "https://www.smspower.org/Games/PatRileyBasketball-SMS",
	"Penguin Adventure":                                    "https://www.smspower.org/Games/PenguinAdventure-SMS",
	"Penguin Land":                                         "https://www.smspower.org/Games/PenguinLand-SMS",
	"PGA TOUR Golf":                                        "https://www.smspower.org/Games/PGATourGolf-SMS",
	"Phantasy Star":                                        "https://www.smspower.org/Games/PhantasyStar-SMS",
	"Pit-Fighter":                                          "https://www.smspower.org/Games/PitFighter-SMS",
	"Pooyan":                                               "https://www.smspower.org/Games/Pooyan-SMS",
	"Populous":                                             "https://www.smspower.org/Games/Populous-SMS",
	"Poseidon Wars 3-D":                                    "https://www.smspower.org/Games/PoseidonWars3D-SMS",
	"Power Boggle Boggle":                                  "https://www.smspower.org/Games/PowerBoggleBoggle-SMS",
	"Power Strike":                                         "https://www.smspower.org/Games/PowerStrike-SMS",
	"Power Strike II":                                      "https://www.smspower.org/Games/PowerStrikeII-SMS",
	"Predator 2":                                           "https://www.smspower.org/Games/Predator2-SMS",
	"Prince of Persia":                                     "https://www.smspower.org/Games/PrinceOfPersia-SMS",
	"Promocao Especial M.System III Compact":               "https://www.smspower.org/Games/PromocaoEspecialMSystemIIICompact-SMS",
	"Pro Wrestling":                                        "https://www.smspower.org/Games/ProWrestling-SMS",
	"The Pro Yakyuu - Pennant Race":                        "https://www.smspower.org/Games/ProYakyuu-SMS",
	"Psychic World":                                        "https://www.smspower.org/Games/PsychicWorld-SMS",
	"Psycho Fox":                                           "https://www.smspower.org/Games/PsychoFox-SMS",
	"Putt & Putter":                                        "https://www.smspower.org/Games/PuttAndPutter-SMS",
	"Puznic":                                               "https://www.smspower.org/Games/Puznic-SMS",
	"Quartet":                                              "https://www.smspower.org/Games/Quartet-SMS",
	"Quest for the Shaven Yak Starring Ren Hoëk & Stimpy": "https://www.smspower.org/Games/QuestForTheShavenYak-SMS",
	"Rainbow Islands":                       "https://www.smspower.org/Games/RainbowIslands-SMS",
	"Rambo III":                             "https://www.smspower.org/Games/RamboIII-SMS",
	"Rampage":                               "https://www.smspower.org/Games/Rampage-SMS",
	"Rampart":                               "https://www.smspower.org/Games/Rampart-SMS",
	"Rastan":                                "https://www.smspower.org/Games/Rastan-SMS",
	"R.C. Grand Prix":                       "https://www.smspower.org/Games/RCGrandPrix-SMS",
	"Renegade":                              "https://www.smspower.org/Games/Renegade-SMS",
	"Rescue Mission":                        "https://www.smspower.org/Games/RescueMission-SMS",
	"Road Fighter":                          "https://www.smspower.org/Games/RoadFighter-SMS",
	"Road Rash":                             "https://www.smspower.org/Games/RoadRash-SMS",
	"RoboCop 3":                             "https://www.smspower.org/Games/RoboCop3-SMS",
	"RoboCop versus The Terminator":         "https://www.smspower.org/Games/RoboCopVersusTheTerminator-SMS",
	"Rocky":                                 "https://www.smspower.org/Games/Rocky-SMS",
	"R-Type":                                "https://www.smspower.org/Games/RType-SMS",
	"Running Battle":                        "https://www.smspower.org/Games/RunningBattle-SMS",
	"Sagaia":                                "https://www.smspower.org/Games/Sagaia-SMS",
	"Samgukji III":                          "https://www.smspower.org/Games/SamgukjiIII-SMS",
	"Sapo Xulé O Mestre do Kung Fu":         "https://www.smspower.org/Games/SapoXuleOMestreDoKungFu-SMS",
	"Sapo Xulé S.O.S. Lagoa Poluída":        "https://www.smspower.org/Games/SapoXuleSOSLagoaPoluida-SMS",
	"Satellite 7":                           "https://www.smspower.org/Games/Satellite7-SMS",
	"Scramble Spirits":                      "https://www.smspower.org/Games/ScrambleSpirits-SMS",
	"Sega Chess":                            "https://www.smspower.org/Games/SegaChess-SMS",
	"Sega Graphic Board":                    "https://www.smspower.org/Games/SegaGraphicBoard-SMS",
	"Sega Master System [System ROM]":       "https://www.smspower.org/Games/SegaMasterSystemRom-SMS",
	"Sega World Tournament Golf":            "https://www.smspower.org/Games/SegaWorldTournamentGolf-SMS",
	"Shadow Dancer - The Secret Of Shinobi": "https://www.smspower.org/Games/ShadowDancer-SMS",
	"Shadow of the Beast":                   "https://www.smspower.org/Games/ShadowOfTheBeast-SMS",
	"Shanghai":                              "https://www.smspower.org/Games/Shanghai-SMS",
	"Shinobi":                               "https://www.smspower.org/Games/Shinobi-SMS",
	"Shooting Gallery":                      "https://www.smspower.org/Games/ShootingGallery-SMS",
	"Sítio do Picapau Amarelo":              "https://www.smspower.org/Games/SitioDoPicapauAmarelo-SMS",
	"Sky Fighter":                           "https://www.smspower.org/Games/SkyFighter-SMS",
	"Sky Jaguar":                            "https://www.smspower.org/Games/SkyJaguar-SMS",
	"Slap Shot":                             "https://www.smspower.org/Games/SlapShot-SMS",
	"The Smurfs":                            "https://www.smspower.org/Games/Smurfs-SMS",
	"The Smurfs Travel the World":           "https://www.smspower.org/Games/SmurfsTravelTheWorld-SMS",
	"Solomon no Kagi - Oujo Rihita no Namida": "https://www.smspower.org/Games/SolomonNoKagi-SMS",
	"Sonic Blast":                    "https://www.smspower.org/Games/SonicBlast-SMS",
	"Sonic Chaos":                    "https://www.smspower.org/Games/SonicChaos-SMS",
	"Sonic's Edusoft":                "https://www.smspower.org/Games/SonicsEdusoft-SMS",
	"Sonic Spinball":                 "https://www.smspower.org/Games/SonicSpinball-SMS",
	"Sonic The Hedgehog":             "https://www.smspower.org/Games/SonicTheHedgehog-SMS",
	"Sonic The Hedgehog 2":           "https://www.smspower.org/Games/SonicTheHedgehog2-SMS",
	"Space Gun":                      "https://www.smspower.org/Games/SpaceGun-SMS",
	"Space Harrier":                  "https://www.smspower.org/Games/SpaceHarrier-SMS",
	"Space Harrier 3-D":              "https://www.smspower.org/Games/SpaceHarrier3D-SMS",
	"Special Criminal Investigation": "https://www.smspower.org/Games/SpecialCriminalInvestigation-SMS",
	"Speedball":                      "https://www.smspower.org/Games/Speedball-SMS",
	"Speedball 2":                    "https://www.smspower.org/Games/Speedball2-SMS",
	"SpellCaster":                    "https://www.smspower.org/Games/SpellCaster-SMS",
	"Spider-Man - Return of the Sinister Six": "https://www.smspower.org/Games/SpiderManReturnOfTheSinisterSix-SMS",
	"Sports Pad Football":                     "https://www.smspower.org/Games/SportsPadFootball-SMS",
	"Spy vs Spy":                              "https://www.smspower.org/Games/SpyVsSpy-SMS",
	"Star Wars":                               "https://www.smspower.org/Games/StarWars-SMS",
	"Street Fighter II'":                      "https://www.smspower.org/Games/StreetFighterII-SMS",
	"Street Master":                           "https://www.smspower.org/Games/StreetMaster-SMS",
	"Streets of Rage":                         "https://www.smspower.org/Games/StreetsOfRage-SMS",
	"Streets of Rage II":                      "https://www.smspower.org/Games/StreetsOfRageII-SMS",
	"Strider":                                 "https://www.smspower.org/Games/Strider-SMS",
	"Strider II":                              "https://www.smspower.org/Games/StriderII-SMS",
	"Submarine Attack":                        "https://www.smspower.org/Games/SubmarineAttack-SMS",
	"Suho Jeonsa":                             "https://www.smspower.org/Games/SuhoJeonsa-SMS",
	"Sukeban Deka II - Shoujo Tekkamen Densetsu": "https://www.smspower.org/Games/SukebanDekaII-SMS",
	"Summer Games":                           "https://www.smspower.org/Games/SummerGames-SMS",
	"Super Basketball":                       "https://www.smspower.org/Games/SuperBasketball-SMS",
	"Super Bioman I":                         "https://www.smspower.org/Games/SuperBiomanI-SMS",
	"Super Boy 4":                            "https://www.smspower.org/Games/SuperBoy4-SMS",
	"Super Boy I":                            "https://www.smspower.org/Games/SuperBoyI-SMS",
	"Super Boy II":                           "https://www.smspower.org/Games/SuperBoyII-SMS",
	"Super Boy III":                          "https://www.smspower.org/Games/SuperBoyIII-SMS",
	"Super Bubble Bobble":                    "https://www.smspower.org/Games/SuperBubbleBobble-SMS",
	"Super Columns":                          "https://www.smspower.org/Games/SuperColumns-SMS",
	"Super Kick Off":                         "https://www.smspower.org/Games/SuperKickOff-SMS",
	"Superman - The Man of Steel":            "https://www.smspower.org/Games/Superman-SMS",
	"Super Monaco GP":                        "https://www.smspower.org/Games/SuperMonacoGP-SMS",
	"Super Monaco GP II":                     "https://www.smspower.org/Games/SuperMonacoGPII-SMS",
	"Super Off Road":                         "https://www.smspower.org/Games/SuperOffRoad-SMS",
	"Super Racing":                           "https://www.smspower.org/Games/SuperRacing-SMS",
	"Super Smash T.V.":                       "https://www.smspower.org/Games/SuperSmashTV-SMS",
	"Super Space Invaders":                   "https://www.smspower.org/Games/SuperSpaceInvaders-SMS",
	"Super Tennis":                           "https://www.smspower.org/Games/SuperTennis-SMS",
	"T2 - The Arcade Game":                   "https://www.smspower.org/Games/T2TheArcadeGame-SMS",
	"Taz in Escape from Mars":                "https://www.smspower.org/Games/TazInEscapeFromMars-SMS",
	"Taz-Mania":                              "https://www.smspower.org/Games/TazMania-SMS",
	"Tecmo World Cup '93":                    "https://www.smspower.org/Games/TecmoWorldCup93-SMS",
	"Teddy Boy":                              "https://www.smspower.org/Games/TeddyBoy-SMS",
	"Tennis Ace":                             "https://www.smspower.org/Games/TennisAce-SMS",
	"Tensai Bakabon":                         "https://www.smspower.org/Games/TensaiBakabon-SMS",
	"Terminator, The":                        "https://www.smspower.org/Games/Terminator-SMS",
	"Terminator 2 - Judgment Day":            "https://www.smspower.org/Games/Terminator2JudgmentDay-SMS",
	"Three Dragon Story, The":                "https://www.smspower.org/Games/ThreeDragonStory-SMS",
	"Thunder Blade":                          "https://www.smspower.org/Games/ThunderBlade-SMS",
	"Time Soldiers":                          "https://www.smspower.org/Games/TimeSoldiers-SMS",
	"Tom and Jerry - The Movie":              "https://www.smspower.org/Games/TomAndJerryTheMovie-SMS",
	"Toto World 3":                           "https://www.smspower.org/Games/TotoWorld3-SMS",
	"TransBot":                               "https://www.smspower.org/Games/TransBot-SMS",
	"Trivial Pursuit - Genus Edition":        "https://www.smspower.org/Games/TrivialPursuit-SMS",
	"Turma da Mônica em - O Resgate":         "https://www.smspower.org/Games/TurmaDaMonica-SMS",
	"TV Colosso":                             "https://www.smspower.org/Games/TVColosso-SMS",
	"Ultima IV - Quest of the Avatar":        "https://www.smspower.org/Games/UltimaIV-SMS",
	"Ultimate Soccer":                        "https://www.smspower.org/Games/UltimateSoccer-SMS",
	"Vigilante":                              "https://www.smspower.org/Games/Vigilante-SMS",
	"Virtua Fighter Animation":               "https://www.smspower.org/Games/VirtuaFighterAnimation-SMS",
	"Wanted":                                 "https://www.smspower.org/Games/Wanted-SMS",
	"Where in the World is Carmen Sandiego?": "https://www.smspower.org/Games/WhereInTheWorldIsCarmenSandiego-SMS",
	"Wimbledon":                              "https://www.smspower.org/Games/Wimbledon-SMS",
	"Wimbledon II":                           "https://www.smspower.org/Games/WimbledonII-SMS",
	"Winter Olympics":                        "https://www.smspower.org/Games/WinterOlympics-SMS",
	"Wolfchild":                              "https://www.smspower.org/Games/Wolfchild-SMS",
	"Wonder Boy":                             "https://www.smspower.org/Games/WonderBoy-SMS",
	"Wonder Boy III - The Dragon's Trap":     "https://www.smspower.org/Games/WonderBoyIII-SMS",
	"Wonder Boy in Monster Land":             "https://www.smspower.org/Games/WonderBoyInMonsterLand-SMS",
	"Wonder Boy in Monster World":            "https://www.smspower.org/Games/WonderBoyInMonsterWorld-SMS",
	"Wonsiin":                                "https://www.smspower.org/Games/Wonsiin-SMS",
	"Woody Pop - Shinjinrui no Block Kuzugi": "https://www.smspower.org/Games/WoodyPop-SMS",
	"World Class Leader Board":               "https://www.smspower.org/Games/WorldClassLeaderBoard-SMS",
	"World Cup Italia '90":                   "https://www.smspower.org/Games/WorldCupItalia90-SMS",
	"World Cup USA 94":                       "https://www.smspower.org/Games/WorldCupUSA94-SMS",
	"World Games":                            "https://www.smspower.org/Games/WorldGames-SMS",
	"World Grand Prix":                       "https://www.smspower.org/Games/WorldGrandPrix-SMS",
	"World Soccer":                           "https://www.smspower.org/Games/WorldSoccer-SMS",
	"WWF WrestleMania Steel Cage Challenge":  "https://www.smspower.org/Games/WWFWrestleManiaSteelCageChallenge-SMS",
	"Xenon 2 - Megablast":                    "https://www.smspower.org/Games/Xenon2-SMS",
	"X-Men - Mojo World":                     "https://www.smspower.org/Games/XMenMojoWorld-SMS",
	"Xyzolog":                                "https://www.smspower.org/Games/Xyzolog-SMS",
	"Y's - The Vanished Omens":               "https://www.smspower.org/Games/Ys-SMS",
	"Zaxxon 3-D":                             "https://www.smspower.org/Games/Zaxxon3D-SMS",
	"Zillion":                                "https://www.smspower.org/Games/Zillion-SMS",
	"Zillion II - The Tri Formation":         "https://www.smspower.org/Games/ZillionII-SMS",
	"Zool - Ninja of the 'Nth' Dimension":    "https://www.smspower.org/Games/Zool-SMS",
}
